### ISSUE TITLE
Suggest documentation for Handling errors when running unreliable programs (broken pipes, exit non-zero, connection closed by host, etc.)

### ISSUE THREAD

**Issue by erikb85** [pexpect/pexpect#110]
This is not really a bug report, more of a question. The kind I would normally send to a mailing list. If this is the wrong place, I'm sorry.

I use pexpect to connect from a source computer (where pexpect runs) to a target computer (which pexpect communicates with) via ssh and serial. In both connections it can happen that the connection breaks down (e.g. ssh server down due to reboot of target device). How am I supposed to handle that? Currently the only way I see to meaningful handling is expecting not just my expect message but different error messages as well (e.g. "broken pipe", "Connection closed by host"), then close the spawn object, and create a completely new one. I'd be very happy if anybody could suggest a more feasable way to do that, because it only works in about 90% of the cases. Sometimes the connection still doesn't work, maybe because I try to get a new connection while the target is still rebooting. And sometimes a little gui window pops up and asks me for an ssh password, which doesn't seem to be necessary because my code logs in via sendline/expect-prompt anyway.

**Comment by jquast** [comment]
No documentation was suggested.
