### ISSUE TITLE
[feature request] pexpect.spawn supports "with statement"

### ISSUE THREAD

**Issue by zjx20** [pexpect/pexpect#111]
It should be useful if `pexpect.spawn` supports "with statement".

``` python
with pexpect.spawn("ssh foo@bar") as ssh:
  i = ssh.expect("password")
  # etc.
```

**Comment by mikepurvis** [comment]
Thanks for this functionality— I didn't know it exists until I googled my way to this ticket. Consider updating the docs? https://pexpect.readthedocs.io/en/stable/api/pexpect.html#spawn-class
