### ISSUE TITLE
pexpect does not get along well with gevent, add to FAQ

### ISSUE THREAD

**Issue by vikasdogra** [pexpect/pexpect#128]
I am using pexpect to spawn "svn" and run different commands.
It was working fine on my CentOS 5.9. When we ran the same code on a virtual machine under virtualBox running same version of CentOS it gives us following error from time to time: 
"ExceptionPexpect: isalive() encountered condition where "terminated" is 0, but there was no child process. Did someone else call waitpid() on our process?"
At some times it comes up at child.close() and sometimes immediately after spawn when i call child.expect.

Looking at pexpect code , the comment says this condition should never occur.
I am totally confused why is this happening, i am not 100% sure if it is only happening because we are running on a virtual machine or it shows up there because of some other reason.

Let me know if you need more information.

**Comment by jquast** [comment]
Superceded by FAQ entry proposal in #255
