### ISSUE TITLE
should be possible to set interact(escape_character=None) to disable escaping entirely

### ISSUE THREAD

**Issue by jquast** [pexpect/pexpect#132]
minor enhancement, this fails in both python3:
```
self.__interact_copy(escape_character, input_filter, output_filter)
AttributeError: 'NoneType' object has no attribute 'encode'
```

and 2:
```
-> 1695                 i = data.rfind(escape_character)
   1696                 if i != -1:
   1697                     data = data[:i]

TypeError: expected a character buffer object
```

**Comment by marcosps** [comment]
Hi, @jquast 
I'm trying to fix both places and I have a patch here, but how can I test pexpect in my local repo insteado of the default pexpect installed in my system?

**Comment by jquast** [comment]
using virtualenv http://docs.python-guide.org/en/latest/dev/virtualenvs/

```
pip install virtualenv
virtualenv ENV
. ENV/bin/activate
pip install ptyprocess pytest
py.test
```

**Comment by marcosps** [comment]
Hi @jquast ,

currently I dont't have time do adjust the tests to be able to run interact with None as escape character. Can you please handle this?

The patch now is ok for you? Thanks a lot!
(I worked with pull requests, so if I did something wrong, please let me know.)

**Comment by jquast** [comment]
Yes I will handle it soon, It's fine as-is, just do not delete your repo/branch.

Thanks again
