### ISSUE TITLE
pxssh should have a unicode variant, like pexpect.pxsshu

### ISSUE THREAD

**Issue by wsong** [pexpect/pexpect#169]
In Python 3, if I do:
```python
s = pxssh.pxssh()
s.login(...)
s.sendline('command')
s.prompt()
assert s.before.startswith('foobar'):
```
I get ``TypeError: startswith first arg must be bytes or a tuple of bytes, not str``

This appears to be because pxssh.pxssh inherits from spawn, not spawnu.  Is there a Unicode version of pxssh available?

**Comment by jquast** [comment]
There is not. This is similar to #92.
