### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by takluyver** [pexpect/pexpect#17]
There are at least two ports of pexpect to Windows APIs:

- Chris Gorecki's [wexpect](http://sage.math.washington.edu/home/goreckc/sage/wexpect/)
- Geert Jansen's [winpexpect](https://bitbucket.org/geertj/winpexpect/)

We could look at integrating this support into pexpect. Both Chris and Geert have said they'd be willing to help out with some initial work, but I think this would need someone committed to maintaining it and fixing the inevitable problems. I don't really use Windows myself, so I can't give it much support.

**Comment by arve0** [comment]
Any news on windows support?

**Comment by MengJueM** [comment]
Hi, this issue is closed yet. Does that means windows support is dropped?

**Comment by takluyver** [comment]
This issue is still open. 4.0, when we get it out, will have experimental Windows support. It won't simulate terminal like we do in Posix systems, but the core functionality of waiting for a particular pattern to be read should work.

**Comment by takluyver** [comment]
With a recently merged PR, it should now be possible to import Pexpect on Windows to use `pexpect.fdpexpect.fdspawn` and `pexpect.popen_spawn.PopenSpawn`. If you want to integrate it with other things, such as pyserial, it should be possible to subclass `pexpect.spawnbase.SpawnBase` (though that API is undocumented, and may still need to be changed).

We have not integrated any machinery to communicate with a subprocess in a hidden Windows console, which is what wexpect/winpexpect do. This would be more similar to the main function of Pexpect on Unix (where it uses a pty), but I don't think we could maintain the Windows code properly. However, if someone else wants to implement the communication machinery, they can reuse Pexpect's pattern-waiting code by inheriting from SpawnBase.

**Comment by tsuhaoc** [comment]
Does Pexpect 4.2.1 Windows support depends on Cygwin?

**Comment by takluyver** [comment]
No, it works on Windows natively.

**Comment by niyatia** [comment]
Hi, I am trying to use corenlp-python on my Windows Machine. The corenlp library internally uses pexpect.spawn(..). However, it gives me AttributeError saying 'module' object has no attribute spawn. Is there any workaround for this?

**Comment by takluyver** [comment]
`spawn` uses a pty, which is a Unix only feature. You can try:

- Using [PopenSpawn](http://pexpect.readthedocs.io/en/stable/api/popen_spawn.html) to run the subprocess with piped output rather than a terminal. This is technically reasonably robust, but the program you're running may not do what you want without a terminal.
- Using a tool like wexpect/winpexpect, which creates a hidden Windows console and tries to exchange data with it. This is conceptually closer to what `spawn` does on Unix, but it's an awkward hack, and I'm not interested in supporting it.
