### ISSUE TITLE
pexpect.spawn is now working with multiprocessing

### ISSUE THREAD

**Issue by radaiming** [pexpect/pexpect#171]
If I run following code:

<pre><code>#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#

import multiprocessing
import pexpect

def try_spawn():
    p = pexpect.spawn('ls')
    p.expect('test')
    p.terminate()

process = multiprocessing.Process(target=try_spawn)
process.start()
process.join()</code></pre>

I will get:

<pre><code>Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./test_p.py", line 9, in try_spawn
    p = pexpect.spawn('ls')
  File "/usr/lib64/python2.7/site-packages/pexpect/__init__.py", line 493, in __init__
    fd = sys.__stdin__.fileno()
ValueError: I/O operation on closed file</pre></code>

This issue happen on Linux/FreeBSD/OS X, your comment on the code "unless the controlling process is also not a terminal, such as cron(1). Fall-back to using CEOF and CINTR." seems it's OK to except ValueError in the code?

**Comment by jquast** [comment]
Thanks, this is resolved in master and was slated for pexpect 3.4 release but for some reason it never got published -- it will be fixed in the next release, which looks like 4.0 now, hopefully sooner than later.

ref #86, #126.

**Comment by radaiming** [comment]
Thanks a lot, I think I should search all the issues before reporting a new one.
