### ISSUE TITLE
regression: fdspawn lost its send() method in 3.4

### ISSUE THREAD

**Issue by jquast** [pexpect/pexpect#174]
looks like ``fdspawn`` inherits directly from ``SpawnBase``, which, although provides ``sendline``, does not provide ``send`` -- this method is only available from ``spawn``.  Seems like some oversight.

I think this is probably related a bit to issue #92, we should have, I presume, a ``fdspawn`` and ``fdspawnu`` variant, inheriting from ``spawn`` and ``spawnu``, respectively -- not ``SpawnBase``.

```
Date: Wed, 21 Jan 2015 10:35:10 -0500
From: Aaron <xxx>
To: contact@jeffquast.com
Subject: fdspawn in pexpect 3

Hi there,

I'm converting a project that used pexpect 2.4 to pexpect 3.2 and I'm hung
up on changes made to fdspawn. It seems that fdspawn no longer has the
'send' method:

  File "/Users/XXX/YYY/cpelib.py", line 6, in send_uboot_cmd
    exp.send(cmd)
AttributeError: 'fdspawn' object has no attribute 'send'

Is this a known problem or have I done something wrong? Looking at the
code, SpawnBase doesn't have send(),  this is added one level up in spawn,
so the error seems reasonable.

Thanks for any help you can provide.

cheers,
Aaron
```

**Comment by takluyver** [comment]
I think that was fairly deliberate - fdspawn should only assume that the fd it's given is readable, not that it's also writeable. And if you need to write to it, you can use `os.write()` - there's no need to involve pexpect in matters. I'm comfortable with breaking a few cases like this for Pexpect 4.

That shouldn't have affected 3.2, though - the refactoring that created SpawnBase is more recent than that.

**Comment by jquast** [comment]
It was available in pexpect 2.4 per the e-mail

**Comment by jquast** [comment]
Also, why does ``sendline`` work, then?

**Comment by takluyver** [comment]
Does it? I don't see a `sendline` method on either SpawnBase or fdspawn in master.

In 3.2 it may simply have been an oversight that send was removed.

**Comment by jquast** [comment]
version 3.2 on pypi has both ``send`` and ``sendline`` https://github.com/pexpect/pexpect/issues/161#issuecomment-67595218

officially, it was lost in commit 82e8e5480d17b7782b75c5cf5908bd921377a967, version "3.3" was cut in 671417beb41c21f772687c565196fdde444b053b but never released. I'll reach out to the fellow to figure out what he installed from, presumably not pip. If I install from pip, ``sendline`` and ``send`` are available.

**Comment by jquast** [comment]
(i got my numbers crossed in regards to the versions, pexpect **3.3 was** released, and it is missing there.)

**Comment by takluyver** [comment]
I'm still confused about how this arises on Pexpect 3.x. When I look at the source code, fdspawn is a subclass of spawn, which has a send method. And sure enough, when I import it:

```
In [1]: import pexpect

In [2]: pexpect.__version__
Out[2]: '3.3'

In [3]: from pexpect.fdpexpect import fdspawn

In [4]: fdspawn.se
fdspawn.send         fdspawn.sendintr     fdspawn.setlog
fdspawn.sendcontrol  fdspawn.sendline     fdspawn.setmaxread
fdspawn.sendeof      fdspawn.setecho      fdspawn.setwinsize

In [4]: fdspawn.send
Out[4]: <function pexpect.spawn.send>
```

**Comment by jquast** [comment]
Sorry, it was troubling that the 'master' branch says '3.3', I think the reporter is also using master branch, and this is why he falsely reported v3.3? This only happens for the **current** source code.

```
$ mkvirtualenv --python=`which python3` xxx3
$ pip install ptyprocess ipython
$ cd Code/pexpect
$ ipython
%paste
import pexpect.fdpexpect
import telnetlib
telsh = telnetlib.Telnet('1984.ws')
client = pexpect.fdpexpect.fdspawn(telsh)
client.expect(u'Login')
client.send(u'anonymous\r\n')
## -- End pasted text --
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-cc440b0beaea> in <module>()
      4 client = pexpect.fdpexpect.fdspawn(telsh)
      5 client.expect(u'Login')
----> 6 client.send(u'anonymous\r\n')

AttributeError: 'fdspawn' object has no attribute 'send'
```

**Comment by jquast** [comment]
fdexpect inherits from SpawnBase, not spawn since 82e8e5480d17b7782b75c5cf5908bd921377a967
https://github.com/pexpect/pexpect/blob/master/pexpect/fdpexpect.py#L30

**Comment by takluyver** [comment]
Ah, OK, so we are talking about master. We should probably update the version attribute to say something like `4.0.dev` to avoid this confusion.

I therefore revert to my earlier argument: fdspawn is fundamentally about waiting for patterns in the data read from a fd. That fd need not be writable, and if it is, you are at liberty to write to it using `os.write()` without going through Pexpect. I am comfortable with making some backwards incompatible changes in cases like this for Pexpect 4.0.

**Comment by jquast** [comment]
We took it away, vote to put it back in to prevent "support" costs, or at least to prevent a few google searches out in the wild, the maintenance cost of code otherwise here is small.
