### ISSUE TITLE
Allowed values for events argument in pexpect.run()

### ISSUE THREAD

**Issue by bancal** [pexpect/pexpect#176]
In `pexpect/__init__.py` line 209, events's value is checked to be an instance of `types.FunctionType`.

In some case it could be usefull to give an instance's method `types.MethodType`. Are there reasons for not allowing it?

Actual behavior is that If we give a `types.MethodType`, we get the error "TypeError: The callback must be a string or function."

**Comment by jquast** [comment]
probably True, could stand to be ``is callable()``.  a PR that includes tests for method would be most appreciated if you're interested.

**Comment by bancal** [comment]
Just a question ... I'm not (yet) used to github practice. What do you mean by "needs-changelog"?

**Comment by jquast** [comment]
need to add to doc/history.rst before merge

**Comment by jquast** [comment]
I had to make another PR for the minor additions I made, Closing in preference to PR #178.

Thank you again for your contribution, this will be in pexpect release version 4.0.
