### ISSUE TITLE
Pexpect on file-like object

### ISSUE THREAD

**Issue by hexum** [pexpect/pexpect#183]
Pexpect support work on already opened file descriptors (fdpexpect).
But I can't find a way to work with file-like objects, which lack of any descriptor.
For example I want to use pexpect with ssh file-like object returned from paramiko.

**Comment by takluyver** [comment]
At present, it uses a file descriptor internally, so there isn't an option to use it with a file-like object. I expect that paramiko objects have an fd somewhere, so if you can get it, you can use fdpexpect.

Also, have a look at [pxssh](http://pexpect.readthedocs.org/en/latest/api/pxssh.html).
