### ISSUE TITLE
pexpect suppresses first prompt

### ISSUE THREAD

**Issue by nbeaver** [pexpect/pexpect#184]
Minimal working example:

    #! /usr/bin/env python
    import pexpect
    child = pexpect.spawn('bash')
    index = child.expect_exact("$ ")
    child.interact()

This should show the `bash` shell prompt, but it does not.

Typing Ctrl-L will repaint the screen and show the prompt, but not all shells support Ctrl-L (e.g. `dash` does not), so sending that keystroke is not always a possible workaround.

First brought up here:

https://stackoverflow.com/questions/28860660/pexpect-eats-bash-prompt

**Comment by jquast** [comment]
Not a bug, pexpect does indeed "suppress" up until interact, as this is intended, it doesn't know you would later call interact. If you want to make a PR for adding something about it to the documentation i'll accept it.

Anyway. If you want to see the prompt (and anything else) printed up until the match, just print it:

```python
#! /usr/bin/env python
from __future__ import print_function
import pexpect
child = pexpect.spawn('bash')
index = child.expect_exact("$ ")
print(child.before + child.match, end='')
child.interact()
```

(Be careful about matching ``$ ``, not all prompts have them. If you're going to use this for any portability, you should take care to force-set PS1 and so on, an example in the ``pexpect.replwrap.bash()`` function: https://github.com/pexpect/pexpect/blob/master/pexpect/replwrap.py#L108-113 )

**Comment by jquast** [comment]
it has been a very long time since i used the original tcl/expect, but i seem to recall that it *implies* duplicating all child program output to the parent process: it always duplicates stdout, which is why the tcl/expect version doesn't require printing before interact to "see" what was given up until ``interact`` is called

**Comment by nbeaver** [comment]
Thanks, that's just what I needed to know.
