### ISSUE TITLE
Can interact() detect patterns?

### ISSUE THREAD

**Issue by willsmyth** [pexpect/pexpect#185]
Can interact() detect patterns?  If not, are there any plans to implement even a rudimentary form of pattern detection?

**Comment by takluyver** [comment]
What kind of patterns do you mean? I think it recognises one special character to get out of interact.

**Comment by jquast** [comment]
and that special character is *input*, from your keyboard.  There is no "stop interact when \<pattern\> matched"

**Comment by willsmyth** [comment]
I'm interested in detecting patterns other than the escape character (similar to Expect's interact).  I'm not trying to connect two ptys (e.g. kibitz) but would like to do some basic matching...

**Comment by takluyver** [comment]
The implementation of `interact()` is just a select loop passing data between the interactive user session and the child pty. I'd start by pulling that apart and doing something with the data as it goes through. I'm not sure it makes sense to add this kind of feature to Pexpect, but perhaps I could be convinced.

**Comment by jquast** [comment]
No plans to further customize interact with pattern matching.
