### ISSUE TITLE
ANSI seems to wrap when a line fits exactly

### ISSUE THREAD

**Issue by detly** [pexpect/pexpect#186]
Quick example:

    import pexpect.ANSI
    test_str = b'\n01234567890123456789\r\n01234567890123456789\r\n'
    ansi_term = pexpect.ANSI.ANSI(r=24, c=20)
    ansi_term.write(test_str)
    print(ansi_term)

Output:
                    
    01234567890123456789
                     
    01234567890123456789

I would not expect the extra line there, since the characters fit exactly.

This is based on trying to print the captured output of `top`, and encountering blank lines when there should be none. `top`'s output fits perfectly in a console of a certain width, but redrawing it with `pexpect.ANSI` adds these blank lines.

Under Python 2.7 on Ubuntu 14.04.1 using `pexpect` 3.3 in a virtualenv.

**Comment by detly** [comment]
By the way, the FAQ says:

> I am working on an ANSI / VT100 terminal emulator [...] but I have no working examples at this time.

If it helps, I hacked together a quick demo [here](https://gist.github.com/detly/2ca59e57ffe177e1ad77). Note that I have no idea what I'm doing with the [`pty` file descriptors](http://stackoverflow.com/questions/29057549/how-do-i-properly-handle-pty-file-descriptors-used-in-subprocess-popen), so that part may be suboptimal.

**Comment by detly** [comment]
(Digression: with some help on SO I reduced that example code to [something more reasonable](http://stackoverflow.com/a/29067444/188535). I'll add it to the docs and issue a pull request. It still shows the bug, though.)

**Comment by takluyver** [comment]
Thanks for digging into it. I'm not entirely surprised - I don't think the screen emulation part of Pexpect has got much love. There are probably better vt100 emulators around on PyPI - Pexpect's own is left there mainly in case anyone is relying on it.

**Comment by detly** [comment]
The problem is that after writing the second `9`, at `ANSI.py:329` there's a call to `self.cursor_forward()` followed by some checks that wrap the cursor if it's been constrained. This then means that by the time `\r` is received, it's too late; the cursor stays where it is, and the next `\n` just terminates an empty line.

It's not immediately obvious to me how to fix it though, so I'll just leave this observation here for now. (PyTE works fine for me too, and I don't really mind which one I use, but I thought I'd at least write it down in case anyone else can see the solution.)

**Comment by jquast** [comment]
Closing, pexpect's terminal emulation code remains next release but no longer improved, marked deprecated by https://github.com/pexpect/pexpect/pull/240 Suggest any terminal emulation / screen scraping code efforts moved to more concerted project efforts such as https://github.com/selectel/pyte
