### ISSUE TITLE
Bytes are written to logfile on python3.4, raising TypeError unless opened in binary mode.

### ISSUE THREAD

**Issue by cagney** [pexpect/pexpect#189]
Hopefully I correctly cut this down from a larger program:

    import pexpect
    import sys
    p = pexpect.spawn("/bin/bash")
    p.logfile = open("/tmp/file", "w")
    print("Escape is ^]")
    p.interact()

I get this:

    $ python3.4 ~/tmp/interact.py 
    Escape is ^]
    Traceback (most recent call last):
      File "/home/cagney/tmp/interact.py", line 7, in <module>
        p.interact()
      File "/usr/lib/python3.4/site-packages/pexpect/__init__.py", line 1624, in interact
        self.__interact_copy(escape_character, input_filter, output_filter)
      File "/usr/lib/python3.4/site-packages/pexpect/__init__.py", line 1660, in __interact_copy
        self.logfile.write(data)
    TypeError: must be str, not bytes

**Comment by jquast** [comment]
This is like #159, but different.

Just use
```
p.logfile = open("/tmp/file", "wb")
```

as a workaround

**Comment by cagney** [comment]
thanks for the workaround
(I cut down my code wrong, the .spawn should be a .spawnu?)

**Comment by takluyver** [comment]
I don't really consider that a workaround - logfile handles need to be opened in a mode compatible with the interface you're using - i.e. `spawn` uses binary logfiles, and `spawnu` uses unicode logfiles.

**Comment by jquast** [comment]
Oh yes, I completely missed the 'spawn' instead of 'spawnu' here. @takluyver is right, if you use spawnu, it should have worked as intended, not a bug.  Thanks !!

**Comment by LuxoftAKutsan** [comment]
I have the same issue with logfile=sys.stdout. What workaround can I use?

**Comment by jquast** [comment]
Try: sys.stdout.buffer
