### ISSUE TITLE
.logfile_send and .logfile_read ignored during .interact()

### ISSUE THREAD

**Issue by cagney** [pexpect/pexpect#190]
Given this code stub:

cat logfile-ignored.py
import pexpect
import sys
p = pexpect.spawn("/bin/bash")
p.logfile_send = open("/tmp/file", "w")
p.logfile_read = p.logfile_send
print("Escape is ^]")
p.interact()

/tmp/file ends up empty.  However, any non-interactive exchanges to get written.

**Comment by jquast** [comment]
use ``p.logfile`` instead of ``p.logfile_send`` or ``p.logfile_read``.

The latter two are for the ``.send*`` and ``.read*`` functions (triggered by ``.expect*``). ``.interact`` only writes to ``p.logfile``. 

Would accept a PR to update the ``interact`` method's docstring to clarify.

**Comment by jquast** [comment]
I will propose to use self._log(data, 'read') and 'write', rather than document the caveat that written data (keystroke input) is not logged.

**Comment by jquast** [comment]
Superseded by #259
