### ISSUE TITLE
recommend .send('')/.expect() before very first .sendcontrol('c') in documentation

### ISSUE THREAD

**Issue by cagney** [pexpect/pexpect#191]
It is easy to get a race between .spawn()ed process setting up its control-C handler and  ascript trying to send a control-C as the first character.  For instance:
```python
import pexpect
import sys
import time
p = pexpect.spawn("virsh console domain")
# examples of how to avoid race
# time.sleep(5) # allow process to start
# p.send('') # has implicit read letting process start?
p.sendcontrol('c')
p.interact()
```

(virsh is chosen as it is a little slow to start) can result in a dead virsh process instead of a control-c being sent to the remote end.

I think the documentation around .sendcontrol('c') should mention this

**Comment by jquast** [comment]
You should typically ``.expect`` something to know that the process has connected, pexpect does not comprehend the process tree in any way.

I'm not sure what's on your remote end to expect, but you might use something like the ``LIBVIRT_DEBUG`` environment variable which might cause ``virsh`` to print something to the effect of "connected", which you could then ``expect`` before sending ^C.

**Comment by jquast** [comment]
``send()`` does not appear to have any kind of implicit read, not how why that would work around the race condition.

**Comment by cagney** [comment]
I guess just calling .send() gives the virsh process enough time.  For virsh, this seems to work:

        # Give the virsh process a chance set up its control-c
        # handler.  Otherwise something like control-c as the first
        # character sent might kill it.
        console.expect("Connected to domain %s\r\n" % self.domain)

As I mentioned, it would be really nice for the documentation, perhaps around .sendcontrol or .sendintr, to give people like me a heads up as to this got-ya :-)

**Comment by jquast** [comment]
I think the implication that you should **expect** something to indicate your program is in the desired state before **sending** control-c or any other character is too elementary.

You may propose a FAQ entry as a pull request if you strongly disagree.
