### ISSUE TITLE
sendline automatically appends some character while sending command

### ISSUE THREAD

**Issue by jsinix** [pexpect/pexpect#194]
When ever i try to go to enable mode on ASA using sendline, it appends it with a character on the lft side. Here is program output in debug mode:

```
Type help or '?' for a list of available commands.
asabox/sec/act>
asabox/sec/act>
asabox/sec/act> enable
enable
Password: abcdefgh
(+) Querying configuration(please be patient)
********************
asabox/sec/act# terminal pager 0
terminal pager 0
asabox/sec/act#

asabox/sec/act# show run
-show run                                       ####### if you see here show starts with -, not sure why ?
                      ^
ERROR: % Invalid input detected at '^' marker.
asabox/sec/act# (+) Grabbing for asabox
exit
(+) Config saved to asabox-RunningConfigBackup-1427647110.TXT

====================

Here is the actual code i am using:

print "(+) Sending SSH Password"
child.sendline(passLocal)
child.sendline("\r")
child.expect('.*>')
child.sendline('enable')
child.expect('.*assword:.*')
child.sendline(enablePassLocal)
print "(+) Querying configuration(please be patient)"
child.expect(".*#")
child.sendline("terminal pager 0")
child.expect(".*#")
child.sendline("\r")
child.expect (".*# ")
child.sendline('show run')
child.expect(".*#", timeout=200)
```

Could you please advise ???
Best Regards

**Comment by jquast** [comment]
could you try ``sendline()`` instead of ``sendline('\r')`` or just ``send('\r')``

**Comment by jsinix** [comment]
Awesome ! Thanks jquast sendline() works

**Comment by jquast** [comment]
Really, Issue resolved ??

Curious. I imagine there is some bug on the distant or transport (like telnet, perhaps) regarding receipt of '\r\r\n' on input being transmuted into receiving a hyphen by the ASA's shell.

Strange and curious, but beyond pexpect's scope.

**Comment by jsinix** [comment]
Ya it was strange and if i change expect statement a little bit, the character changes like - / 0 5 etc. Most probably its not pexpect but it was a bit annoying.

**Comment by jsinix** [comment]
For long ASA runningConfig outputs, pexpect is pretty slow if i use timeout. If i use EOF, the output in debug mode is really fast but it just hangs after displaying the 'show run' command output and timesout:

  subscribe-to-alert-group telemetry periodic daily
 profile configbackup-1
  destination address email jsinix.1337@gmail.com
  destination transport-method email
  subscribe-to-alert-group configuration export full periodic daily 19:00
Cryptochecksum:xxxxxxxxxxxxxxxxxxxxxxxx
: end
asaBox#           (-) Error: Timeout exceeded.


here is the code:

child.expect (".*# ")
child.sendline('show run')
child.expect(pexpect.EOF)
child.expect(".*# ")
print "ABC"


Is there any way to get out of that ?

Best

**Comment by jsinix** [comment]
Looks like speed was a regex issue. The one i was using was too wide. That's fixed.  But another question if you can help with please, the running config is too long(>5000 lines). But pexpect only gives me around 2500-2800 lines and exits out without meeting the expect condition. Is this something i need to set in pexpect's attributes ?

**Comment by takluyver** [comment]
I don't think the volume of output should matter to pexpect, only the time. If it doesn't find a match in a set period of time, it will give up. You can control that by passing `child.expect(..., timeout=60)` (the number is in seconds). `timeout=None` will wait indefinitely.

Also, note that if you're expecting `".# "`, there's a risk that something in those thousands of lines will match. Especially since `expect()` treats its arguments as regexes, so `.` matches any character. If you want to match only the character `.` in that position, use `expect_exact` to match against an exact string.

**Comment by jsinix** [comment]
You are absolutely correct with the second one :) 

I needed to use that matches exactly what i need. Here is what i use now and works. Now this regex is fast and is not truncated in between. Thanks for the response. 

hostname[:-4]+".*./(act|stby)/(pri|sec).*# "

Best
