### ISSUE TITLE
Asyncio coroutine output stops at first occurrence

### ISSUE THREAD

**Issue by detly** [pexpect/pexpect#195]
I've been trying to use the new `asyncio` integration, but it's not working as expected. I can only seem to get the data up to the first occurrence of the expected string.

There are three attachments to demonstrate what's happening:

  * [pexpect_bug_script.py](https://gist.github.com/detly/541280d90788a0ee7992) - the script that produces the output to be received by `pexpect`
  * [pexpect_bug_event.py](https://gist.github.com/detly/490f8f0cd2508ee30a49) - a `pexpect` script using the `events` argument to `run()`
  * [pexpect_bug_async.py](https://gist.github.com/detly/7be411010366f5a67467) - a `pexpect` script using `asyncio` and the `async` argument to `run()`

Don't run the first script (`pexpect_bug_script.py`), just put it in the same directory as the others and run those. `pexpect_bug_event.py` uses the `events` argument to react to occurrences of `\r`, and as expected shows all of the output from `pexpect_bug_script.py`. `pexpect_bug_async.py` uses the `asyncio` integration instead, and only shows the first few control characters. `ctrl+c` will stop either script.

Am I using the `async` argument wrong, or is this a bug?

I'm running this under Python `3.4.0` on Ubuntu 14.04.1 with `pexpect` and `ptyprocess` installed from git.

**Comment by detly** [comment]
Note that `pexpect_bug_script.py` contains control characters, but it doesn't seem related. Replacing those with eg. `****` still demonstrates the problem.

**Comment by jquast** [comment]
Thanks for the thorough report, we'll try to get to it soon.

**Comment by takluyver** [comment]
@detly I think I've figured it out - can you try #198?

I had incorrectly handled the case where the data it needs to match was already read before `expect(..., async=True)` was called.

**Comment by detly** [comment]
Yep, this seems to fix it!

**Comment by takluyver** [comment]
Great. @jquast, I'll give you a little while to look at it before I merge.

**Comment by jquast** [comment]
Already took a look, fine with me -- merge when ready. Thanks!
