### ISSUE TITLE
pexpect.spawnu(...).__str__() crashes

### ISSUE THREAD

**Issue by cagney** [pexpect/pexpect#199]
For instance:

$ cat ~/tmp/pexpect-str.py
#!/usr/bin/env python3
import pexpect
child = pexpect.spawnu("/bin/bash")
print(child)

gives:

$ ~/tmp/pexpect-str.py
Traceback (most recent call last):
  File "/home/cagney/tmp/pexpect-str.py", line 4, in <module>
    print(child)
  File "/usr/lib/python3.4/site-packages/pexpect/__init__.py", line 531, in __str__
    s.append('before (last 100 chars): %r' % (self.before)[-100:],)
TypeError: 'NoneType' object is not subscriptable

$ rpm -q python3-pexpect
python3-pexpect-3.1-3.fc21.noarch

**Comment by jquast** [comment]
Thanks, this was fixed https://github.com/pexpect/pexpect/pull/142
