### ISSUE TITLE
p.eof() returns False after pexpect.EOF raised (async use)

### ISSUE THREAD

**Issue by detly** [pexpect/pexpect#200]
The [`spawn.eof()` docs](https://pexpect.readthedocs.org/en/latest/api/pexpect.html#pexpect.spawn.eof) say:

> This returns `True` if the EOF exception was ever raised.

I created a [simple script](https://gist.github.com/detly/8f936259753e4a23b50c) that seems to break this when `async=True` is used: the EOF exception is caught, but it looks like `p.flag_eof` is still `False`.

The only place I could find in the code that raises EOF *without* first setting `flag_eof = True` is in [`expect.py:49`](https://github.com/pexpect/pexpect/blob/master/pexpect/expect.py#L49). I'll see if tweaking this fixes the problem, but I'm not 100% sure it's the right solution.

**Comment by takluyver** [comment]
Adding it there would probably work, though it will be set twice if EOF occurs during a non-async expect, because expect_loop catches EOF and calls that code to re-raise it.

I think adding it here in `PatternWaiter.eof_received()` might be neater: https://github.com/pexpect/pexpect/blob/master/pexpect/async.py#L60

**Comment by detly** [comment]
There also seems to be a problem where the message itself is lost. I can't find the error string in `p.before`, or anywhere else. Is it possible that `stderr` data is just discarded?

**Comment by takluyver** [comment]
It can't be selectively discarding stderr, because when you use a pty, stdout and stderr are merged at the OS level - see my diagrams here: http://ptyprocess.readthedocs.org/en/latest/#what-is-a-pty

However, the async integration might be losing some data it gets just before EOF. I think you're the first person to really use the async functionality, and as you've noticed, there are still some kinks to work out.

**Comment by detly** [comment]
Re. asyncio losing data before EOF — I was wondering about this myself, but
couldn't get very far debugging it. I'll keep looking.

But yeah, I saw the new async feature and thought I'd give it a workout for
a hobby project. Nothing mission critical, so any bugs resolved at this
point are purely a bonus for me :)

**Comment by detly** [comment]
Oh, I just noticed that `eof_received()` is not being called directly, but actually by the `OSError` handler in  `connection_lost()`. The error message is definitely getting received by `data_received()` before this point too, and is passed to `new_data()` in the `expecter`. So for a while, `self.expecter.spawn.before` does actually contain the error string. It looks like at some point after this it gets clobbered though.

**Comment by takluyver** [comment]
Great, that's the perfect scenario to have someone using this and discovering the bugs that unit tests haven't caught.

I'm flying to Montreal tomorrow for PyCon, so I may not have much time to dig into this, but I'll still be contactable. Good luck!

**Comment by detly** [comment]
I think I'm getting closer to the problem, so expect a pull request soonish. I have the long weekend to work on it. Have fun at PyCon!

**Comment by detly** [comment]
Okay, it looks like `spawn.before` gets clobbered in [`Expecter.eof()`](https://github.com/pexpect/pexpect/blob/master/pexpect/expect.py#L35). I'm not sure, but the solution might be to call `Expecter.new_data()` with an empty string in `PatternWaiter.eof_received()`.

**Comment by jquast** [comment]
I'm having failing builds on OSX that I think may be related, unfortunately PR https://github.com/pexpect/pexpect/pull/202 doesn't seem to be helping. I've been at it for a while, I'm very lost.

```
(xxx)osx:pexpect teamcity$ git merge --no-ff detly/eof-fix
Auto-merging pexpect/async.py
Merge made by the 'recursive' strategy.
 pexpect/async.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
(xxx)osx:pexpect teamcity$ py.test -vvv tests/test_async.py  -k test_expect_exact
============================================ test session starts =============================================
platform darwin -- Python 3.4.3 -- py-1.4.26 -- pytest-2.7.0 -- /Users/teamcity/.virtualenvs/xxx/bin/python3.4
rootdir: /opt/TeamCity/buildAgent/work/210ae16cc3f30c30/pexpect, inifile: setup.cfg
plugins: capturelog, cov
collected 4 items

tests/test_async.py::AsyncTests::test_expect_exact FAILED

================================================== FAILURES ==================================================
________________________________________ AsyncTests.test_expect_exact ________________________________________

self = <tests.test_async.AsyncTests testMethod=test_expect_exact>

    def test_expect_exact(self):
        p = pexpect.spawn('%s list100.py' % sys.executable)
        assert run(p.expect_exact(b'5', async=True)) == 0
        assert run(p.expect_exact(['wpeok', b'11'], async=True)) == 1
>       assert run(p.expect_exact([b'foo', pexpect.EOF], async=True)) == 1

tests/test_async.py:51:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_async.py:13: in run
    return asyncio.get_event_loop().run_until_complete(coro)
/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py:316: in run_until_complete
    return future.result()
/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py:275: in result
    raise self._exception
/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py:238: in _step
    result = next(coro)
pexpect/async.py:23: in expect_async
    return expecter.timeout(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pexpect.expect.Expecter object at 0x10a60f908>, err = TimeoutError()

    def timeout(self, err=None):
        spawn = self.spawn
        from . import TIMEOUT

        spawn.before = spawn.buffer
        spawn.after = TIMEOUT
        index = self.searcher.timeout_index
        if index >= 0:
            spawn.match = TIMEOUT
            spawn.match_index = index
            return index
        else:
            spawn.match = None
            spawn.match_index = None
            msg = str(spawn)
            if err is not None:
                msg = str(err) + '\n' + msg
>           raise TIMEOUT(msg)
E           pexpect.exceptions.TIMEOUT:
E           <pexpect.pty_spawn.spawn object at 0x10a620ac8>
E           command: /Users/teamcity/.virtualenvs/xxx/bin/python3.4
E           args: ['/Users/teamcity/.virtualenvs/xxx/bin/python3.4', 'list100.py']
E           searcher: None
E           buffer (last 100 chars): b'5, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]\r\n'
E           before (last 100 chars): b'5, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]\r\n'
E           after: <class 'pexpect.exceptions.TIMEOUT'>
E           match: None
E           match_index: None
E           exitstatus: 0
E           flag_eof: False
E           pid: 7830
E           child_fd: -1
E           closed: False
E           timeout: 30
E           delimiter: <class 'pexpect.exceptions.EOF'>
E           logfile: None
E           logfile_read: None
E           logfile_send: None
E           maxread: 2000
E           ignorecase: False
E           searchwindowsize: None
E           delaybeforesend: 0.05
E           delayafterclose: 0.1
E           delayafterterminate: 0.1

pexpect/expect.py:68: TIMEOUT
------------------------------------------------ Captured log ------------------------------------------------
selector_events.py          53 DEBUG    Using selector: KqueueSelector
-------------------------------------------- Captured stdout call --------------------------------------------

 tests.test_async.AsyncTests.test_expect_exact
================================ 3 tests deselected by '-ktest_expect_exact' =================================
================================== 1 failed, 3 deselected in 30.27 seconds ===================================
```

**Comment by takluyver** [comment]
@detly - can you provide a code snippet showing the data loss before EOF? Preferably open a new issue. That `self.before = self.buffer` in Expecter.eof() is intentional, but if Expecter.eof() gets called twice, it would clobber self.before.

WRT `eof_received`, it can be called by the asyncio internals, but it isn't in all situations. Actually, that could be the issue - if it gets called by asyncio, and then again by `connection_lost`. Try adding a check for `self.expecter.spawn.flag_eof` in `connection_lost` (i.e. if it's already True, don't call `eof_received()` again.

@jquast that looks like the opposite problem - `Expecter.eof()` is not getting called at all. I know how EOFs are reported differs by platform, maybe we're not catching the EOF on your platform. Stick something in `connection_lost()` and see if that gets called well before the 30 second timeout.

**Comment by detly** [comment]
@takluyver See issue 204 `:)`

**Comment by takluyver** [comment]
Ah, thanks. I was at PyCon, and apparently I'm still catching up on things that I didn't pay proper attention to at that time. I think I can see the issue, I'll try to make a fix.
