### ISSUE TITLE
 searchwindowsize+freshlen edge case

### ISSUE THREAD

**Issue by cagney** [pexpect/pexpect#203]
I'm reading expect_loop(self, searcher, timeout=-1, searchwindowsize=-1) and suspect there's a nasty edge case when the pattern/string crosses the boundary between old and new data.
(I'm also somewhat at a loss as to how to come up with a test case to demonstrate this)

To set up an extreme example:

  regex = "1234567890"
  buffer = "xxxxx123456789"
  searchwindowsize = 10

and read_nonblocking returns "0y" so:

  buffer = "xxxxx1234567890y"
  freshlen = 2

Then both searcher_string.search() and searcher_re.search() will look at "234567890y".  They need to look at freshlen+searchwindowsize, that is "x1234567890y".

Even when searchwindowsize isn't small (say 100 bytes), then a large read will also have issues.

BTW, for searcher_string I suspect that the best fix might be to ignore searchwindowsize and always use:
     offset = -(freshlen + len(s))

**Comment by jquast** [comment]
You may be right, I remember having similar thoughts when I last reviewed that section.

If you could turn your extreme example into a valid (presumably, failing) TestCase against the github master branch, you'd save us the first (and hardest) step of fixing it ala TDD. If not, no problem, I'll get around to it

**Comment by jquast** [comment]
Not marking as bug unless it can be reproduced. Bytes are read 1 byte at a time, expensive and slow by default, but conservative in your suspicion.

**Comment by cagney** [comment]
Burried in my logs I've noticed that given the very large read (mixed in with lots of other reads):

DEBUG a.shell east 2:40.056/46.008: read <<"rting D-Bus System Message Bus...\r\r\n         Starting /etc/rc.d/rc.local Compatibility...\r\r\n         Starting Permit User Sessions...\r\r\n[\x1b[32m  OK  \x1b[0m] Started Permit User Sessions.\r\r\n[\x1b[32m  OK  \x1b[0m] Found device /dev/ttyS0.\r\r\n[\x1b[32m  OK  \x1b[0m] Started Login Service.\r\r\n[    4.995073] FS-Cache: Loaded\r\n[    5.007563] 9p: Installing v9fs 9p2000 file system support\r\n[    5.008732] FS-Cache: Netfs '9p' registered for caching\r\n[    5.064651] random: nonblocking pool is initialized\r\n[    5.092857] ppdev: user-space parallel port driver\r\n\x1b%G[    5.135218] [drm] Initialized drm 1.1.0 20060810\r\n[    5.242658] [drm:qxl_pci_probe [qxl]] *ERROR* qxl too old, doesn't support client_monitors_config, use xf86-video-qxl in user mode\r\n[    5.242658] qxl: probe of 0000:00:02.0 failed with error -22\r\n">>>
DEBUG a.shell east 2:43.035/48.987: read <<'[\x1b[32m  OK  \x1b[0m] Started LSB: Bring up/down networking.\r\r'>>>

the call:

    expect("Started Login Service", searchwindowsize=len("Started Login Service")*4)

timing out.  This would suggest that my comment  "Even when searchwindowsize isn't small (say 100 bytes), then a large read will also have issues." is no longer theoretical :-(
