### ISSUE TITLE
Wait() should return normally if the child process has already terminated

### ISSUE THREAD

**Issue by reynir** [pexpect/pexpect#205]
This bug is cause by pexpect/ptyprocess#13.

An exception will be thrown if you try to call `wait()` on an already terminated child. This is easily demonstrable with short-lived programs such as /bin/true, but can also happen in other situations. I personally discovered this behavior using a program to encrypt files - it would finish encrypting the file and terminate before the parent python script could start `wait()`ing.

This behavior is unexpected. `subprocess.Popen.wait()` returns normally if the process has already terminated, although the documentation doesn't mention this. Returning normally is the behavior in other languages (e.g. [java](http://docs.oracle.com/javase/7/docs/api/java/lang/Process.html#waitFor%28%29). Furthermore, it is the behavior for `wait` in `expect(1)`.

I think this makes the only way to safely wait for a process to finish is to call `wait()` and catch the exception as described in this [comment](http://www.heikkitoivonen.net/blog/2009/01/28/pexpect-and-inconsistent-exit-status/#comment-6905). This is however brittle since it inspects the string contents of the exception(!) The whole blog post and comment section is relevant to the issue. I *think* the suggested solution (expecting on EOF) isn't adequate either since the child could close stdin/stdout/stderr and still run.

In the ptyprocess @takluyver suggests not changing this behavior in pexpect for backwards compatibility. I think we should consider if there
1) legitimate use cases for this behavior
2) examples where this behavior is used and isn't a workaround.
Note that changing this behavior will *not* break workarounds such as the one in the blog post comment linked earlier.

**Comment by takluyver** [comment]
My stance on pexpect is that it's been around so long with no changes that people are probably relying on it in all kinds of ways and places that I can't find. So I'm very wary of any change to its public API. I'm making some API changes to 4.0, but even so, I'm not intending that as a chance to arbitrarily change other APIs.

I think there is room for a project to offer the same functionality as Pexpect with a more carefully thought out API, but I think that should be a new project.

**Comment by takluyver** [comment]
Though, on some more reflection, I think I could live with it if we decided to change this - it's hard to see how someone could be relying on it raising an exception.

**Comment by jquast** [comment]
Closed by #211
