### ISSUE TITLE
Build Infrastructure: Allow Travis-CI builds to comprehend ptyprocess relationship

### ISSUE THREAD

**Issue by jquast** [pexpect/pexpect#210]
TeamCity comprehends the relation of pexpect and ptyprocess, and if two branches are made of the same name, they are tested together.  Travis-CI however does not, which would require publishing ptyprocess to the public to test a pairing branch in pexpect.

Travis-CI supports any kind of linux command, so we should be able to solve this with a little bit of shell scripting and a series of git(1) commands.

**Comment by takluyver** [comment]
I think it's valuable to have some reminder that this doesn't work with the released version of ptyprocess. I hope that, going forwards, the projects won't be so tightly coupled that they regularly need matching changes. Of course there are some teething issues as we separate them out.
