### ISSUE TITLE
performance problems due to time.sleep(0.0001) in expect_loop

### ISSUE THREAD

**Issue by billpage** [pexpect/pexpect#215]
Is there a good reason to keep this:
https://github.com/pexpect/pexpect/blob/3.x/pexpect/__init__.py#L1540
Is there really an issue with "busy waiting" given the way ''read_nonblocking' is written?
See discussion at: http://trac.sagemath.org/ticket/10295#comment:50

**Comment by jquast** [comment]
We need to periodically check os.waitpid for child process termination, which is done in each loop.

**Comment by billpage** [comment]
Would ''time.sleep(0)'' be sufficient? 
http://stackoverflow.com/questions/7273474/behavior-of-pythons-time-sleep0-under-linux-does-it-cause-a-context-switch

**Comment by jquast** [comment]
Regarding the sage math conversation, I would be a proponent of removing it entirely, if possible.

We have a large suite of tests, if they pass (a PR will trigger an OS X, Linux, FreeBSD, and Solaris build farm)., it can be removed.  If not, we need to figure out why noah felt he needed to add it and possibly document.

You would need to also install a pairing ‘master’ branch of https://github.com/pexpect/ptyprocess/ <https://github.com/pexpect/ptyprocess/> to test locally

**Comment by jquast** [comment]
``sleep(0)`` may be sufficient, if it can be proven it "yields" a python thread's control on so all platforms? what a crummy hack, could use a comment above it describing why it exists!

**Comment by nexttime** [comment]
> We need to periodically check os.waitpid for child process termination, which is done in each loop.

Well, that's rather orthogonal to the `sleep()` call.

Also, `isalive()` (which calls `waitpid()`) is called unconditionally each time **before** an attempt to read is made;  IMHO that should only be done after a failed read / timed-out `select()`.

**Comment by jquast** [comment]
You're welcome to try any such changes, the test results of the build servers will help support or deny your suggestions as a pull request.

**Comment by billpage** [comment]
This pull request
https://github.com/pexpect/pexpect/pull/216
gave mixed results. I do not understand how to interpret the ca/teamcity result.

**Comment by billpage** [comment]
@jquast wrote:
"You would need to also install a pairing ‘master’ branch of https://github.com/pexpect/ptyprocess/ <https://github.com/pexpect/ptyprocess/> to test locally"

Could you explain this in a bit more detail or point me to some docs?  The README in the /tests directory seems out of date.  Something is missing from the /tools directory. Apparently I can no  longer test pexpect that way?

**Comment by jquast** [comment]
Please try a PR against master branch (upcoming 4.x release).

Sorry for the delay in responding, the "3.x" branch doesn't support the testing framework.

**Comment by billpage** [comment]
https://travis-ci.org/pexpect/pexpect/builds/62276250
Any idea about what the failure with Python 3.3 means?
https://travis-ci.org/pexpect/pexpect/jobs/62276252#L442

**Comment by billpage** [comment]
How close is the upcoming 4.x release?  Should the SageMath project be targetting 4.x instead of 3.x?

**Comment by jquast** [comment]
the winsize timeout failure is new, i haven't seen it before. It also happens on Linux, FreeBSD, 

There is one blocking bug affecting python3.4.3 that prevents my OK for a pexpect 4.0 release, #213. These are the other errors reported by teamcity for: expect_exact, test_expect_wait

**Comment by billpage** [comment]
Perhaps I should try time.sleep(0).  If I make another commit under this same pull request will it repeat the tests?

**Comment by jquast** [comment]
yes

**Comment by billpage** [comment]
It failed again with time.sleep(0).  I am having a hard time interpreting the output but it seems strange that it affects only Python 3.3.  For now I am kind of stuck.

**Comment by jquast** [comment]
Closing in favor of keeping #217 open as WIP
