### ISSUE TITLE
run directory

### ISSUE THREAD

**Issue by egorf** [pexpect/pexpect#218]
Hi!
This is more of a question, than an issue. I am using pexpect to control a cli program, that is sensitive to the directory it has been launched in. From my tests I assume that the default dir for spawning children is the one you run the python script from. Is there a way to change this?
Thank you

**Comment by takluyver** [comment]
Yep, when you create a `spawn()`, you can pass `cwd='/heres/some/path'`.

**Comment by takluyver** [comment]
Docs: http://pexpect.readthedocs.org/en/latest/api/pexpect.html#spawn-class

**Comment by egorf** [comment]
Thanks! The docs don't explain this actually
