### ISSUE TITLE
pip install pexpect >3.3?

### ISSUE THREAD

**Issue by erikb85** [pexpect/pexpect#219]
Hi guys,

since I started using pexpect there always was 3.3. The [documented history](http://pexpect.readthedocs.org/en/latest/history.html) states there are newer versions as well. But they are not on pypi. Was that forgotten by mistake, or on purpose? What is the preferred way to install pexpect > 3.3? I'd be happy if I could continue to track that requirement via [setup.py](https://github.com/DFE/MONK/blob/0bb8b72be7bde74132cf60154276d0c2d0f80949/setup.py#L47).

And of course I'd like to use the cool features that come with the work you've put in adding asyncio support.

**Comment by takluyver** [comment]
Hi Erik. That's just because we document new versions before they're released. 3.3 is the latest version that has actually been released. We really need to get round to making a 4.0 release - there's just a few more things to sort out.

**Comment by erikb85** [comment]
Hey Thomas,

okay, I might have a few free hours this weekend. Is there some way I can help? E.g. by doing something about #133?

**Comment by takluyver** [comment]
Thanks! I've just released ptyprocess 0.5, which was one of the hold ups. I think #182 is the next big thing that needs to be dealt with - I'll try to find some time this weekend to dig into it.
