### ISSUE TITLE
logfile in replwrapper?

### ISSUE THREAD

**Issue by endrebak** [pexpect/pexpect#224]
Is it possible to create a logfile for the replwrapper?

I have an idea for a repl logfile feature:

It would be nice if every command used in the repl was written to the logfile. Other log entries can be there too, but they should start with a comment symbol.

The log files would then look something like this (for R):

```R
print(1 + 1)
# log message: Blah blah blah spoons blah blah blah swordfish blah blah blah
3 + 5
# another log message
...
```

This way, the scripts run in the wrapped REPL would be easy to debug afterwards, as the environment could easily be recreated by running the logfile.

**Comment by jquast** [comment]
A fine idea. I suggest this could be accommodated by #133 -- once the standard logging module is in use, we are free to decorate new logging data from various portions of pexpect without introducing new ``logfile=``, ``logfile_read=``, and ``logfile_send`` arguments to replwrap.
