### ISSUE TITLE
There is a way ti clear the buffer after a sendline?

### ISSUE THREAD

**Issue by marcosps** [pexpect/pexpect#227]
I'm trying to avoid a banner message of ubuntu server when doing a ssh connection...

So, I want to do something like this:

expect('password:')
sendline('my_password')

clear_buffer()

sendline('\n')
expect("user@ubuntu")

There is a way to clear the buffer of the data that was read from child? I saw that SpawnBase class has a buffer, after, before and match, but changing them doesn't change the expect behavior.

Thanks!

**Comment by marcosps** [comment]
A possible workaround I found is to read the spawned child fd and do an os.read before calling expect again. This kind of solved my problem, but in a tricky way :)

**Comment by takluyver** [comment]
I think the buffer should be cleared when expect finds a match (its contents are moved to `.before`).

**Comment by marcosps** [comment]
Hi @takluyver, yes, but there is a way to clear it without matching nothing?

**Comment by ebos** [comment]
There have been numerous times when there is garbage from the previous command in the buffer and it messes up the script. There are times when i need to pull the values out of the spawn_id.buffer or the spawn_id.after and do additional regex pattern matching on them to get values. I need to guarantee those values are clear and flushing the buffer would be helpful in guaranteeing I don't get garbage.

**Comment by marcosps** [comment]
Closing as I resolved in some other way. Thanks for the help!

**Comment by tony-teknique** [comment]
Clearing `buffer` buffer (a variable of SpawnBase) rather than `before` or `after` works for me.

**Comment by Abhishek627** [comment]
Hi tony-teknique,

Are you doing pexpect_obj._set_buffer('') for this ?

**Comment by tony-teknique** [comment]
@Abhishek627 I did this. `self.pexpect_ser.buffer = ""`

**Comment by lokesh8421** [comment]
@marcosps , I am facing the same issue where child.before contents are not clearing, wheneve I ran the child.sendline("commands"),  I observe the previous commands are appending to the child.before attribute.
You have mentioned that issue is resolved using  "spawned child fd and do an os.read" , can you share code snipped how you have over come the issue.

**Comment by marcosps** [comment]
> @marcosps , I am facing the same issue where child.before contents are not clearing, wheneve I ran the child.sendline("commands"), I observe the previous commands are appending to the child.before attribute.
> You have mentioned that issue is resolved using "spawned child fd and do an os.read" , can you share code snipped how you have over come the issue.

@lokesh8421 after a spawn object is instantiated, there is a fd created to be used as a communication pipe between the spawned process and the process "control process". IIRC, you can os.read() from child_fd[1], and it would clean the buffer for subsequent calls. I don't have this code anymore, and to be honest, I don't remember exactly how I did it...

Or, you can clean the before attribute by setting None to it?

Let me know if this helps :)

[1]: https://github.com/pexpect/pexpect/blob/c694853403716ace2754cc1e039bf35ecdc17db6/pexpect/spawnbase.py#L51

**Comment by pbartyik** [comment]
leaving this here for future me, and others who might face the same issue :)
child.read_nonblocking(1000000000, timeout = 1)

**Comment by jsthomason** [comment]
@pbartyik  ... thank you very much... your one liner worked well, had to wrap in a try catch block, but you certainly put me on the right path...
Here's the final definition...
`
def clear_buffer(self, exp):
    buff = None
    try:
        buff = exp.read_nonblocking(16384, timeout = 1)
        print(f'clear_buffer(): read_nonblocking: ***{buff}***')
    except pexpect.exceptions.TIMEOUT as toe:
        print(f'clear_buffer(): TIMEOUT: {str(toe)}, buff: ***{buff}***')
`
Thank you much!
John Thomason

**Comment by jeffatoptics** [comment]
this is working in my code:
```
child.expect_exact(child.buffer)
```
