### ISSUE TITLE
pxssh does not synchronize prompt with non-bourne remote shells

### ISSUE THREAD

**Issue by ArockiaAntony** [pexpect/pexpect#228]
Hi,

I am using Pxssh to login to firewall which has a specific prompt. It gives the following error.

 ^\r\nERROR: % Invalid input detected at '^' marker.\r\n\rwebvpn> PS1='[PEXPECT]\\$ '\r\n         ^\r\nERROR: % Invalid input detected at '^' marker.\r\n\rwebvpn> set prompt='[PEXPECT]\\$ '\r\n         ^\r\nERROR: % Invalid input detected at '^' marker.\r\n\rwebvpn> ", expected: '\\[PEXPECT\\][\\$\\#] ').

It expects #,$ in the prompt. How can I change the prompt to webvpn> ?

**Comment by jquast** [comment]
pxssh depends on a bourne-like shell on the distant end.

This is so that pexpect can distinguish command output from the banner, command prompt, etc.
