### ISSUE TITLE
Two ptys for twice the fun!

### ISSUE THREAD

**Issue by JohnLonginotto** [pexpect/pexpect#230]
Because both stdout and stderr are sent to the same pty, they get mixed up and theres no way to separate them and thus ultimately send them to different places. And arbitrary number of ptys to accommodate an arbitrary number of file descriptors would sort this out :)

These guys are currently discussing how to do something pexpect is perfectly suited to solve, if only it didnt mix stdout and stderr together: 
http://stackoverflow.com/questions/31926470/run-command-and-get-its-stdout-stderr-separately-in-near-real-time-like-in-a-te?noredirect=1#comment51816585_31926470

**Comment by takluyver** [comment]
I don't see pexpect doing that, sorry. A process has a controlling pty, not just a pty hooked to a file descriptor, and I don't know of any precedent for connecting one process to two ptys. If it works for their use case, that's great, but I'm not interested in supporting it in pexpect at the moment.
