### ISSUE TITLE
sendline in uboot

### ISSUE THREAD

**Issue by ljoli** [pexpect/pexpect#231]
Hi everybody,

I want to control a board with an interactive script.
My aim is to manage the uboot ( bootloader ) of an specific board.
so, I do a code like this : 

```
import pexpect 
import pdb; pdb.set_trace()

child = pexpect.spawn ('picocom  /dev/ttyUSB0 -b 115200')

# control uboot of board
child.expect ('Hit any key to stop autoboot*')
child.sendline ('\r\n')
child.expect ('U-Boot*')
child.sendline ('printenv')
child.expect ('U-Boot >')
print ('before set mmc')
child.sendline ('setenv mmcdev 1')
child.expect ('U-Boot >')
child.sendline ('setenv mmcroot /dev/mmcblk1p1 rw ')
child.expect ('U-Boot >')
child.sendline ('saveenv')
child.expect ('U-Boot >')
child.sendline ('reset')
# check boot 
child.expect ('Asterisk*',timeout=120)
print('Asterisk OK')
child.expect (' login:')
print('Login')
child.sendline ('root')
child.expect ('Password:')
child.sendline ('xxx')
child.expect ('root@smop:*')
child.sendline ('ls /home/smop-admin')
child.expect ('root@toto:*')
print child.before  
child.interact()                                                        
````

But when I start my script, I have no the good answer :

```
`--> python ./test_pexpect.py
> /home/xxx/script_auto/test_pexpect.py(16)<module>()
-> child = pexpect.spawn ('picocom  /dev/ttyUSB0 -b 115200')
(Pdb) c
before set mmc
 setenv mmcdev 1

 setenv mmcroot /
U-Boot > saveenv
Saving Environment to SPI Flash...
SF: Detected SST25VF032B with page size 4 KiB, total 4 MiB
Erasing SPI flash...Writing to SPI flash...done
U-Boot > reset
resetting ...

U-Boot 2013.04 QMX6Rx20 pn016102-05003-ge9ffe2d (Jul 23 2014 - 09:23:33)

CPU:   Freescale i.MX6Q rev1.5 at 792 MHz
CPU:   Temperature 39 C, calibration data: 0x5874f169
Reset cause: WDOG
```

So, It does not do a good sendline with => setenv mmcroot /
Why pexpect stop when it see a "/" ?

**Comment by ljoli** [comment]
Ok,

I do some test and I see why my command ( child.sendline ('setenv mmcroot /dev/mmcblk1p1 rw ') don't work.

I try with : 
```
child.sendline ('setenv d /dev/mmcblk1p1')
```
And thath give : 
```
setenv d /dev/mm
```

How can I have a string sendline more longer ?

**Comment by jquast** [comment]
your problem is likely in transport (picocom). It must have a limited input buffer. Try sending your text slower. What if you use picocom by hand, and type at ~1,000wpm? (hint, copy & paste your commands to achieve such speeds)

**Comment by jquast** [comment]
also suggest to enable -f hardware flow control for picocom if your serial line is fully wired for it. this is precisely what flow control is meant to solve, if you are without it, then you may have such difficulties. the distant end (uboot) seems to expect any connecting client to be able to communicate RTS/CTS flow control.

**Comment by ljoli** [comment]
Hello,
sorry for my late answer and thanks to Jquast for your answer.!!

I found one solution for send a big line. 

I use writelines instead of sendline : 

   child = pexpect.spawn ('picocom  /dev/ttyUSB0 -b 115200')
 # go to uboot
    child.expect ('Hit any key to stop autoboot*')
    child.sendline ('\r\n')
    child.expect ('U-Boot*')
    child.sendline ('printenv')
    child.expect ('U-Boot*')
    child.sendline ('setenv mmcdev 1')
    child.expect ('U-Boot*')
 # child.sendline ('setenv mmcroot /d')
    child.writelines ('setenv mmcroot /dev/mmcblk1p1 rootwait rw \n')
    child.expect ('U-Boot >')
    child.sendline ('saveenv')
    child.expect ('U-Boot >')
    child.sendline ('reset')
    child.interact()           


And that is it works !!

**Comment by jquast** [comment]
Well, its still a timing issue in your transport as I suspect. All ``child.writelines`` does is:

```
        for s in sequence:
            self.write(s)
```

Artificially ensuring each byte is written one at a time. Your problem is still in transport.
