### ISSUE TITLE
promt bussy / dissapear ?

### ISSUE THREAD

**Issue by juanremi** [pexpect/pexpect#232]
Hi, i use pexpect to run telegram-cli 1.3.3

but i have a problem, when i run 4 or more pexpect paralell, each pexpect is expecting a "string" or "> ", but the promt dissapear and not catch the pexpect response right, is like if the promt freeze, because the pexpect not catch correctly the answer and i cant continue with other operations (insert on db, etc..)

how can i avoit the "promt freeze" and catch correctly the answer for each pexpect process.

exists a limit to run paralell pexpect process at the same time?

**Comment by jquast** [comment]
Limit is #47 probably not your problem.

> but the promt dissapear and not catch the pexpect response right

if the prompt is not emitted by the child process (telegram-cli, presumably), this is not something that pexpect would not cause. It should be reproducible without pexpect by opening 4 simultaneous terminal windows and pasting in a series of commands.

If you can reproduce the issue with something simple, such as cat(1) or something that can be created as a python program, then please produce a failing test case that demonstrates an issue where pexpect is at fault for any freezing prompt issues.
