### ISSUE TITLE
CJK / wide East Asian characters don't render in ANSI terminal

### ISSUE THREAD

**Issue by ericpruitt** [pexpect/pexpect#233]
Writing Japanese characters to the pexpect.ANSI terminal results in nothing being drawn on the virtual screen:

    ~$ python
    Python 3.4.2 (default, Oct  8 2014, 10:45:20)
    [GCC 4.9.1] on linux
    Type "help", "copyright", "credits" or "license" for more information
    >>> import pexpect.ANSI
    >>> terminal = pexpect.ANSI.ANSI(2, 40)
    >>> terminal.write("Wikipedia: メインページ\n\rコマドリ (Bird)")
    >>> print(*terminal.get_region(1, 1, 2, 40), sep="\n")
    Wikipedia:
     (Bird)
    >>>

**Comment by takluyver** [comment]
I'm actually inclined to deprecate the terminal emulation stuff in Pexpect - it's orthogonal to what the main parts of Pexpect do, and there are more actively developed terminal emulators out there, like [pyte](https://pypi.python.org/pypi/pyte).

**Comment by jquast** [comment]
second that!

**Comment by jquast** [comment]
@ericpruitt recommend https://github.com/jquast/wcwidth if you are concerned about the printable width of wide characters.
