### ISSUE TITLE
Trouble with sftp with pexpect

### ISSUE THREAD

**Issue by jaschil2** [pexpect/pexpect#234]
I am currently trying to use pexpect to transfer files. It usually works fine, but recently it has been causing issues by not transferring entire files. It either truncates the file transfer or the script moves on before it is done.

My code is as follows:

```python
job_id = str(job_record['control']['id'])
self.px_ssh.sendline('cd ' + self.remotePath + job_id)
self.px_ssh.prompt()
self.px_ssh.sendline('ls')
self.px_ssh.prompt()
remote_files = self.px_ssh.before.decode('utf-8')
for cop in outfiles:
  if cop in remote_files:
    print('Transferring file _from_ remote cluster:   ' + cop)
    self.px_ftp.sendline('get ' + self.remotePath + job_id + '/' + cop + ' ' + os.getcwd())
    self.px_ftp.expect('sftp>', timeout=None)
```

And the logfile:

```
get path/QMCDB/Elemental/As/As_QMC_2x2x2/prop.in.o    path/Documents/Research/QMCDB/Runs/Elemental/As/As_QMC_2x2x2
Connected to taub.campuscluster.illinois.edu.
sftp> get path/QMCDB/Elemental/As/As_QMC_2x2x2/prop.in.o path/Documents/Research/QMCDB/Runs/Elemental/As/As_QMC_2x2x2
Fetching path/QMCDB/Elemental/As/As_QMC_2x2x2/prop.in.o to path/Documents/Research/QMCDB/Runs/Elemental/As/As_QMC_2x2x2/prop.in.o

path/QMCDB/Elemental/As/As_   0%    0     0.0KB/s   --:-- ETA
path/QMCDB/Elemental/As/As_   0%   11MB  11.1MB/s   02:32 ETA
path/QMCDB/Elemental/As/As_   1%   22MB  11.1MB/s   02:31 ETA
```

It can be seen that it just moves on after a short time. I am not sure why it does this. Do you have any idea how to ensure the whole file is transferred before the rest of my code progresses?

**Comment by takluyver** [comment]
Has something else in your code already called `expect()` to find the `sftp>` prompt? You should expect the prompt and then send the command. Doing it the other way round, it will send the command, then read as far as the prompt and immediately continue to the next file.

**Comment by jaschil2** [comment]
I'm not sure why the order would matter. Usually this problem happens after a couple of sftp calls already so a prompt call would have already been called beforehand. Regardless, I switched the order of all sftp calls to expect the prompt first.

New code:

    for cop in outfiles:
      if cop in remote_files:
        print('Transferring file _from_ remote cluster:   ' + cop)
        self.px_ftp.expect('sftp>', timeout=None)
        self.px_ftp.sendline('get ' + self.remotePath + job_id + '/' + cop + ' ' + os.getcwd())

New log:

    Connected to taub.campuscluster.illinois.edu.
    sftp> get /projects/erg/jaschil2/QMCDB/Elemental/As/As_QMC_Test/prop.in.o /Users/joshuaSchiller/Documents/Research/QMCDB/Runs/Elemental/As/As_QMC_Test
    get /projects/erg/jaschil2/QMCDB/Elemental/As/As_QMC_Test/prop.in.o /Users/joshuaSchiller/Documents/Research/QMCDB/Runs/Elemental/As/As_QMC_Test
    Fetching /projects/erg/jaschil2/QMCDB/Elemental/As/As_QMC_Test/prop.in.o to /Users/joshuaSchiller/Documents/Research/QMCDB/Runs/Elemental/As/As_QMC_Test/prop.in.o

    /projects/erg/jaschil2/QMCDB/Elemental/As/As_   0%    0     0.0KB/s   --:-- ETA
    /projects/erg/jaschil2/QMCDB/Elemental/As/As_   0% 5120KB   5.0MB/s   05:41 ETA
    /projects/erg/jaschil2/QMCDB/Elemental/As/As_   0%   17MB   5.7MB/s   04:59 ETA
    /projects/erg/jaschil2/QMCDB/Elemental/As/As_   1%   33MB   6.8MB/s   04:07 ETA


The problem still persists.

**Comment by jquast** [comment]
@jaschil2 is the 4th file also the last file of your list (``remote_files``)?

In such case, the ``for loop`` you have shared does not have a final ``self.px_ftp.expect('sftp>', timeout=None)``. Your check for sftp> should be only once, before the loop (loop "priming" section), then each "get" sendline should be followed by an expect to sftp>.

**Comment by jaschil2** [comment]
Right I think I may have fixed it that way. I added an extra expect command at the very end, outside the loop.

**Comment by pghole** [comment]
@jaschil2 can you pls. provide the code which worked for you ? I am using, normal spwan command for sftp. Are you using some other ? Also, for me I am not sure how to capture the errors, if any while uploading the file, as even after the error, "sftp>" prompt comes and get through my p.expect('sftp>'). How to check for errors while uploading file. Can you pls. guide ?

`
p = spawn('XXXXXXXX')
passwd = 'XXXXXXXXx'
out=p.expect('(?i)password:')
p.sendline(passwd)
x = p.expect(['Permission denied', 'sftp>'])
if x == 1:
   p.sendline('put ' + 'myfile')
   p.expect('sftp>')  
   print("upload success")
`
