### ISSUE TITLE
'\r' is added when sendline longer than ~60 characters, how to fix?

### ISSUE THREAD

**Issue by mbanders** [pexpect/pexpect#238]
I use pexpect to ssh to machines and type some commands.  It works great except the output is a bit garbled when I `sendline()` a command longer than about 60 characters.  Example code:
```python
s = pexpect.spawn('ssh ...')
s.logfile_read = sys.stdout
s.sendline('echo "Testing, testing, one two three four five six seven eight nine ten"')
s.expect("tester@vm.*# ")
print('\n\nBefore="%s"' % repr(s.before))
```

The resulting output is below. Notice the command is wrapped on itself, and you can see the ' \r' is shown when printing repr(s.before):
```
ht nine ten"g, testing, one two three four five six seven eig 
Testing, testing, one two three four five six seven eight nine ten
tester@vm07:~# 

Before="' echo "Testing, testing, one two three four five six seven eig \rht nine ten"\r\nTesting, testing, one two three four five six seven eight nine ten\r\n'"
```

Besides being visually confusing, this also causes a problem if I `sendline()` a command and then `expect()` that same command to verify all characters arrived.  That `expect()` fails because extra '\r' characters were added.

Does anyone have advice on how to fix this?

**Comment by jquast** [comment]
As you are using pexpect, you are providing a virtual terminal. That virtual terminal's with, in addition to the length of your prompt, is more than likely precisely 80 columns.

The '\r' that you see is the output of the remote terminal driver, to indicate the cursor should move to column 1 of the next row -- the same effect of authoring a long line at a local prompt requires.

> Does anyone have advice on how to fix this?

Firstly, I would tell you that, given you know your input (you sent it with sendline), I suggest finding an alternate design that does not depend on an exact replica of your input in your output.

However, you may expediently resolve this by adjusting the window size, http://pexpect.readthedocs.org/en/latest/api/pexpect.html#pexpect.spawn.setwinsize

**Comment by jquast** [comment]
I would also suggest, to execute remote ssh commands without a terminal driver, to use paramiko. You can more accurately receive output that is not artifically wrapped at 80 columns, as well as better identity management and remote command return values.

**Comment by mbanders** [comment]
I tried using setwinsize, but unfortunately had the same result:
```python
s = pexpect.spawn('ssh ...')
s.logfile_read = sys.stdout
s.setwinsize(200,200)
s.sendline('echo "Testing, testing, one two three four five six seven eight nine ten"')
s.expect("tester@vm.*# ")
print('\n\nBefore="%s"' % repr(s.before))
```

**Comment by mbanders** [comment]
> I would also suggest, to execute remote ssh commands without a terminal driver, to use paramiko. 

Yeah we've tried paramiko a few times, and for many reasons our team kept using pexpect for the past few years - pexpect is just generally better.  The line-wrapping isn't a big deal, but it would be cool to somehow fix it.

I saw someone else tried setwinsize and it also didn't work for them:  http://stackoverflow.com/questions/16602513/preventing-linewrap-when-using-pexpect-bash
That person ended up using:
```bash
spawn = pexpect.spawn('/bin/bash --noediting')
```

Is that recommended?

**Comment by jquast** [comment]
You may be sending setwinsize at an inappropriate time -- too early for bash to receive the SIGWINCH notification on the remote end.

**Comment by mbanders** [comment]
> You may be sending setwinsize at an inappropriate time -- too early for bash to receive the SIGWINCH notification on the remote end.

Thank you! Thank you! That fixed it completely - just doing setwinsize slightly later.  That fixed a problem that's been bugging us for a while.

**Comment by hackrole** [comment]
thank, this save me.
