### ISSUE TITLE
readline does not return specified N line

### ISSUE THREAD

**Issue by heniotierra** [pexpect/pexpect#243]
Hi,

I'm trying to use ```readline``` to read an specific line number, but it just doesn't work, always printing the lines in sequence even if line number is specified. I'm using pexpect 4.0.dev with Python 2.7.
```
import pexpect
process = pexpect.spawn("/usr/bin/omxplayer -I \"/home/pi/Perlman Tartini Devil's trill Part 4 onlive(corrected audio)-LnvUS0QxDYo.m4a\"")
print process.readline(8)                       #this prints the first line of the output
print process.readline()                         #this prints the second line of the output
```

Am I doing something wrong here?

**Comment by heniotierra** [comment]
Nevermind, just found that the 'size' argument is generally ignored when informed...
Anyway, is there a reasonably easy way to solve this problem?

**Comment by jquast** [comment]
> Nevermind, just found that the 'size' argument is generally ignored when informed...

Yes, I wrote the docstring to clarify, but did not write the original API that is published. I agree it is too bad.

> Anyway, is there a reasonably easy way to solve this problem?

Sure, write yourself an assisting ``def readto_line(process, line_no)`` function.

**Comment by heniotierra** [comment]
> Sure, write yourself an assisting def readto_line(process, line_no) function.

Haha, that's just not very elegant... And not very useful either if I had to go back to some previous line. But I found a way to do what I needed without that function. :+1:
