### ISSUE TITLE
pxssh.login unreachable condition

### ISSUE THREAD

**Issue by rminsk** [pexpect/pexpect#244]
In the methd pxssh.login there is the line

    elif i==6: # Connection closed by remote host

The line is unreachable because the expression list only has 6 elements.  Should the expression list have EOF as the seventh element?

**Comment by jquast** [comment]
``elif i==6`` matches the sixth element of a 0-index list, at line number 280. https://github.com/pexpect/pexpect/blob/cde8e15893edd87c61acf0515fd217554d21ce51/pexpect/pxssh.py#L280

```
>>> l[6]
'(?i)connection closed by remote host'
```
