### ISSUE TITLE
Regular expression should be compiled with with re.MULTILINE flag

### ISSUE THREAD

**Issue by rminsk** [pexpect/pexpect#246]
Regular expression should be compiled with with re.MULTILINE flag.  This would allow "^" to be used for beginning of line instead of beginning of string.  I am currently compiling my own regular expression with the MULTILINE flag and passing them in.

**Comment by jquast** [comment]
@rminsk can you please research whether Don Libre's original expect implementation compiled with MULTILINE flag?

**Comment by rminsk** [comment]
I have downloaded the original expect and looked at the source.  Just examining the source I'm still not clear.  The expect man page says"Regexp-style patterns follow the syntax defined by Tcl's regexp" but it uses it's own regex implementation.  The TCL regexp takes a "lineanchor" option or a (?w) embedded option.

 I will write some test cases to test the behavior.

**Comment by takluyver** [comment]
Given that you can pass compiled regexes, my instinct is not to change this
now. If people's code breaks because we compile it with different regex
flags, it won't be easy to recognise that that's the cause.

**Comment by jquast** [comment]
I second the decision to leave the implicit regular expression compilation as-is for the same reasons. explicit regex compilation is available for anyone who wishes to set alternate flags.

Thank you for the suggestion @rminsk ! Unfortunately, as pexpect is such a late-term project, it is our wish to ensure consistent API behaviour.
