### ISSUE TITLE
Pexpect does not seem to always wait for the prompt

### ISSUE THREAD

**Issue by jaschil2** [pexpect/pexpect#262]
Hello,

I have this problem occasionally when using pexpect, which causes huge problems for my code. As an example, I have the following:

    px_ssh.prompt()
    px_ssh.sendline("echo '" + qscript + "' > batch_script")
    px_ssh.prompt()
    px_ssh.sendline('qsub batch_script')
    px_ssh.prompt()
    qsub_out=px_ssh.before.decode('utf-8').split('\n')[-2]
    px_ssh.sendline('pwd')
    print(qsub_out)
    return qsub_out.split('.')[0]

qscript is a batch script string. Many times, this portion of the code will return a different part of the output than the job id it is supposed to return. This is a portion of the log:

    [PEXPECT]$ echo '#PBS -l nodes=1:ppn=16
    #PBS -l walltime=04:00:00
    #PBS -j oe
    #PBS -q secondary
    #PBS -o QSUB.stdout
    #PBS -N Ga_0.3-3-3.5_0.0001-30-4

    cd ${PBS_O_WORKDIR}
    cp autogen.d12 INPUT
    module load openmpi/1.6.4-intel-13.1
    mpirun -np 16 ~/bin/Pcrystal >& autogen.d12.o
    rm fort.*.pe*
    ' > batch_script
    qsub batch_script
    pwd
    echo '#PBS -l nodes=1:ppn=16
    > #PBS -l walltime=04:00:00
    > #PBS -j oe
    > #PBS -q secondary
    > #PBS -o QSUB.stdout
    > #PBS -N Ga_0.3-3-3.5_0.0001-30-4
    > 
    > cd ${PBS_O_WORKDIR}
    > cp autogen.d12 INPUT
    > module load openmpi/1.6.4-intel-13.1
    > mpirun -np 16 ~/bin/Pcrystal >& autogen.d12.o
    > rm fort.*.pe*
    > ' > batch_script
    [PEXPECT]$ qsub batch_script
    pwd
    cd /projects/erg/jaschil2/QMCDB/Elemental/Ga/Ga_0.3-3-3.5_0.0001-30-10
    cd /projects/erg/jaschil2/QMCDB/Elemental/Ga/Ga_0.3-3-3.5_0.0001-30-103024980.cc-mgmt1.campuscluster.illinois.edu
    [PEXPECT]$ pwd
    /projects/erg/jaschil2/QMCDB/Elemental/Ga/Ga_0.3-3-3.5_0.0001-30-4
    [PEXPECT]$ cd /projects/erg/jaschil2/QMCDB/Elemental/Ga/Ga_0.3-3-3.5_0.0001-30-1 
    0ls
    pwd

From the log, it appears that it doesn't seem to wait for the prompt in between commands. Consequently, my script will sometimes return strings like:
    cd /projects/erg/jaschil2/QMCDB/Elemental/Ga/Ga_0.3-3-3.5_0.0001-30-4'

Do you have any idea how I might solve this issue? I appreciate your help.

**Comment by jquast** [comment]
Unless you can produce a failing test case that demonstrates a bug in pexpect, I cannot afford to help, sorry. May I suggest mocking up a reproducable script and using any of https://mail.python.org/mailman/listinfo/python-list https://stackoverflow.com/ or https://www.python.org/community/irc/ for further support?
