### ISSUE TITLE
test_max_no_icanon: AssertionError: TIMEOUT not raised

### ISSUE THREAD

**Issue by ignatenkobrain** [pexpect/pexpect#276]
```
[brain@x1carbon pexpect]$ py.test-3 tests/test_maxcanon.py 
============================= test session starts ==============================
platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.3
rootdir: /home/brain/git/fedora/python-pexpect/pexpect, inifile: setup.cfg
collected 3 items 

tests/test_maxcanon.py .F.

=================================== FAILURES ===================================
_______________________ TestCaseCanon.test_max_no_icanon _______________________

self = <tests.test_maxcanon.TestCaseCanon testMethod=test_max_no_icanon>

    @pytest.mark.skipif(
        sys.platform.lower().startswith('freebsd'),
        reason='os.write to BLOCK indefinitely on FreeBSD in this case'
    )
    def test_max_no_icanon(self):
        " may exceed maximum input bytes if canonical mode is disabled. "
        # given,
        child = pexpect.spawn('bash', echo=self.echo, timeout=5)
        child.sendline('stty -icanon imaxbel')
        child.sendline('echo BEGIN; cat')
        send_bytes = self.max_input + 11
    
        # exercise,
        child.sendline('_' * send_bytes)
    
        # fast forward beyond 'cat' command, as ^G can be found as part of
        # set-xterm-title sequence of $PROMPT_COMMAND or $PS1.
        child.expect_exact('BEGIN')
    
        if os.environ.get('TRAVIS', None) == 'true':
            # Travis-CI has intermittent behavior here, possibly
            # because the master process is itself, a PTY?
            return
    
        # BEL is *not* found,
        with self.assertRaises(pexpect.TIMEOUT):
>           child.expect_exact('\a', timeout=1)
E           AssertionError: TIMEOUT not raised

tests/test_maxcanon.py:165: AssertionError
----------------------------- Captured stdout call -----------------------------

 tests.test_maxcanon.TestCaseCanon.test_max_no_icanon 
====================== 1 failed, 2 passed in 2.60 seconds ======================
```

**Comment by ignatenkobrain** [comment]
I've tried to run this testcase in interpreter. If I will wait for ~15 seconds after `expect_exact('BEGIN')` executed, it raises TIMEOUT, otherwise no.

**Comment by takluyver** [comment]
Sounds like something is taking a lot longer than expected. @jquast understands this part of the code better than me.

**Comment by ignatenkobrain** [comment]
hm, just waiting didnt help. I need to execute `child.expect_exact('\a', timeout=1)` for 10-20 times and it will raise exception.

**Comment by ignatenkobrain** [comment]
after each execution I see changed `buffer` and `before` inside `child`. Looks like something goes wrong with buffering.

**Comment by takluyver** [comment]
Asserting that it raises TIMEOUT is really just a way to check that the pattern you're expecting is not matched, so if you do it enough times you'll certainly run out of `\a` in the output. However, the test is checking that it doesn't produce `\a` at all, and clearly it does.

**Comment by jquast** [comment]
These tests were written to place numeric boundaries on the documentation in send() in the form of a proof.

http://pexpect.readthedocs.org/en/stable/api/pexpect.html#pexpect.spawn.send

That Fedora has different results than Debian really isn't pexpect's concern. I'll propose a PR to remove the tests entirely.

I certainly am not about to get into the minutia of documenting "On debian linux, this is <some size>, on fedora, <another>" -- the true purpose here was to document kernels, I didn't realize linux flavors are in such a state.

**Comment by jquast** [comment]
See PR #279
