### ISSUE TITLE
pexpect and sagemath

### ISSUE THREAD

**Issue by pcpa** [pexpect/pexpect#289]
I did package sagemath on fedora some years ago. Right now, the only bundled interface is pexpect.
See https://fedorahosted.org/fpc/ticket/238
The main problem was that, at the time, newer pexpect would not play well with sagemath, there were some echo issues, and getting out of sync.
Just a minor heads up, and letting you know that I would want to help in making sure it works with upstream releases of pexpect.
I remember I did several attempt patches, but never got it fully functional, because I am not 100% familiar with either pexpect or sagemath interface to pexpect.

**Comment by billpage** [comment]
You might be interested in

http://trac.sagemath.org/ticket/10295

and the email thread at:

https://groups.google.com/forum/#!searchin/sage-devel/unicode$20in$20sage$20worksheets/sage-devel/oyTKIfPlCRs/so6s0yO59c0J

as well as the patch at

https://github.com/pexpect/pexpect/pull/216

**Comment by jdemeyer** [comment]
I think this can be closed now: SageMath is using pexpect-4.0.1 + some pull requests (of those, #304 and #291 have not been merged upstream yet).

**Comment by takluyver** [comment]
OK, thanks.
