### ISSUE TITLE
output is different when added one more expect

### ISSUE THREAD

**Issue by miichy** [pexpect/pexpect#292]
def ssh_dir_exist(child):
1      #child.sendline("whoami")
2     #who = child.expect(['bestadmin','root'])
3      #print who
      child.sendline("cd /home/dataa")
      i = child.expect(['#','No such file or directory','$'])
      print i

comment the 1 2 3line,the output is 2; remove the  '#',the output is 0?before the step,i connect the host and su the root user.

**Comment by takluyver** [comment]
The first `expect()` will read up to the match. So if there's a `$` anywhere before the `whoami` result, when you comment those lines out, it will find that.

**Comment by miichy** [comment]
Thanks for your quick reply.Got it~~~

**Comment by takluyver** [comment]
:-)
