### ISSUE TITLE
SyntaxError generated with python2.7

### ISSUE THREAD

**Issue by kiwifb** [pexpect/pexpect#297]
When installing `pexpect-4.0.1` or master with `python2.7` I get the following message
```
byte-compiling /home/fbissey/sandbox/git-fork/sage/local/lib/python2.7/site-packages/pexpect/async.py to async.pyc
  File "/home/fbissey/sandbox/git-fork/sage/local/lib/python2.7/site-packages/pexpect/async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax
```
I don't get the message with `python3.4`. The install completes successfully and I haven't encountered a problem so far.

**Comment by jquast** [comment]
Same as #220, not a bug. Upgrade pip and the error goes away.

**Comment by kiwifb** [comment]
Not using `pip`. I have noticed in `Gentoo` portage and while working on upgrading `sage`'s shipped `pexpect`. But I see you suggest we just don't ship it for `python2`. We, in distros, don't like stuff like this but you obviously noticed already.

**Comment by jquast** [comment]
it ships fine for python2. The file may be included. It may not be compiled with a python 2 interpreter -- but that is not a failure.  Portage tools should not fail because python 3 code files could not be pre-compiled by a "python -mcompileall" or equivalent.
