### ISSUE TITLE
how to  assignment  the content of logfile to a  variable?

### ISSUE THREAD

**Issue by mechenglei** [pexpect/pexpect#299]
now, i write the logfile to a file .Then ,read the content from the file.But ,whil i use multi thread, the content will be out of order. xxx.before() or xxx.after() only contains a part of output.

**Comment by takluyver** [comment]
I'm not quite sure what you're asking. When you use multiple threads, you need to be careful about how data is passed between them, to avoid race conditions. This problem comes up whenever you program with threads; it's not specific to pexpect.

**Comment by mechenglei** [comment]
I want to record the operations of what i did on the devices. If i wrote the log to a log file while i used multi threads, the content of log would be out of order.So i want to know, could i  assignment the content of logfile to a variable, like this: variable = child.logfile.read().

**Comment by takluyver** [comment]
If you're using different `spawn` instances in each thread, simply give them different log files. If you're sharing one spawn instance between threads... then you probably have bigger problems than the logging. For a given subprocess, there should be only one thread talking to it.

You can read the logfile back into a variable, but I don't see how it would help with threading issues.
