### ISSUE TITLE
'import pxssh' doens't work on pexpect (4.0.1)

### ISSUE THREAD

**Issue by franza73** [pexpect/pexpect#302]
I used to use 'import pxssh' in my scripts. The recent version of pexpect package doesn't support this anymore and the documentation at http://pexpect.readthedocs.org/en/stable/api/pxssh.html also uses this format. 

If the user now needs to 'from pexpect import pxssh', than the documentation should be corrected. If not,   'import pxssh' should be reinstated.

$ pip list | grep pexpect 
pexpect (4.0.1)
$ python
Python 2.7.10 (default, Sep 23 2015, 04:34:14) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import pxssh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pxssh
\>\>\> from pexpect import pxssh
\>\>\>

**Comment by takluyver** [comment]
Yep, it's a docs problem. Thanks for point it out, I'll get it fixed.

pxssh was moved into the pexpect package for the 3.0 release, but we left a shim in so `import pxssh` would carry on working. For 4.0, we decided to take the shim out, so you have to use the new `from pexpect import pxssh` imports.
