### ISSUE TITLE
Password refused when login pxssh

### ISSUE THREAD

**Issue by vjcharlie** [pexpect/pexpect#312]
So, the issue I am having is simple.

When I do

s.login(host, username, password)

I get a password refused error...

It is really weird because I get that error only when I pass the password in a variable.. if I pass it hard-coded it works fine...

Any help?

Thanks

**Comment by takluyver** [comment]
Pexpect has no idea whether you're passing a variable or a hard-coded string. The way Python works, that can't really make a difference. The only thing that would make sense is that the variable doesn't contain exactly what you think it does. There might be trailing spaces, or an issue with character encoding. Try doing `print(repr(password))` and `print(repr('hard_coded_string'))` just before using it, and see how they differ.
