### ISSUE TITLE
conda install appears incomplete

### ISSUE THREAD

**Issue by wasade** [pexpect/pexpect#316]
I'm unable to do an import of pexpect after a conda install. It appears that the `exceptions.py` file is missing. Details below using a new conda environment, clean pexpect install on CentOS 6.6

```bash
$ conda install pexpect
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/REMOVED/miniconda3/envs/test:

The following NEW packages will be INSTALLED:

    pexpect: 3.3-py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##############################################################################################################################################| 100%
$ python -c "import pexpect"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/REMOVED/miniconda3/envs/test/lib/python2.7/site-packages/pexpect/__init__.py", line 69, in <module>
    from .exceptions import ExceptionPexpect, EOF, TIMEOUT
ImportError: No module named exceptions
$ ls /home/REMOVED/miniconda3/envs/icu/lib/python2.7/site-packages/pexpect/
ANSI.py  ANSI.pyc  fdpexpect.py  fdpexpect.pyc  FSM.py  FSM.pyc  __init__.py  __init__.pyc  pxssh.py  pxssh.pyc  replwrap.py  replwrap.pyc  screen.py  screen.pyc
$ python --version
Python 2.7.11 :: Continuum Analytics, Inc.
```

**Comment by takluyver** [comment]
You've got your versions in a muddle - that code `from .exceptions import ...` is from a later version of Pexpect. I'd guess that you've upgraded pexpect using pip in another conda environment - conda uses hardlinking, which can produce some bizarre effects with environments affecting one another.

I think the easiest way to work around it in this environment is to use pip again to upgrade conda. To fix it for all environments, you'll probably need to persuade conda to re-download and unpack pexpect.

**Comment by wasade** [comment]
Ah, fun fun. Thanks, and I apologize for not recognizing that

**Comment by takluyver** [comment]
No problem. I know it can be tricky to work out what's caused a problem at
times.

**Comment by wasade** [comment]
Just to follow up, after futzing with this for a bit, what I ended up having to do was to uninstall `pexpect` and `ipython`, `mv pkgs/pexpect-3.3-py* to_somewhere_else/`, then reinstall `pexpect` and `ipython`. Upgrading conda did not do the trick. I do not recall installing pexpect via pip, but it's possible one of the pip-only dependencies in one of my environments needed it.
