### ISSUE TITLE
Read text after matched text or without expect

### ISSUE THREAD

**Issue by pamolloy** [pexpect/pexpect#317]
I'm connecting to a device and trying to login. The state is unknown, but since I'm connecting through `minicom` there is a consistent welcome message. Manually connecting with `minicom`, I simply hit Enter and then may see a user prompt, root prompt or login prompt. Additionally, when logging in I sometimes run into other weird messages.

How can I check the text after the text that was matched by the expected pattern? Or how can I check the output without calling `expect()`?

> The `before` property will contain all text up to the expected string pattern. The `after` string will contain the text that was matched by the expected pattern.

The above naming is a bit confusing.

**Comment by takluyver** [comment]
Yes, it is confusing. It's like that for historical reasons. Pexpect hasn't necessarily read the remaining text from the underlying file descriptor, but if it has, it will be in `.buffer`.

**Comment by pamolloy** [comment]
And if it isn't in `.buffer`? I tried that with inconsistent results.

**Comment by pamolloy** [comment]
It seems like the only way is to call `expect()` with a short timeout and catch the `EOF` exception. But that sounds like it would get ugly quickly.

**Comment by jquast** [comment]
How do you expect the unexpected? :)

You can call read_nonblocking method directly, bypassing the expect method. http://pexpect.readthedocs.org/en/stable/api/pexpect.html#pexpect.spawn.read_nonblocking to just slurp up any remaining output after your expected match.

Expecting for EOF, and expecting an appropriate timeout to raise, then inspecting ``.buffer`` for such output is perfectly fine also.

another note -- minicom is a terminal emulator in its own right, performing cursor/screen addressing, using a program like cu(1) or tip(1) might get rid of unnecessary terminal escape sequences.

**Comment by takluyver** [comment]
> How do you expect the unexpected? :)

Easy!

```python
p.expect("The Spanish Inquisition")
```

```
ValueError: Nobody expects the Spanish Inquisition!
```

**Comment by pamolloy** [comment]
Thanks for the quick responses @takluyver and @jquast!

I thought I could expect `\r\n` and check `.before`, but that wasn't working very well. I'll take a look at `read_nonblocking()`.

Catching the `TIMEOUT` exception was inconsistent. The contents of `timeout.buffer` and `timeout.buffer` contained _multiple_ commanded prompts in the case of expecting a login prompt when there is a command prompt. In the case of a password prompt the above variables only contain newlines.

**Comment by pamolloy** [comment]
I ended up using `pyserial` to interact with the device. Thanks for the feedback!
