### ISSUE TITLE
 AttributeError: 'module' object has no attribute 'spawn' (New Issue)

### ISSUE THREAD

**Issue by redraven984** [pexpect/pexpect#321]
Hi All,

I'm getting the same error described here: https://github.com/pexpect/pexpect/issues/166

AttributeError: 'module' object has no attribute 'spawn'

I checked the path and it looks like python is referencing the correct location (site-packages). I am running windows 8.1 and python 2.7.

What else should I check?

**Comment by takluyver** [comment]
If you're on Windows, that's expected. `pexpect.spawn` has historically used ptys, which are a Unix thing that Windows doesn't have. We chose not to make the same name available on Windows because it couldn't behave quite the same.

http://pexpect.readthedocs.org/en/stable/overview.html#pexpect-on-windows

**Comment by 007-JB** [comment]
@takluyve lot's of love from peeps but you don't exactly tell us how to resolve bru

**Comment by takluyver** [comment]
It depends on what you want to do. Briefly, your options are:

- Run the code in a Unix environment (Linux, Mac, or I think WSL should work)
- Change the code to use PopenSpawn (may not work work, some programs won't go into their interactive mode when run this way)
- Use one of the Windows specific pexpect alternatives linked in the docs (both unmaintained, last time I checked)

There is no simple, complete Windows equivalent, as far as I know.

**Comment by zulven** [comment]
For windows you could just add your own class for PowerShell like this:
import subprocess
from typing import List, Union
from uuid import uuid4
import re
import pexpect
from pexpect.popen_spawn import PopenSpawn

class PowerShellProcess:
    """Executes PowerShell commands and returns the output."""

    def __init__(
        self,
        strip_newlines: bool = False,
        return_err_output: bool = False,
        persistent: bool = False,
    ):
        self.strip_newlines = strip_newlines
        self.return_err_output = return_err_output
        self.prompt = ""
        self.process = None
        if persistent:
            self.prompt = str(uuid4())
            self.process = self._initialize_persistent_process(self.prompt)

    @staticmethod
    def _initialize_persistent_process(prompt: str) -> PopenSpawn:
        process = PopenSpawn(
            "pwsh -NoProfile", encoding="utf-8"
        )
        # Set the custom prompt
        process.sendline(f"function prompt {{'{prompt}'}}")

        process.expect_exact(prompt, timeout=10)
        return process

    def run(self, commands: Union[str, List[str]]) -> str:
        """Run commands and return final output."""
        if isinstance(commands, str):
            commands = [commands]
        commands = ";".join(commands)
        if self.process is not None:
            return self._run_persistent(
                commands,
            )
        else:
            return self._run(commands)

    def _run(self, command: str) -> str:
        """Run commands and return final output."""
        try:
            output = subprocess.run(
                f"pwsh -Command {command}",
                shell=True,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
            ).stdout.decode()
        except subprocess.CalledProcessError as error:
            if self.return_err_output:
                return error.stdout.decode()
            return str(error)
        if self.strip_newlines:
            output = output.strip()
        return output

    def process_output(self, output: str, command: str) -> str:
        # Remove the command from the output using a regular expression
        pattern = re.escape(command) + r"\s*\n"
        output = re.sub(pattern, "", output, count=1)
        return output.strip()

    def _run_persistent(self, command: str) -> str:
        """Run commands and return final output."""
        if self.process is None:
            raise ValueError("Process not initialized")
        self.process.sendline(command)

        # Clear the output with an empty string
        self.process.expect(self.prompt, timeout=10)
        self.process.sendline("")

        try:
            self.process.expect([self.prompt, pexpect.EOF], timeout=10)
        except pexpect.TIMEOUT:
            return f"Timeout error while executing command {command}"
        if self.process.after == pexpect.EOF:
            return f"Exited with error status: {self.process.exitstatus}"
        output = self.process.before
        output = self.process_output(output, command)
        if self.strip_newlines:
            return output.strip()
        return output

Should work for most use cases

**Comment by zen-ham** [comment]
Would be nice if it worked on windows.
