### ISSUE TITLE
Can not kill spawned child from another thread

### ISSUE THREAD

**Issue by egorf** [pexpect/pexpect#322]
Hi! 

Is there a correct way to expect a killed process? When I try to kill a process, started by another thread, I can't see the `EOF` exception, but instead see the standard 30 seconds timeout.

I am using `Python 2.7.3`, `pexpect 3.3`. I can't upgrade the packages at the moment.

Please take a look at this example(nvm the creepy ChildHolder name). I run `sleep 5` command in a separate thread, then run spawn.close() in the main thread. Instead of exiting immediately after the command, I need to wait 30 seconds. 

```
import threading
import pexpect
import time

class ChildHolder:

    def __init__(self):
        self.child = 0

    def do_stuff(self):
        print("Spawning")
        self.child = pexpect.spawn("sleep 5")
        print("Expecting")
        self.child.expect(pexpect.EOF)
        print("Done")

print("Pexpect testing")
ch = ChildHolder()

test_thread = threading.Thread(target = ch.do_stuff)
test_thread.start()
print("thread started")

time.sleep(1)

ch.child.close()
print("Process killed")

print("Waiting for join")
test_thread.join()
print("Over")

```

**Comment by takluyver** [comment]
I would try to use `.kill()` to terminate the child process, then use `.close()` after you've got EOF back.

**Comment by egorf** [comment]
Hi!
That seems to work. Do you have any idea why?

Just in case I've edited the code to look like this:

```
import threading
import pexpect
import time
import signal

class ChildHolder:

    def __init__(self):
        self.child = 0

    def do_stuff(self):
        print("Spawning")
        self.child = pexpect.spawn("sleep 5")
        print("Expecting")
        self.child.expect(pexpect.EOF)
        print("Done")

print("Pexpect testing")
ch = ChildHolder()

test_thread = threading.Thread(target = ch.do_stuff)
test_thread.start()
print("thread started")

time.sleep(1)

ch.child.kill(signal.SIGINT)
print("Process killed")

print("Waiting for join")
test_thread.join()
print("Joined")
ch.child.close()
print("Closed. Over")
```

**Comment by takluyver** [comment]
There are two moving pieces when you use `spawn`: the pty and the process (see [this diagram](http://ptyprocess.readthedocs.org/en/latest/) for an illustration). The pty is what we use to communicate with the process, except for signals. `close()` acts primarily to close the pty, while `kill()` sends a signal to the process. `expect()` is reading the pty, so I guess that if you close it while an expect() call is running, it gets into some unexpected state. By using kill(), we can signal the process and cause it to die without closing the pty from our end.

**Comment by egorf** [comment]
Thanks! Good job running this amazing module!
