### ISSUE TITLE
AttributeError: 'module' object has no attribute 'popen_spawn'

### ISSUE THREAD

**Issue by msmosso** [pexpect/pexpect#328]
Hi all,

I'm facing the following issue

```
C:\Users\Matheus>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexpect
>>> p = pexpect.popen_spawn.PopenSpawn('dir')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'popen_spawn'
```

Do you have any clues?

Thanks in advance.

**Comment by msmosso** [comment]
My bad. I miss ```from pexpect import popen_spawn```.

**Comment by dotjavafile** [comment]
This seems like a bug.

**Comment by jnatschev** [comment]
Hi.

Not an absolute pexpect expert, though my understanding is:
If you executed:
	import pexpect
then the message is correct, there is no attribute named popen_spawn.

However,
If you execute:
	from pexpect import popen_spawn
then all attributes and methods of the module popen_spawn of the package pexpect will be availabe.

The way it works, as I see it, is that “pexpect” is a package containing modules. If you "import pexpect”, then only a subset of all that is available is imported. Therefore, if there is a specific requirement for a package “pexpect” module, then it needs to be imported using:

from pexpect import <module_name>

Hope this helps.


Cheers,
John Natschev.

**Comment by Eoksni** [comment]
Well, I'm not an advanced Python user, I usually only use it for Numpy/scikit etc, but I've never seen such behavior with other packages. Usually when I import a package, I can just "dot" into package and use freely whatever is inside. I don't know if this situation with `popen_spawn` is a bug or not, but it is certainly very confusing and imo at least should be mentioned in the docs.

**Comment by jnatschev** [comment]
If that is the case, then the programmers of those packages you write about will have programmed that into their __init__.py file.

see for yourself.

edit and save the pexpect __init__.py file.

under these lines (based on pexpect 4.3.0):
from .exceptions import ExceptionPexpect, EOF, TIMEOUT
from .utils import split_command_line, which, is_executable_file
from .expect import Expecter, searcher_re, searcher_string

add:
from . import popen_spawn

kick python off again for an interactive session.
import pexpect

you ought to have access to pexpect.popen_spawn now.



Cheers,
John Natschev
‌
