### ISSUE TITLE
Execution returns <pexpect.popen_spawn.PopenSpawn object at 0x029678F0>

### ISSUE THREAD

**Issue by msmosso** [pexpect/pexpect#329]
Hi all,

When I run the following code, i'm receiving just <pexpect.popen_spawn.PopenSpawn object at 0x029678F0>

What's wrong?

Thanks in advance.

```
import pexpect
from pexpect import popen_spawn
import sys

try:
    co = pexpect.popen_spawn.PopenSpawn('ftp localhost',encoding="utf-8")
    co.expect("",timeout=30)
    co.logfile = sys.stdout
    co.timeout = 4
    co.expect(":")
    co.sendline("test")
    co.expect(".*word:.*")
    co.sendline("test123")
    co.sendline('dir')
    co.expect('ftp>')
    co.close()


except Exception as e:
    print(co)
```

**Comment by takluyver** [comment]
Well, `co` is a PopenSpawn instance. Did you mean `print(e)`?

**Comment by msmosso** [comment]
@takluyver Thanks. Now I'm getting this: ```got <type 'str'> ('') as pattern, must be one of: <type 'unicode'>, pexpect.EOF, pexpect.TIMEOUT```

**Comment by takluyver** [comment]
That probably means that `encoding='utf-8'` is not the right option for your system or for that subprocess. What system are you on? If it's Windows, the encoding might be 'cp1252' (that's the default for western European languages, in any case).

Do you need to have the try/except to catch the exception? If there's an uncaught exception, it's automatically printed out with a traceback, which is more helpful for debugging.

**Comment by msmosso** [comment]
@takluyver Hi Thomas, I think it was due to the accent in the output of ```ftp```. 

Thanks!
