### ISSUE TITLE
replwrap.run_command stdout & stderr hook

### ISSUE THREAD

**Issue by jkgeyti** [pexpect/pexpect#331]
When running slow commands with occasional output in replwrap, it would be good to be able to receive output as it's written to stdout/stderr.

For my own purpose, I've just added an optional lambda argument to `replwrap.run_command`, that is called with `self.child.before` in the inner loop, whenever it's appended to `res` (see below), but it would be good to have this implemented in a more rigorous manner, separating stdout from stderr output.

    def run_command(self, command, timeout=-1, progress_fn=None): # added progress_fn
        ...
        for line in cmdlines[1:]:
            ...
            res.append(self.child.before)
            progress_fn(self.child.before) # added line
        ...
        return u''.join(res + [self.child.before])

I'd be happy to take a stab at it, but I haven't looked further into the source, and wanted to get some feedback on the idea first.

**Comment by takluyver** [comment]
Thanks for looking at this! That won't quite capture output as it's written - it will pass `progress_fn` the output from each command (technically each line) at a time. Capturing it as it goes is a bit trickier, but probably feasible (although part of the prompt might turn up in the captured output).

We can't separate stdout and stderr, because they're combined at the OS level before we even get them. See the diagrams here: http://ptyprocess.readthedocs.org/en/latest/

**Comment by jkgeyti** [comment]
Alright, feasible or not, not being able to capture stdout and stderr due to it being in a pty is clearly a separate issue, so I'll leave that out of this feature suggestion.

Could you expand on in which cases `progress_fn` won't necessarily capture output? I can see problems, if you were trying to capture output char by char, but as we're capturing output line by line, I'm not seeing where it could go wrong.

I think line by line capturing is a fair limitation to impose when we're in an environment where we need the whole line, to decide what to do with it (namely checking if it's a prompt). You could potentially have both a safer "line by line" callback, as well as a "raw char by char" callback (that I suspect should be passed all the way into `self.child.expect_exact`.

Thoughts?

**Comment by takluyver** [comment]
Line by line of output would be fine, but what it currently does is line by line by *input*. i.e. if I call:

```python
rw.run_command('ls\ngit status\nps')
```

Then progress_fn will be called three times - once with the output from `ls`, then with the output from `git status`, and then with the output of `ps`.

**Comment by jkgeyti** [comment]
Pft, of course. I've stared myself blind on my own code. It's just by pure chance that I'm sending multiple commands in one go, where waiting for a single line from each command produces the expected result.

Oh well, it's a feature I really need, so I'll look into the source, and dig deeper for a better solution.

**Comment by takluyver** [comment]
If you set `rw.child.logfile_read` to a file-like object with a `write()` method, whatever Pexpect reads will be written to that immediately. That's the easiest way to get the data, I think.

**Comment by jkgeyti** [comment]
Perfect - that'll works for my purposes. I still think it would be a worthwhile addition to have a less "hacky" way of getting output callbacks line by line, but this will make do for now.

Thanks a lot!

**Comment by jquast** [comment]
Thank you @jkgeyti !
