### ISSUE TITLE
passmass not working

### ISSUE THREAD

**Issue by joelcollinsdc** [pexpect/pexpect#332]
I get this when trying to run passmass (python 2.7)

Traceback (most recent call last):
  File "./passmass.py", line 116, in <module>
    main()
  File "./passmass.py", line 106, in main
    child = login(host, user, password)
  File "./passmass.py", line 49, in login
    child.setlog (fout)
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1721, in setlog
    'member variable.')
pexpect.ExceptionPexpect: This method is no longer supported or allowed. Just assign a value to the logfile member variable.

**Comment by takluyver** [comment]
Oops. Do you want to make a pull request to fix the example?

**Comment by joelcollinsdc** [comment]
I'm pretty far from being experienced at this but I'm happy to try if you point me in the right direction.  I commented out the setlog line to get past it, what is the right way to approach this?

**Comment by takluyver** [comment]
The `setlog()` method was removed in favour of just setting the logfile attribute, like this:

```python
child.logfile = fout
```

**Comment by joelcollinsdc** [comment]
That was my second guess :)  When I do that... I dont see anything in the log file... even when there are errors or successes.  Shoudl I still put a PR with that in it?

**Comment by joelcollinsdc** [comment]
nevermind.  i misread

**Comment by jquast** [comment]
This was addressed in #333 thanks for your contribution, @joelcollinsdc !
