### ISSUE TITLE
support request: passmass potential changes / improvements

### ISSUE THREAD

**Issue by joelcollinsdc** [pexpect/pexpect#334]
I have a few questions around passmass:

- the log file records passwords, perhaps we should remove the log file by default but describe how to add it back in to troubleshoot?  happy to comment out the log line in a PR if you recommend this approach
- I did some dumb stuff to my password prompt (\[\e[0;31m\][\u@\h \W]\$\[\e[0m\] ), do you have a recommended way I could add some additional characters to COMMAND_PROMPT = '[$#] ' to accommodate this or am I out of luck?
- [removed 3rd question]

Thanks!

**Comment by joelcollinsdc** [comment]
disregard question 3, I see i'm an idiot, missing my array brackets

**Comment by takluyver** [comment]
It's an example, and not a particularly good one - if you want to do things over SSH, [paramiko](http://docs.paramiko.org/en/1.16/) is a better bet, and if you want to do them with pexpect, there's a [pxssh module](http://pexpect.readthedocs.org/en/stable/api/pxssh.html) for that.

Recording passwords is probably a bit silly even for an example, though. I think if you change `logfile` to `logfile_read`, it will only log the data sent from the server, which shouldn't include passwords.

**Comment by joelcollinsdc** [comment]
many thanks for all your help!
