### ISSUE TITLE
pxssh login not working with password warning

### ISSUE THREAD

**Issue by joelcollinsdc** [pexpect/pexpect#336]
I'm (still) working on a script to reset passwords... now trying with pxssh

this line:

`i = self.expect(["(?i)are you sure you want to continue connecting", original_prompt, "(?i)(?:password)|(?:passphrase for key)", "(?i)permission denied", "(?i)terminal type", TIMEOUT, "(?i)connection closed by remote host"], timeout=login_timeout)`

fails (i = 2) when this string is returned after the login:
Warning: your password will expire in 3 days

I realize the doc describes .hushlogin, which does work when I add this... but i'm hoping theres another way.  Is there a way that that that prompt can be made to not trigger the i=2 logic without a .hushlogin file?

**Comment by jquast** [comment]
I'm afraid our bug tracker and pexpect API cannot help you here, I am hopeful that you have already found a solution for your problem. Best of luck!
