### ISSUE TITLE
pxssh import issue

### ISSUE THREAD

**Issue by rubycarlin** [pexpect/pexpect#339]
import pxssh

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import pxssh
ImportError: No module named pxssh

from pexpect import pxssh

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    from pexpect import pxssh
  File "C:\Python27\lib\site-packages\pexpect-4.0.1-py2.7.egg\pexpect\pxssh.py", line 23, in <module>
    from pexpect import ExceptionPexpect, TIMEOUT, EOF, spawn
ImportError: cannot import name spawn

**Comment by takluyver** [comment]
pxssh is not currently supported on Windows, as it uses a pty.

**Comment by rubycarlin** [comment]
Can you tell me what is the alternative to pxssh on windows !!

Thanks in advance.

**Comment by takluyver** [comment]
[Paramiko](https://github.com/paramiko/paramiko), maybe.

**Comment by ewortzman** [comment]
I'm seeing inconsistent behavior with importing.  When I use `import pxssh`, it works on some systems and fails on others.  I've encountered one system where `from pexpect import pxssh` fails but `import pxssh` works.  

I can't seem to find any pattern to why this happens.  All system have version 4.0.1 installed using `pip`, but some have a `pxssh.py` file installed directly to $PYTHONHOME/site-packages, while others lack this file.

**Comment by takluyver** [comment]
I would guess that some of your systems have files from an older install of pexpect, or an older version installed through another mechanism. `from pexpect import pxssh` is the supported way to import it; if that fails, then I would guess it's finding an old version of pexpect; do `import pexpect; print(pexpect)` to see where it gets it from.

**Comment by ewortzman** [comment]
That makes sense.  I looked at the `pxssh.py` file and all it does is issue a warning that the module has been moved then import the correct module.  I'll update my files with the correct method of importing.
