### ISSUE TITLE
file created will have disappeared next reboot

### ISSUE THREAD

**Issue by teobo** [pexpect/pexpect#341]
Hi,
 using a snippet as this the file created will have disappeared next reboot what happened?
 That is 1.txt is not existing after next reboot anymore. 
 What would be a good practice to create persistent files?
tia
```
child.sendline(user)
child.expect('(?i)password:')
child.sendline(password)
child.expect(".*\# ")
child.send("echo hello>1.txt\r")

child.expect(".*\# ")
child.sendline("ls /root/\r")
child.expect(".*\# ")
child.sendline("echo hell >/root/12.txt\r")
child.expect(".*\# ")
```
...

outputs:
```
root@debian-amd64:~# ls /root/

```

**Comment by takluyver** [comment]
This is nothing to do with pexpect. It's up to the server you're running commands on what those commands do and where you should store files.
