### ISSUE TITLE
best practice for remote control spawned qemu images

### ISSUE THREAD

**Issue by teobo** [pexpect/pexpect#342]
Hi,
1)being newbie I dare asking for **best practice for remote controlling qemu** (even so it is much qemu topic):
Some times I got the I idea that on the long run, there could be better ways to remote control a quest. Maybe ssh and keys, as soon as possible. Normally the spawned process needs to first started. 
-For connecting to a running guest, you needed a second pexpect process then, dont you?
-Or you may say pexpect and qemu is perfect form beginning to end: for installing packages, starting and stopping services 
-and as there is no other out of box option, neither, qemu "user network mode" offers no IP-Connection from the host. So connecting from the host by ssh is that easy neither.
-one might alternatively opt to chroot into the image, configure ssh-server at init, and go without pexpect for that task?

2)Another problem is that much qemu -images offered boot directly to the window manager and not to the terminal login. How can this be secured? Are not there any kernel boot option to guide the init process to the terminal.

**Comment by jquast** [comment]
@teobo I appreciate your consideration that pexpect authors may help with your software design, but I must suggest that this is not the correct place or audience to help. A well-formed question on http://www.stackoverflow.com may get the response you are looking for. Best wishes!
