### ISSUE TITLE
"pexpect.pxssh.ExceptionPxssh: could not set shell prompt" on script that used to work

### ISSUE THREAD

**Issue by Committing** [pexpect/pexpect#344]
I was affected by the 123reg blackout where they deleted all their VPS'.

I have rebuilt my web server (Same IP) and I am now trying to run the same python script to connect to my other (same) server.

I get this error every time I try now and I cannot stop it.

![image](https://i.gyazo.com/0a7f5093ce7b5324ba84c307fb455304.png)

The script couldn't be more simple:

```
from pexpect import pxssh
s = pxssh.pxssh()

if not s.login ('{server_ip}', '{server_user}', '{server_pass}'):
    print "SSH session failed on login."
else:
    s.sendline("touch /var/node/example.txt;")
    s.prompt()
    print s.before
    s.logout()
```

------------------------------------------------------------

I have managed to supposedly get it to connect by altering it to this but then no commands are successful when I try them:

```
from pexpect import pxssh
s = pxssh.pxssh()

if not s.login ('{server_ip}', '{server_user}', '{server_pass}, auto_prompt_reset=False'):
    print "SSH session failed on login."
else:
    s.sendline("touch /var/node/example.txt;")
    s.prompt()
    print s.before
    s.logout()
```

I used to connect to this server fine every time before without issue. It is only since I have rebuilt the server (Plesk) that it was stopped working and it's driving me nuts! :)

Any ideas?

Edit: I have tried using both python 2.6.6 and 2.7 but both fail with the same error.

**Comment by takluyver** [comment]
Can you ssh to those other servers manually, and is there anything odd about them when you do?

With `auto_prompt_reset` disabled, try calling `s.interact()` after it has logged in - that should let you interact with the ssh session: see if there's a normal prompt afterwards.

**Comment by Committing** [comment]
Hi Takluyver - Thank you very much for your response.

I tested your script and it seems to say that it has done everything but no commands seem to actually run. (I also had to remove the s.prompt() as it was erroring)

I am able to SSH in to these servers manually absolutely fine. Nothing seems odd when I try. Nothing about these servers I am trying to connect to has changed.

I have however just tried to SSH into the server while in an SSH session in to the server I am trying to run the python script and it fails! Here is what happens:

![Image of Yaktocat](https://i.gyazo.com/d4abf122eaf8f663db939a61b4c29591.png)

I then ran a traceroute:

![Image of Yaktocats](https://i.gyazo.com/b9acedd38cb841af1c77bc39e858ff45.png)

If I try and ping the IP but it fails. If I try and ping it from another other server or locally it pings absolutely fine. It is only when I run it in the server that has just been rebuilt:

![Image of Yaktoca2t](https://i.gyazo.com/4409fd3592c3d1c638e4c23d179aaa6f.png)

Nothing about the remote server I am trying to connect to has changed.

I can pay you to help me if you think you can if this is out of the spec because I desperately need to get this working again. :(

Thank you!

**Comment by takluyver** [comment]
Sorry, I don't think I know enough about networking to work out an issue like that for you.

This seems to be an issue with your network configuration rather than with Pexpect, though perhaps Pexpect should give a more helpful error message.

**Comment by jquast** [comment]
@Committing Suggest you reduce your problem scenario to its most basic problem (seems DNS lookup issue?) and use stackoverflow.com from here, and there are certainly plenty of companies that provide software engineers by contract to help you if you are offering money.

Sorry we cannot help further, we can only volunteer our time to address bugs in the pexpect program. Best wishes!

**Comment by Committing** [comment]
I understand thank you for your help nonetheless.

I actually know the reason now thanks to Digital Ocean help. It turns out 123-reg had blocked the IP address of the DO server I was using for some reason. Whether it was automatic or not I'm not sure.

Cheers again
