### ISSUE TITLE
prompt method on pxssh.pxssh takes too long on "large output" (~14MByte)

### ISSUE THREAD

**Issue by AlonElharar1** [pexpect/pexpect#352]
While running the following lines:
        connection.sendline("cat  file_size_of_14_megabytes.log")
        connection.prompt():

The connection.prompt() takes "too long":
"too long" is means that cat 14 megabytes takes about 150 seconds - ~10 seconds for 1 single Mega.
The "prompt" method eventually goes to "def expect_loop(self, timeout=-1):" method on "Expecter" class.
On the following lines from implementation there is several problems:

```
While True:
       idx = self.new_data(incoming)
       ...
       incoming = spawn.read_nonblocking(spawn.maxread, timeout)
       time.sleep(0.0001)
```
1. The spawn.maxread defined to 2048, is too small number, but that number as no affect since the limit on OSX-El Capitan is 1024. the spawn.maxread number has no affect even if it defined to millions.
2. On the while loop for each incoming(small size) we check for new data on "idx = self.new_data(incoming)" - and that takes a lot of time.

The solution:
The solution is to read nonblocking data with greater size, so the "new_data" method handle a bigger data.

The solution is on "expect_loop(self, timeout=-1)" method:

```
while True:
            ....
            # No match at this point
            if (timeout is not None) and (timeout < 0):
                    return self.timeout()
            # Still have time left, so read more data
       (-) incoming = spawn.read_nonblocking(spawn.maxread, timeout)
       (+) incoming = ""
       (+) for _ in range(30):
       (+)     try:
       (+)         incoming += spawn.read_nonblocking(spawn.maxread, 0.5)
       (+)     except Exception:
       (+)         break
           time.sleep(0.0001)
       ....
```
- The "magic numbers" (0.5, 30) should be constant/parameter.
- The expect Exception can replaced to Timeout exception.
- My mail is elharrar.alon@gmail.com

**Comment by AlonElharar1** [comment]
Shrarpen the spoon will help me a lot. right now it's affected on smaller files too(size of ~3MB), slow user experience compared to terminal/shell direct connection, so sharpen the spoon will be great.

Thanks!

**Comment by ryanpetrello** [comment]
@AlonElharar1 I've opened a PR that I think should drastically improve performance - mind giving it a shot?

https://github.com/takluyver

**Comment by takluyver** [comment]
Closing as #464 was merged. Let me know if performance is still problematic in this case with Pexpect >= 4.4 - we can reopen the issue if necessary.
