### ISSUE TITLE
Won't install on Python 2.7

### ISSUE THREAD

**Issue by ukch** [pexpect/pexpect#355]
The latest version of pexpect uses the `yield from` syntax, which is Python 3 only, but setup is configured for Python 2.7+.

Attempting to install via pip yields the following error:

```
Compiling /tmp/pip-build-YyEzkz/pexpect/pexpect/async.py ...
  File "/tmp/pip-build-YyEzkz/pexpect/pexpect/async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax
```
Either this library should be marked as Python 3 only, or the syntax should be made compatible with both versions.

**Comment by takluyver** [comment]
It's fine - only the `pexpect.async` module requires Python 3. The rest of it has installed correctly and can be used. If you upgrade to a recent version of pip (`pip install --upgrade setuptools pip`), you won't even see the error message.

See: #318 #297 #296 #295 #290

**Comment by bms** [comment]
Hmm... can't it use trollius?
