### ISSUE TITLE
pexpect 4.1.0 not Python 2.7 compatible?

### ISSUE THREAD

**Issue by ccazabon** [pexpect/pexpect#357]
pexpect/async.py contains syntax which isn't valid in Python 2.7:

`
  File ".../lib/python2.7/site-packages/pexpect-4.1.0-py2.7.egg/pexpect/async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()
                             ^
SyntaxError: invalid syntax
`

I didn't see anything in the release notes about dropping Python 2.7 support, so I think this must have been accidental?

**Comment by ccazabon** [comment]
argh @ formatting - it's the `yield from` it's complaining about.

**Comment by takluyver** [comment]
The `pexpect.async` module is Python 3 only, the rest of Pexpect is still compatible with Python 2. Old versions of `pip` show you that error on installation, but should still install it successfully. If you upgrade pip, you shouldn't even see the error.
