### ISSUE TITLE
4.3.1 release?

### ISSUE THREAD

**Issue by takluyver** [pexpect/pexpect#370]
I'd like to do a new release to get the fix from #362 out there, because it's causing issues in downstream projects (takluyver/bash_kernel#55). @jquast @MountainRider: is there anything else that you think should be done before we do another release?

**Comment by MountainRider** [comment]
Do we want to merge #354?

**Comment by takluyver** [comment]
No objections from me.

**Comment by MountainRider** [comment]
I say go for it.

**Comment by jquast** [comment]
go ahead, yes, we need #362 out

**Comment by takluyver** [comment]
Released (though I got the version number wrong in the issue title: it's 4.2.1, not 4.3.1).
