### ISSUE TITLE
User can get a exit code of a command by pxssh?

### ISSUE THREAD

**Issue by Hochikong** [pexpect/pexpect#371]
I want to get the exit code of commands,pxssh can do that?

**Comment by takluyver** [comment]
If you're using pxssh to send commands to a remote shell, you will need to use the mechanism the shell provides to get the exit code. In bash, running `echo $?` will show the exit code.

**Comment by Hochikong** [comment]
@takluyver 
Thanks.
I know this,when I use pxssh on VyOS,I donno why I can't send this '?'.Maybe I need to ask VyOS development group
