### ISSUE TITLE
Pexpect.child.expect does not wait 

### ISSUE THREAD

**Issue by cihantunc** [pexpect/pexpect#372]
I am spawning an SSH connection that applies apt-get update and then apt-get install <programs>. My steps are as follows: 

```python
child.sendline('apt-get update && echo STEP_DONE')
child.expect('STEP_DONE')
child.sendline('apt-get install <programs> && echo STEP_DONE')
child.expect('STEP_DONE')
child.sendline('OTHER_CMDs')
```
while expect waits for update, it does not wait for apt-get install to completed and moves on to the other cmds immediately. While other cmds are being executed, install still tries to install the programs (this can be seen by the mixed output of install and other cmds and it moves to other cmds immediately, so it is visible that it does not install). It behaves as if apt-get install and echo STEP_DONE are executed at the same time. child.match shows STEP_DONE as well. 

Maybe I am missing something, but I couldn't solve this behavior.

**Comment by takluyver** [comment]
The terminal 'echoes' back the commands you send - if you were typing in an interactive terminal, this is how you see the text you're typing. So when you send `echo STEP_DONE`, the text `STEP_DONE` appears twice: once in the command and once in the output.

You can:

1. Turn this echoing off with `child.setecho(False)`
2. Fuzz the command a bit so the command itself doesn't match the pattern you're expecting, e.g.

        $ echo "STEP_${QQQ}DONE"
        STEP_DONE

**Comment by cihantunc** [comment]
setecho(False) did not help by itself but with the fuzzed pattern (additionally), it was solveed. 

Thanks a lot.
