### ISSUE TITLE
`yield from` is not adapt python2.7

### ISSUE THREAD

**Issue by zjjott** [pexpect/pexpect#384]
```
pexpect/async.py", line 16
        transport, pw = yield from asyncio.get_event_loop()\
                                 ^
    SyntaxError: invalid syntax
```

and `setup.py` say pexpect is adapt for python2.7,now when we use `pip install pexpect` or `pip install ipython==5.1.0` will raise this exception

**Comment by takluyver** [comment]
Old versions of pip will show you that error, but it has installed successfully anyway. New versions of pip will not show the error. That module is not used on Python 2, so you can safely ignore it.

To upgrade pip, run:

```
pip install --upgrade setuptools pip
```

**Comment by daotoulangzi** [comment]
thanks
