### ISSUE TITLE
pexpect with long stdout - maxread and searchwindowsize example

### ISSUE THREAD

**Issue by aavella77** [pexpect/pexpect#385]
Hi,

Environment:
pexpect (2.3)
python 2.7.5
centos 7

I am trying a pexpect script that throws large amounts of data to stdout.  I see that the display on the screen is very slow and takes more than 3 to 4 hours to come back with the prompt.  I have read the documentation but I cannot figure out how to configure the maxread and searhwindowsize parameters.  Are there examples on the Internet? or can someone provide them?  Is this a bug?

```
child = pexpect.spawn('ssh %s@%s' % (admin_username, mgmnt_ip), env = os.environ, maxread=100000000, searchwindowsize=2000)

cmd = 'python my-script.py -c config.json'  
if not cli.run_in_session(child,cmd,prompt,28800):
    assert 0, "%s command failed" % cmd 
```

Thanks,
Alejandro

**Comment by ohmkay** [comment]
I have the same problem.  As far as I can tell, your maxread parameter is setup correctly.  The default is 2000 characters.  I've used a large number like yourself, but it appears the maximum size of this parameter is 4092.  Not nearly enough for my usage and very disappointing.  I've read somewhere it may have something to do with the TTY settings but I have found no work arounds.

**Comment by MengJueM** [comment]
I also faced the same issue and am watching the good solutions.

**Comment by ryanpetrello** [comment]
@aavella77 @MengJueM I've written a PR that I think should drastically improve performance - mind giving it a shot?

https://github.com/takluyver

**Comment by takluyver** [comment]
Closing as #464 was merged. Let me know if performance is still problematic in this case with Pexpect >= 4.4 - we can reopen the issue if necessary.
