### ISSUE TITLE
Question about pexpect on Windows

### ISSUE THREAD

**Issue by poppyseedplehzr** [pexpect/pexpect#404]
Hello there!

My apologies if I'm posting in the wrong place, but I've been working to get pexpect working on Windows to try and support our integration tests for the osquery project.  The specific snippets of code I'm working to make cross platform [live on a branch I'm working on here](https://github.com/poppyseedplehzr/osquery/blob/win-integration-tests/tools/tests/test_base.py#L124), but I've been catching a slight snag with getting `PopenSpawn` to allow me to interact with the `osqueryi` process.

I've tried toying around with interfacing with our client as follows:
```
In [48]: osquery_proc = pexpect.popen_spawn.PopenSpawn(["C:\\Users\\Nicholas\\projects\\repos\\osquery\\build\\windows10\\osquery\\Release\\osqueryi.ex
    ...: e"])
    ...: PROMPT = u'osquery> '
    ...: CONTINUATION_PROMPT = u'    ...> '
    ...: ERROR_PREFIX = 'Error:'
    ...: proc.echo = False
    ...: osq = REPLWrapper(proc, PROMPT, None, continuation_prompt=CONTINUATION_PROMPT)
    ...:
                                                                                                                                                ---------------------------------------------------------------------------
TIMEOUT                                   Traceback (most recent call last)
<ipython-input-48-c1fbee283262> in <module>()
      4 ERROR_PREFIX = 'Error:'
      5 proc.echo = False
----> 6 osq = REPLWrapper(proc, PROMPT, None, continuation_prompt=CONTINUATION_PROMPT)

c:\tools\python2\lib\site-packages\pexpect\replwrap.pyc in __init__(self, cmd_or_spawn, orig_prompt, prompt_change, new_prompt, continuation_prompt, extra_init_cmd)
     53         self.continuation_prompt = continuation_prompt
     54
---> 55         self._expect_prompt()
     56
     57         if extra_init_cmd is not None:

c:\tools\python2\lib\site-packages\pexpect\replwrap.pyc in _expect_prompt(self, timeout)
     64     def _expect_prompt(self, timeout=-1):
     65         return self.child.expect_exact([self.prompt, self.continuation_prompt],
---> 66                                        timeout=timeout)
     67
     68     def run_command(self, command, timeout=-1):

c:\tools\python2\lib\site-packages\pexpect\spawnbase.pyc in expect_exact(self, pattern_list, timeout, searchwindowsize, async)
    388             return expect_async(exp, timeout)
    389         else:
--> 390             return exp.expect_loop(timeout)
    391
    392     def expect_loop(self, searcher, timeout=-1, searchwindowsize=-1):

c:\tools\python2\lib\site-packages\pexpect\expect.pyc in expect_loop(self, timeout)
    105             return self.eof(e)
    106         except TIMEOUT as e:
--> 107             return self.timeout(e)
    108         except:
    109             self.errored()

c:\tools\python2\lib\site-packages\pexpect\expect.pyc in timeout(self, err)
     68             if err is not None:
     69                 msg = str(err) + '\n' + msg
---> 70             raise TIMEOUT(msg)
     71
     72     def errored(self):

TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x0000000005101128>
searcher: searcher_string:
    0: "osquery> "
    1: "    ...> "
<pexpect.popen_spawn.PopenSpawn object at 0x0000000005101128>
searcher: searcher_string:
    0: "osquery> "
    1: "    ...> "
```
I've noticed that if I try and just start a `PopenSpawn` session with the `osqueryi` binary and `read`, all I get back is `''`. It seems like somewhere along the line I'm not getting back any of the spawning terminal messages? I'd truly rather not use wexpect or the others just to get this functality up and rolling, especially considering we're not looking to do anything more complicated than just interact with the osquery shell and daemon processes.

Lastly, I've been reading through all of y'alls docs, and I get the impression that I'm missing something trivial somewhere, as it seems that the basics of pexpect should be functioning on Windows. Any thoughts on how I could troubleshoot? I'm on a Windows 10 system but can jump on other builds if it's known to work on earlier releases.

**Comment by takluyver** [comment]
I went and had a quick look at osquery's source code (cool idea, by the way :-) ). As I suspected, you have code that checks `platformIsatty(stdin)` and switches behaviour.

When you use `PopenSpawn`, the standard streams are pipes, so any is-a-tty check will return False. There's some explanation of the difference from a Unix perspective here: http://ptyprocess.readthedocs.io/en/latest/#what-is-a-pty

The issue is that Windows does not provide something equivalent to Unix ptys. You can create console windows, hide them and copy text to and from them - that's what wexpect and winpexpect do - but it sounds fiddly and error prone, and I'm not interested in maintaining that in Pexpect. Or you can use a library called [winpty](https://github.com/rprichard/winpty) which aims to provide pty-like functionality in userspace, but I look at the instructions for compiling that and... no thanks.

So the 'basics' of Pexpect work in that you can send input to a subprocess and wait for output patterns. But what's missing is a way to make the subprocess think it's in an interactive console.

**Comment by poppyseedplehzr** [comment]
Ah got it thanks!

I think another issue I was having might've been related to using Powershell for all of my testing, in which case it seems that powershell might be doing some sort of blocking read/write on the std pipes? I'm going to keep investigating, but I really appreciate the rapid response, thanks!

**Comment by takluyver** [comment]
> I think another issue I was having might've been related to using Powershell for all of my testing, in which case it seems that powershell might be doing some sort of blocking read/write on the std pipes?

No ideas on that one
