### ISSUE TITLE
Redirect raw data from child's stdout to a local stdin process

### ISSUE THREAD

**Issue by ffatghub** [pexpect/pexpect#418]
Hi,

bear with me, I am new to pexpect and I am stuck with this. I want to capture traffic with tcpdump "two hops away" using this technique (https://wiki.wireshark.org/CaptureSetup/Pipes#Remote_Capture). The code look like this:

    opts = "-o CheckHostIP=no -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    child = pexpect.spawn("ssh " + opts + " -p 22 root@remote0")
    child.expect('assword: ')
    child.send('rootpassword\r')
    child.expect('# ')
    child.send('\r')
    # ssh again from remote0 to remote1
    child.send("ssh " + opts + " -p 22 -i /tmp/key user@remote1\r")
    child.expect('\$ ')
    child.send('sudo su - root\r')
    child.expect('# ')
    child.send('tcpdump -i eth0\r')

    for line in child:
        print(line)

This works fine, I can see traffic in/out eth0 at remote1 (as text emitted by tcpdump) on my local stdout.

Now I ask tcpdump to produce binary data to stdin (in pcap format) and I want to send these data to local stdout for farther processing, I mean like "rsniff.py | wireshark -k -i -". The modified code is

    opts = "-o CheckHostIP=no -o LogLevel=quiet -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    child = pexpect.spawn("ssh " + opts + " -p 22 root@remote0")
    child.expect('assword: ')
    child.send('rootpassword\r')
    child.expect('# ')
    child.send('\r')
    # ssh again from remote0 to remote1
    child.send("ssh " + opts + " -p 22 -i /tmp/key user@remote1\r")
    child.expect('\$ ')
    child.send('sudo su - root\r')
    child.expect('# ')
    child.send('tcpdump -i eth0 -w -\r')

    while True:
        data = child.read(1024)
        sys.stdout.buffer.write(data)

This is not working, wireshark says that the data received is not in pcap format. I know I am missing something big here about tty or encoding... but after several hours I decided to ask for help :-)

Any help would be much appreciated!

Thank you for the pexpect module!!!
ciao
fra

**Comment by ffatghub** [comment]
Hmm, coffee helped here, I see at least two problems now:

1)
When I read data from child I got both remote process stderr and stdout intermixed, this is a problem because tcpdump is a bit verbose on stderr and the result is a malformed pcap. **Is it possible to read only stdout from the child?**

2)
The tty echo breaks things. I got back what I sent and the prompt in case tcpdump exits. I tryied with 

    child.setecho(False)
    child.waitnoecho()
    child.send('tcpdump blabla\r')

but I still get the "tcpdump blabla" string back at child.read() time...

thank you
ciao
fra

**Comment by takluyver** [comment]
> Is it possible to read only stdout from the child?

Not from pexpect. When you run a subprocess in a pty, stdout and stderr are combined before the parent process gets to see them. You could redirect stderr to a file or a pipe so you're only reading stdout.

There may also be another issue - some programs produce different output (e.g. with colours for human consumption) when they're connected to a pty rather than a pipe. One hack to get the pipe data anyway is to pipe it through cat: `command | cat`.

> The tty echo breaks things. I got back what I sent and the prompt in case tcpdump exits.

`setecho()` turns off the local tty's echo, but I think that when you're connected to ssh, it is the server echoing characters back to you, and local echo is already turned off. You can control the terminal on the server with the `stty` command.

**Comment by ja-jquast** [comment]
I would suggest removing terminals from the picture entirely, you need only to Use ssh's built in ProxyCommand or ProxyJump options to "jump" via intermediary ssh hosts and use a single os.popen call.

untested pseudo-code, note use of '-S' argument to sudo to allow entering sudo password without a tty, this is the same technique packer.io uses, for example.
```
import subprocess
import sys
cmd_args = ['/bin/ssh', '-J', 'root@remote0', 'user@remote1', 'sudo -S tcpdump -i eth0 -w -']
with open('test.log', 'w') as f:
    process = subprocess.Popen(cmd_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    # write sudo password
    process.stdin.write('password')
    for c in iter(lambda: process.stdout.read(1), ''):
        sys.stdout.write(c)
        f.write(c)
```

https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#Jump_Hosts_--_Passing_Through_a_Gateway_or_Two
https://www.packer.io/docs/provisioners/shell.html#sudo-example

**Comment by ja-jquast** [comment]
you might also wish to filter out your ssh traffic, or your tcpdump will recursively record its own traffic.
`sudo tcpdump -i eth0 -w - port not ssh`

**Comment by ffatghub** [comment]
@takluyver 

Hi,

> You could redirect stderr to a file or a pipe so you're only reading stdout.

Silly me, '2>/dev/null' at the first (remote0) and second (remote1) host resolved this problem.

> One hack to get the pipe data anyway is to pipe it through cat: command | cat.

It seems tcpdump is not emitting any escape chars, thanks anyway I didn't know the 'cat' filtering trick.

> setecho() turns off the local tty's echo [cut]

Yep silly me again :-) The setecho() call is - obviously - disabling echo on tty at remote0, I guess I was receiving echo from remote1 tty. Sending 'stty -echo' to remote1 would fix this (I'll try next week). 

thanks a lot!
ciao
fra

**Comment by ffatghub** [comment]
@ja-jquast

Hi,

> I would suggest removing terminals from the picture entirely

the more I read about tty/pty (my understanding of this little beast was superficial and limited) the more I think you are right... I tried in "one shot" ssh+command(ssh +command(sudo tcpdump)) but sudo told me "Pseudo-terminal will not be allocated because stdin is not a terminal." I wasn't aware of the '-S' option!!! I'll give it a try.

> you need only to Use ssh's built ProxyCommand or ProxyJump options

I wasn't aware of these either. It seems the right way to go.

> you might also wish to filter out your ssh traffic, or your tcpdump will recursively record its own traffic.

I need to narrow down the filter including my own IP address (and the source port if I'll persuade ssh to bind to a fixed one) because I would like to capture other SSH traffic landing to remote1, thanks anyway

thanks a lot!
ciao
fra

**Comment by ffatghub** [comment]
Hi,

I managed to make it works by not allocating pty (-T option for ssh and -S for sudo) plus redirecting the stderr to /dev/null on remote0/remote1. An alternate solution in case sudo cannot be persuaded to not require a pty is to spawn 2 children: the 1st one - pty allocated - will tcpdump data to a named pipe or file on remote1, the 2nd one - no pty allocated - will transfer raw data from remote1 to local host.

thanks again for you support, much appreciated
ciao
fra
