### ISSUE TITLE
^] kills pexcept.spawn process

### ISSUE THREAD

**Issue by nateprewitt** [pexpect/pexpect#420]
We're currently experiencing an issue when using `pexpect.spawn` in combination with vim navigation characters. `^]` (`ctrl-]`) is used to [navigate tags](http://vimdoc.sourceforge.net/htmldoc/tagsrch.html) in vim but seems to be acting as an interrupt inside of `pexpect.spawn`. That means anytime the user tries to use the this command in vim, it immediately halts the `pexpect.spawn` process.

I haven't been able to find any documentation suggesting ^] is reserved for SIGINT or SIGHUP. Is there a specific reason this is implemented inside of pexpect? I can't seem to reproduce this behaviour in `subprocess` which I realize is slightly different.

Here's a simple repro:
```python
import pexpect

cmd = "sleep 500"

c = pexpect.spawn(cmd)
c.interact()
c.close()
```

Please let me know if I can provide any extra information, or if I'm missing something obvious. Thanks!

**Comment by takluyver** [comment]
It's the escape character for `interact()`. Docs: http://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.interact

**Comment by nateprewitt** [comment]
@takluyver thanks for pointing that out! Sorry for the noise.
