### ISSUE TITLE
use pexpect to scp "large" size file, we need to sleep to get the correct size of files?

### ISSUE THREAD

**Issue by yizephyr** [pexpect/pexpect#421]
I try to transfer files from the remote site to the local site by using:
```
tempChannel = pexpect.spawn('scp root@remote:/largeSizeFile /local_folder')
tempChannel.expect('assword:')
tempChannel.sendline(my_password)
```
If I do this without sleep, I will get a "blank" file, so I try to do:
```
tempChannel = pexpect.spawn('scp root@remote:/largeSizeFile /local_folder')
tempChannel.expect('assword:')
tempChannel.sendline(my_password)
time.sleep(1)
```
and it works well. Then I try to shorten the sleep time, say ```time.sleep(0.05)```
I will get "part" of the content of the file instead of intact file. 
Therefore, it looks like the sleep time does really matter in this case.
Do I wrongly use the function? or how do I solve this issue if I don't wanna freeze my runtime. 

btw, when I try 
```
pexpect.run('scp root@remote:/largeSizeFile /local_folder', events={"assword:", "my_password"})
```
it will freeze for a while and then finishes without correctly transferring.

Thanks!

**Comment by jnatschev** [comment]
have a look at an scp transfer natively. do you see the output of progress? if you do, then you could add, after tempChannel.sendline(my_password), something like this:
tempChannel.sendline(mypassword)
while true:
    pxresult = tempChannel.expect([’scp_progress_output_that_changes’, pexpect.EOF, pexpect.TIMEOUT], timeout=some_value)
    if pxresult == 0:
        continue
    elif pxresult == 1:
        spawn_complete(eof)_action
        break
    elif pxresult == 2:
        spawn_timeout_action
        break

This ought to ensure that pexpect doesn’t do anything else, like timeout, until the file is copied. It is difficult to know what timeout to set when doing a copy; especially if there is no change in copy output. scp, though, has progress displayed and some part of that progress changes. so in your tempChannel.expect() look for what changes and how regularly it changes. use the how regularly it changes as the timeout value + a bit more. in this manner you will never hit a pexpect.TIMEOUT and the copy will continue without pexpect failing.

well, that’s my ‘two bob’s worth’

john.

**Comment by yizephyr** [comment]
Thank you so much, John. This looks more appropriate usage of pexpect, and this definitely works to guarantee the session open. ;)

**Comment by jnatschev** [comment]
No worries, you’re welcome.

John.

**Comment by takluyver** [comment]
Thanks @jnatschev
