### ISSUE TITLE
relative import error

### ISSUE THREAD

**Issue by nvdeepa** [pexpect/pexpect#424]
I got the following and fixed it locally in site-packages by commenting out that line as the import was already at the top of the file:
_**..... pexpect/expect.py", line 82, in expect_loop
    from . import EOF, TIMEOUT
SystemError: Parent module 'pexpect' not loaded, cannot perform relative import**_

**Comment by takluyver** [comment]
That's weird, I don't recall ever seeing that error before. :-S I think your fix is fine, though, if you want to make a PR.
