### ISSUE TITLE
child.logfile=sys.stdout failed

### ISSUE THREAD

**Issue by icecooly** [pexpect/pexpect#437]
code:
  ```python
def login(self):
        command = 'ssh ' + self.host.user + '@' + self.host.host + ' -p ' + self.host.port
        child = pexpect.spawn(command)
        child.logfile=sys.stdout     #  when i use this line error happen
        ret = child.expect([pexpect.TIMEOUT, 'Are you sure you want to continue connecting', '[p]assword:'])
        if ret == 0:
            logError('[-] Error Connecting')
            return
        if ret == 1:
            child.sendline('yes')
            ret = child.expect([pexpect.TIMEOUT, '[p|P]assword'])
            if ret == 0:
                logError('[-] Error Connecting')
                return
            if ret == 1:
                self.sendCommand(child, self.host.password, X_PROMPT)
                return
        if ret == 2:
            self.sendCommand(child,self.host.password, X_PROMPT)
            child.interact()
            return
        return child
```

error:
Traceback (most recent call last):
  File "xssh", line 22, in <module>
    main()
  File "xssh", line 19, in main
    client.login()
  File "/Users/skydu/PycharmProjects/xtools/xtools/XClient.py", line 27, in login
    ret = child.expect([pexpect.TIMEOUT, 'Are you sure you want to continue connecting', '[p]assword:'])
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.6/site-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 465, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 163, in read_nonblocking
    self._log(s, 'read')
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 121, in _log
    self.logfile.write(s)
TypeError: write() argument must be str, not bytes

my env:
OS:MacBook Pro  10.12.6 macOs Sierra
Python: 3.6.1
Pexpect:4.2.1

**Comment by takluyver** [comment]
The logfile needs to match whether the `spawn` instance is handling bytes or unicode. By default, if you don't specify `encoding=`, it handles bytes.

In most circumstances, you should be able to set `child.logfile=sys.stdout.buffer` to send the bytes directly. That may not work if something is redirecting output at the Python level (like IDLE or Jupyter).

**Comment by icecooly** [comment]
$>scp Python-3.6.2.tgz appadmin@xxxxx:/tmp/  
the progress may show like this
Python-3.6.2.tgz                   14% 3200KB   3.1MB/s   00:05 ETA

but when i use pexpect call scp , the progress is invisible  why?

**Comment by karlp** [comment]
I'm having this with python3 and the fdspawner as well.

if I set encoding, I can use logfile=sys.stdout and I get decoded text, but I _cannot_ use a real logfile, (I get bytes/string mismatches)  if I _don't_ set the encoding, I can use a real logfile, but my text matches are now all bytes not unicode.

**Comment by karlp** [comment]
I worked this out eventually, it was a mix of python3'isms and file modes, below snippet works
```
	child = pexpect.fdpexpect.fdspawn(serial_port, encoding="us-ascii", codec_errors="ignore")
	if opts.logfile:
		fout = open(opts.logfile, "w", encoding="us-ascii")
		child.logfile = fout
	else:
		child.logfile = sys.stdout.buffer
```
