### ISSUE TITLE
Could you tell me the  How to support Windows

### ISSUE THREAD

**Issue by githublaohu** [pexpect/pexpect#440]
If inscribe

**Comment by takluyver** [comment]
http://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows

**Comment by andfoy** [comment]
I think it should be possible to use [pywinpty](https://github.com/spyder-ide/pywinpty) experimentally at least? @takluyver

**Comment by takluyver** [comment]
I haven't made any efforts to integrate pywinpty. I think it should be possible, but I don't really have the motivation to drive Pexpect development forwards. I'm no longer really using it myself, and the changes I've tried to make seem to have resulted in more bugs and confusion than actual improvements.

**Comment by githublaohu** [comment]
thank you，Has been tested。Thank you very much
