### ISSUE TITLE
Cannot block execution in signal handler

### ISSUE THREAD

**Issue by Chlorek** [pexpect/pexpect#448]
I made a script that utilizes spawn() interface. It works fine and blocks execution on expect(). I need however to interrupt standard flow to save something, then spawn process again when RTMIN signal is received and inside this signal's handler pexpect seems not to block at all. Tried to use wait() and it does not block either.
Some kind of collision in expect() is rather not the case, as my code leads to only one expect() at a time. So I guess it has something to do with code executed in signal handler itself?
```
proc = pexpect.spawn(command)
signal.signal(signal.SIGRTMIN+5, signal_save_buffer)
input('Press enter to stop.')
proc.sendcontrol('c')
print('Waiting for process to finish...')
proc.expect(pexpect.EOF)
print('Finished.')
```
The above works fine. And here is my signal handler:
```
def signal_save_buffer(sig, frame):
    global proc
    global command
    if proc != None:
        print('Waiting for process to finish before saving...')
        proc.expect(pexpect.EOF)
        # or wait() instead, same effect
        print('Process finished, copying...')
        # do copying here...
        proc = pexpect.spawn(command)
        print('Process restarted.')
    else:
        print('Process is not running.')
```
I posted this problem on stackoverflow, reddit and asked on IRC without any results, please help!

**Comment by jquast** [comment]
Glad you found the resolution, just wanted to thank you for trying other avenues of support before filing a bug. 

Have a great week!
