### ISSUE TITLE
Release Notes for 4.3.0?

### ISSUE THREAD

**Issue by lukas-gitl** [pexpect/pexpect#454]
Where do we find them?

**Comment by lukas-gitl** [comment]
Added now

**Comment by takluyver** [comment]
I don't tend to bother copying them onto Github (thanks @jquast for putting them there!), but in the docs they are at:

http://pexpect.readthedocs.io/en/latest/history.html

**Comment by lukas-gitl** [comment]
Yeah, this was right after the release. They appeared after an hour or so after the release.

**Comment by takluyver** [comment]
Ah, OK. It probably took a while for readthedocs to build and for the cache to clear.
