### ISSUE TITLE
pexpect.sendline() not always working

### ISSUE THREAD

**Issue by TomW28** [pexpect/pexpect#461]
I'm trying to run some Fortran code from Python 3.6.4 that requires three typed user inputs while running. I'm using pexpect to do this, and it's working as expected for the first two inputs. However the third time, when I use pexpect.sendline('0'), it seems to send a blank line which isn't much use as the program needs to receive '0' or '1'. This is the code I have:

       scattering = 0  # Defined in the function arguments

        v_turb = str(v_turb)
        scattering = str(scattering)
        model_name = str("MODELS/" + str(model_name))

        formal_integral_executable = str("./pformalsol_" + str(model_type) + ".eo")

        formal_integral = pexpect.spawn(formal_integral_executable)
        formal_integral.logfile_read = sys.stdout.buffer

        formal_integral.expect('FORMAL')
        formal_integral.sendline(model_name)

        formal_integral.expect("VTURB")
        formal_integral.sendline(v_turb)

        formal_integral.expect("IESCAT")
        formal_integral.sendline(scattering)

This is the output I get:

         GIVE IN CATALOGUE NAME FOR FORMAL CALC.
        MODELS/Testing
         GIVE IN VTURB. (KM/S)
        10.0
         GIVE IN IESCAT (=0, NO; = 1 WITH ESCAT)

        ... the rest of my script output ...

So it's correctly using sendline() to send the first two values, but sending a blank line for the third. I have tried using just `formal_integral.sendline('0')` and using `formal_integral.send('0')`. Both have identical results to the block of code above. I've also tried sending other strings that aren't '0' or '1', but no joy with them either, which I guess means that this particular calling of sendline() just isn't working.

Any ideas on if this is a problem with pexpect or is it to do with how I'm using it?

Thanks!

**Comment by takluyver** [comment]
You're not doing anything obviously wrong. The only difference between `sendline()` and `send()` is that the former adds a newline after the content. Both should return the number of bytes written, if that helps you investigate. It should wind up running lower level code like `os.write(formal_integral.child_fd, b'0\n')` .

One thing to try is sticking a short sleep in just before calling sendline. It shouldn't make a difference, but sometimes it does (probably depending on what the code you're running does).

**Comment by TomW28** [comment]
After a lot of just trying literally anything I could think of, I've solved it!

For that final `sendline()` to work, I needed another `expect()` after it. Once I set that to `child.expect(pexpect.EOF)` it works as I hoped.

**Comment by takluyver** [comment]
Ah, that makes sense. Without the expect call, pexpect won't be reading any data from the child process. If it produces more than a small amount of output, it will fill up a buffer and block waiting to write its output.
