### ISSUE TITLE
second call to spawn always hangs if SIGWINCH is handled

### ISSUE THREAD

**Issue by garfieldnate** [pexpect/pexpect#465]
The below program always hangs on the second call to `spawn()`:

    p = None
    def sigwinch_passthrough (sig, data):
        s = struct.pack("HHHH", 0, 0, 0, 0)
        a = struct.unpack('hhhh', fcntl.ioctl(sys.stdout.fileno(),
            termios.TIOCGWINSZ , s))
        global p
        p.setwinsize(a[0],a[1])

    def run_less():
        global p
        p = pexpect.spawn(f'/bin/bash -c "echo hello | less"')
        signal.signal(signal.SIGWINCH, sigwinch_passthrough)
        p.interact()
        p.wait()
        p.close(force=False)
        print(p.exitstatus, p.signalstatus) # prints '0 None'

    run_less()
    run_less() # hangs here

If you remove the SIGWINCH handler, then both calls run successfully. I'm not very familiar with the mechanics of how this happens, but the SIGWINCH handler is suggested in the documentation, which seems problematic in this case.

Using Python 3.6.

**Comment by takluyver** [comment]
If you Ctrl-C it, do you get a traceback showing where it was hanging?

**Comment by garfieldnate** [comment]
Yep:

    $ python3 test.py
    0 None
    ^CTraceback (most recent call last):
      File "test.py", line 21, in <module>
        run_less() # hangs here
      File "test.py", line 13, in run_less
        p = pexpect.spawn(f'/bin/bash -c "echo hello | less"')
      File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 197, in __init__
        self._spawn(command, args, preexec_fn, dimensions)
      File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 297, in _spawn
        cwd=self.cwd, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 308, in _spawnpty
        return ptyprocess.PtyProcess.spawn(args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 300, in spawn
        exec_err_data = os.read(exec_err_pipe_read, 4096)
    KeyboardInterrupt

**Comment by takluyver** [comment]
I think I've figured out what's going on. Internally, `spawn()` is actually forking the process, and then the child process execs the new command after forking. But in this case, something (not sure what) is firing SIGWINCH between the fork and the exec, so the child process receives it while it's still executing the Python code, and the handler attempts to pass through the SIGWINCH to the previous child process, which has already been closed. That causes it to fail in an unexpected way (although when I tried, I get exitstatus=1 rather than a hang).

The solution is either to restore the default signal handler before spawning the second process, so that it doesn't inherit the Python handler, or check inside the handler that `p.ptyproc.fd > 0` before calling `setwinsize()`.

**Comment by takluyver** [comment]
#466 should improve that example.

**Comment by garfieldnate** [comment]
Hmm, I pulled your PR branch locally and installed it, but the original example script still hangs even after adding the `if not p.closed` line before the `setwinsize` call. The stack trace I get when CTRL-C'ing is almost the same; the line numbers are just a bit different:

    ^CTraceback (most recent call last):
      File "test.py", line 21, in <module>
        run_less() # hangs here
      File "test.py", line 13, in run_less
        p = pexpect.spawn(f'/bin/bash -c "echo hello | less"')
      File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 198, in __init__
        self._spawn(command, args, preexec_fn, dimensions)
      File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 298, in _spawn
        cwd=self.cwd, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 309, in _spawnpty
        return ptyprocess.PtyProcess.spawn(args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/ptyprocess/ptyprocess.py", line 302, in spawn
        exec_err_data = os.read(exec_err_pipe_read, 4096)
    KeyboardInterrupt

**Comment by takluyver** [comment]
In that case, try resetting the default signal handler before spawning a second process.

For me, the changes in the PR took it from spawn 2 exiting with an error, to both spawns working as expected.

**Comment by garfieldnate** [comment]
What do you mean by resetting it? I tried assigning it again with `signal.signal(signal.SIGWINCH, sigwinch_passthrough)` between the two spawn calls and it still hung.

**Comment by takluyver** [comment]
No, I mean assign it back to the default value:

```python
signal.signal(signal.SIGWINCH, signal.SIG_DFL)
```

**Comment by garfieldnate** [comment]
That definitely works. But that means that the solution is to not use the handler, right?

**Comment by takluyver** [comment]
No, you can still use the handler, it just has to not be set when the process forks:

```python
signal.signal(signal.SIGWINCH, signal.SIG_DFL)
p = pexpect.spawn(f'/bin/bash -c "echo hello | less"')
signal.signal(signal.SIGWINCH, sigwinch_passthrough)
```

**Comment by garfieldnate** [comment]
Okay. That makes sense, and it's all working now.

**Comment by takluyver** [comment]
Great. I'm still not sure why it hung for you, or if there's anything else we can do in pexpect to mitigate it.
