### ISSUE TITLE
select.select() cannot handle more than 1024 open files

### ISSUE THREAD

**Issue by rediate** [pexpect/pexpect#47]
I have been using pexpect for many months with no problem. However, I recently this line:

1680     return select.select(iwtd, owtd, ewtd, timeout)

Has been creating a few problems. The select system call cannot handle more than 1024 file descriptors. On the other hand, the select.poll() system call does not have such limitations. 

I understand that not all platforms support poll() but it would be nice to incorporate this system call as an option.

**Comment by sagarinpursue** [comment]
even i am facing the same issue with file descriptor, i do not want to use anything other than select as there are lot of dependency. if there are any work around for the same please help.

**Comment by shoyer** [comment]
This bit me today.

I'm happy to give this a shot, but I don't have idea what sort of conservative platform checks would be appropriate. Can anyone suggest some minimal checks?

Presumably we could get this info from the `platform` module:
https://docs.python.org/2/library/platform.html

**Comment by cooperlees** [comment]
@shoyer + others - Did anyone get a patch somewhere for this? Otherwise I want to look at implementing a refactor to allow Linux to use select.poll() and fallback to select.select() for other platforms to maintain compatibility.

Can I also assume (if I do the PR) that we will be >= Python 2.7? TravisCI only does this. So I assume so.

**Comment by takluyver** [comment]
We're definitely not trying to support anything older than Python 2.7. But I'm now quite wary of making non-trivial changes to Pexpect. There's so much old code out there using it, and I've already accidentally broken things with changes I thought would be fine.

I think it would be better for someone to make a new library that can do similar tasks to Pexpect but isn't bound to follow its API. In particular, if I was building something like this today, I would try to use the [Sans-I/O paradigm](http://sans-io.readthedocs.io/), to separate the pattern searching that's the core of what Pexpect does from dealing with I/O.

**Comment by shoyer** [comment]
I ended up writing a patch which worked for my case, but I didn't test it extensively or add any platform detection logic. That said, in case it's helpful please see https://github.com/pexpect/pexpect/pull/470. I don't plan to finish this, but it would be great if someone else took it up.

**Comment by cooperlees** [comment]
The main problem I have and want to solve here is when other third party modules want `pexpect`. My example is when something we've written uses a fork such as `pexpect-u`, that drops itself in as `pexpect` to be an easy drop in replacement. `ipython` is one module that wants `pexpect` and we offer building ipython debug modules for people and thus hit a name collision here if they also include the fork.

I think very carefully inserting a config driven selection or platform dependent selection maintaining the behavior we have today as default is very doable. This should ensure very little breakage. That said, which way would people prefer and more likely accept?
- Add epoll and turn it on via parameter / config
- Try extend select and fall back to current behavior if the new way fails

Other ideas?

**Comment by takluyver** [comment]
I'd probably favour having to explicitly enable the new behaviour, because I suspect it might be hard to capture all the ways it could fail on different platforms (e.g. maybe it accepts the fd but just never says it's ready).

I'm also an IPython maintainer - for IPython we'd probably be willing to take slightly more risks with the default. I tend to keep a very conservative policy with Pexpect.

**Comment by cooperlees** [comment]
Have put up https://github.com/pexpect/pexpect/pull/474 to address this issue.

**Comment by cooperlees** [comment]
What's the plan on releasing 4.5.0 now we're all merged?
- Anything I can help with?

**Comment by takluyver** [comment]
If you could tackle the issue with interact() and poll (see my comment on #474), I think everything else is ready.

**Comment by takluyver** [comment]
To summarise the resolution: as of Pexpect 4.5, you can pass `spawn(..., use_poll=True)` if you need it to work with file descriptors above 1024.

I know it may be annoying that it's not the default, but I'm (now) very wary of compatibility for Pexpect. It's been used on some less popular platforms which I'm not familiar with, and it works with ptys, which are fairly odd objects in themselves. So the default is to stick to what it's been doing for a long time.
