### ISSUE TITLE
Mulitple ssh on pexpect/pxssh?

### ISSUE THREAD

**Issue by darath2000** [pexpect/pexpect#471]
Is there a way to do multiple ssh in pexpect or pxssh?
What I'm trying to do was to ssh to a server and then from that server ssh to another server.
**ssh server1 -> do some commands -> ssh server2 -> do some commands.**

**Comment by takluyver** [comment]
I don't think pxssh has any direct support for that; you'd have to send the second ssh command in and expect and respond to the subsequent prompts.

**Comment by Red-M** [comment]
Calling login again with the second host's hostname should work with my patch in PR #472

**Comment by Red-M** [comment]
Sorry, I forgot to mention, you'll need to pass spawn_local_ssh=False on any subsequent ssh connections.

**Comment by Red-M** [comment]
I've merged this in with #473

**Comment by Red-M** [comment]
I'll close this issue now but reply back if you have issues with the feature in #473
