### ISSUE TITLE
pexpect.which() is matching against directories

### ISSUE THREAD

**Issue by haridsv** [pexpect/pexpect#487]
I have two entries in `PATH`, `~/bin` followed by `~/bin/python/bin` (a virtualenv). When I call `pexpect.which("python")`, I get `~/bin/python` as the result, which is a directory. The expected result should have been `~/bin/python/bin/python`.

**Comment by jnatschev** [comment]
What is the version of pexpect and version of python?

I have pexpect 4.5.0 running in both a pyenv python 2.7.14 and pyenv python 3.6.5 on macos 10.13.4 and I am not getting the behaviour you are describing. In fact, I have tried a couple of manipulations to replicate the behaviour you describe and pexpect.which(‘python’) always returns the expected output.




Cheers,
John Natschev
‌

**Comment by haridsv** [comment]
I am using pexpect 4.5.0 as well with Python 2.7.6 on Ubuntu 14.04. However, I just tried to reproduce it on a standalone environment and it didn't happen:

```
$ virtualenv --never-download /tmp/python
$ PATH=/tmp:/tmp/python/bin:$PATH
$ pip -q install pexpect==4.5.0
$ python -c 'import pexpect; print pexpect.which("python")'
/tmp/python/bin/python
```

In the environment where I encountered it, I had to modify `PATH` so that the virtualenv came first to get around this issue, so I am not sure what is different about it. Let me look into it deeper.

**Comment by Red-M** [comment]
I'd reinstall pexpect as it sounds like it has been chagnged as per the following lines which make it unable to match anything but files (and symblinks to files).
https://github.com/pexpect/pexpect/blob/3bc1314f978568434d9d030c428395f754aef0ad/pexpect/utils.py#L64
https://github.com/pexpect/pexpect/blob/3bc1314f978568434d9d030c428395f754aef0ad/pexpect/utils.py#L28

**Comment by haridsv** [comment]
@Red-M I don't think it is as straight-forward. I actually have this change:

```
$ cat -n ~/bin/python/lib/python2.7/site-packages/pexpect/utils.py | head -40
     1  import os
     2  import sys
     3  import stat
     4  import select
     5  import time
     6  import errno
     7
     8  try:
     9      InterruptedError
    10  except NameError:
    11      # Alias Python2 exception to Python3
    12      InterruptedError = select.error
    13
    14  if sys.version_info[0] >= 3:
    15      string_types = (str,)
    16  else:
    17      string_types = (unicode, str)
    18
    19
    20  def is_executable_file(path):
    21      """Checks that path is an executable regular file, or a symlink towards one.
    22
    23      This is roughly ``os.path isfile(path) and os.access(path, os.X_OK)``.
    24      """
    25      # follow symlinks,
    26      fpath = os.path.realpath(path)
    27
    28      if not os.path.isfile(fpath):
    29          # non-files (directories, fifo, etc.)
    30          return False
```

Since I first encountered the issue when I was running pexpect via nose, I did the below test and it reproduced:

```
$ cat >/tmp/test.py
import unittest
import pexpect

class Test(unittest.TestCase):
    def test(self):
        self.assertEquals(pexpect.which("python"), "/tmp/python/bin/python")
$ PATH=/tmp:/tmp/python/bin:$PATH nosetests -s -v /tmp/test.py
test (test.Test) ... FAIL

======================================================================
FAIL: test (test.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test.py", line 6, in test
    self.assertEquals(pexpect.which("python"), "/tmp/python/bin/python")
AssertionError: '/tmp/python' != '/tmp/python/bin/python'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```

I am not sure why it behaves differently here.

**Comment by Red-M** [comment]
I'd print your environ with `os.environ` and also confirm that noses isn't super old.

**Comment by takluyver** [comment]
Also `print(pexpect)` to see where it's loaded from - it might be finding an old version somewhere else.

**Comment by haridsv** [comment]
@takluyver Perfect! I didn't install nose into the virtualenv, so it ended up running from system which caused `pexpects` loaded from system too that has 3.1 version installed. Once I installed nose into my virtualenv, the problem went away.
