### ISSUE TITLE
How to use .login with a ssh key?

### ISSUE THREAD

**Issue by kw-andy** [pexpect/pexpect#489]
I'm trying to connect to a ssh server on which I have set a public key.

I have my private keys on the folder ` /home/XXX/priv_keys` but I'm not sure on how to use it with the `login` module.

The doc gives me this 

```
Set ssh_key to True to force passing the current SSH authentication socket to the to the desired hostname.
```

But eventually, pexpect still ask me for the password, which is deactivated on my distant server.

This is the code I've tried

```
from pexpect import pxssh
import getpass
try:
    s = pxssh.pxssh()
    hostname = '1xx.138.12.xx'
    username = 'and_wk'
    s.login(hostname, username, '/home/XXX/priv_keys', True) # the path with the private keys has been used instead of the password and the ssh_key has been set to True  
    s.sendline('uptime')   # run a command
    s.prompt()             # match the prompt
    print(s.before.decode())        # print everything before the prompt.](url)
```

Thanks in advance for any help

**Comment by Red-M** [comment]
That option is for the socket not a key.
To use the option load a key into a socket based ssh key agent and either:

- Run the script from a bash line with said socket agent active
- Pass the socket agent to pxssh via the ssh options.

An example would be:
On your bash command line:
```
ssh-add <ssh key path>
./pxssh_script.py
```
or loading the agent from another session under the same user within pxssh:
bash command line:
```
ssh-add <ssh key path>
echo $SSH_AUTH_SOCK
```
Echo'd line is the path to the socket of that instance of the ssh key agent.
Python:
```python
from pexpect import pxssh
import getpass
try:
    ssh_options = {'IdentityAgent': '<agent path>'}
    s = pxssh.pxssh(options=ssh_options)
    hostname = '1xx.138.12.xx'
    username = 'and_wk'
    s.login(hostname, username)
    s.sendline('uptime')   # run a command
    s.prompt()             # match the prompt
    print(s.before.decode())        # print everything before the prompt.](url)
```


With all the said above you wouldn't need to load in your SSH key so instead:
```python
s.login(hostname, username)
```

**Comment by Red-M** [comment]
To answer with something that could help you rather than explain docs.
Can you confirm that you can login to the remote machine with said key and that the remote side has ~/.ssh set to the correct permissions?

Another common issue is that the SSH server does not have keys set up correctly in the terms that the server is looking for the keys in the wrong place or its not configured to look for keys.

**Comment by kw-andy** [comment]
Hi Red,

OMG.

I learnt something new. Thank you for your precious help.

It worked a treat!

Thank you very much.

Cheers

**Comment by kw-andy** [comment]
Hi Red,

Thanks for your help.

I managed to run my python script.

However, I'm still have a few questions:

1) You said that for the part below I need to be connected to the `same agent from another session under the same user within pxssh:`

You used the code below for that.

```python
from pexpect import pxssh
import getpass
try:
    ssh_options = {'IdentityAgent': '<agent path>'}
    s = pxssh.pxssh(options=ssh_options)
    hostname = '1xx.138.12.xx'
    username = 'and_wk'
    s.login(hostname, username)
    s.sendline('uptime')   # run a command
    s.prompt()             # match the prompt
    print(s.before.decode())        # print everything before the prompt.](url)
```
How do you do that?

2) ssh-agent did what I need to connect my python script.

Is there not a function/else in pexpect to do the same thing as the ssh-agent ?

I feel a bit awkward to run a bash script then the python script instead of having python to do the job for everything.

Thank you for your answers.

**Comment by Red-M** [comment]
1. An agent from the same user but in another tty or pty. Not the same agent.
2. Annoyingly I thought this was already in the docs however I shall have to add this, pass a sting to `ssh_key` and make sure the string is a path to a private key file. eg,
```python
s.login(hostname, username, ssh_key='/home/XXX/priv_keys')
```
previously you would have been sending the key as a password and setting the `terminal_type` to `True`.

**Comment by Red-M** [comment]
`$SSH_AUTH_SOCK` is the `IdentityAgent` that is passed normally to ssh if that variable exists in the environment. This is what you would replace in my example as `<agent path>`

pexpect is only passing the agent to ssh here, as what is would normally happen.
You can only connect to an IdentityAgent if it is your own user's agent socket, otherwise your OS will tell you that you don't have permission to access said socket.

**Comment by kw-andy** [comment]
Thanks. I got yout last point. Cheers for your help.
