### ISSUE TITLE
Pxssh and expect patterns

### ISSUE THREAD

**Issue by 123troy** [pexpect/pexpect#495]
We have tried pexpect, but we have found pxssh to work better is our situation, but we are hitting a wall at one part.

I am trying to connect to multiple versions of Cisco devices.  Some I have to enable, some use a '>' as a prompt and others just go to the '#' prompt.  Is there a way that we can create a expect pattern with pxssh as we can with pexpect?

I would prefer to have one script running rather than having to specify which script to use with which host.

Thank you

**Comment by jnatschev** [comment]
Hi.

I’m not a pexpect guru, however you will more than likely have a couple of ways to do it.

1.
when you create a pxssh instance:
    from pexpect import pxssh
    my_pxssh = pxssh.pxssh()
    my_pxssh.PROMPT = r'\S+>$|\S+> $|\S+#$|\S+# $’
    my_pxssh.login(‘ip_address/hostname’, ‘username’, password=’the_password’, auto_prompt_reset=False)
    my_pxssh.prompt()    # this ought to test for the prompt of the system logged into based on my_pxxsh.PROMPT
    my_pxssh.sendline(‘command’)
    my_pxssh.prompt()
    …
    
    With this way, I am uncertain how TIMEOUT and EOF are catered for. You may need to play around with it a little.

2.
when you create a pxssh instance:
    from pexpect import pxssh
    from pexpect import TIMEOUT as pxTIMEOUT
    from pexpect import EOF as pxEOF
    my_pxssh = pxssh.pxssh()
    my_pxssh.login(‘ip_address/hostname’, ‘username’, password=’the_password’, auto_prompt_reset=False)
    mypxsshexpect_result = my_pxssh.expect([r’what’, ‘prompts’, ‘to’, ‘expect’, ‘as’, ‘a’, 'list’, pxTIMEOUT, pxEOF])
    if mypxsshexpect_result == 0:
        do something
    elif mypxsshexpect_result == 1:
        do something
    elif mypxsshexpect_result == 2:
        do something
    so on and so on until all the elements of the list were catered for.
    
Hope this helps.


Cheers,
John Natschev

**Comment by 123troy** [comment]
I have these four example router prompts
routerA#
rp/0/rps0/cpu0:routerB#
routerC> (enable)
routerD>

Given the code listed below I get the following results:
routerA# <- Does not work
rp/0/rps0/cpu0:routerB# <- Does not work
routerC> (enable) <- goes to index #2
routerD> <- works
 

for router in routeServers:
  router = router.strip()
  print('####connecting to####', router)
    s = pxssh.pxssh()
    s.login(router,'username','password',auto_prompt_reset=False)
    pattern_index = s.expect(["#", "enable", ">"])
    if pattern_index == 0:
      print("Index 0")
      do this
    elif pattern_index == 1:
      print("Index 2")
      do that
    elif pattern_index == 2:
      print("Index 2")
      do something
 
Those that do not work get the following stacktrace in debug mode:
-> pattern_index = s.expect(["#", "enable", ">"])
(Pdb)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pxssh.pxssh object at 0x7f2303161e10>
command: /bin/ssh
args: ['/bin/ssh', '-q', '-l', 'username', 'router']
buffer (last 100 chars): b' '
before (last 100 chars): b' '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 102814
child_fd: 7
closed: False
timeout: 30  ########## This is more than enough time to connect.
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'#'")
    1: re.compile("b'enable'")
    2: re.compile("b'>'")

**Comment by jnatschev** [comment]
Hi.

Using which of the two options: Option 1 or Option 2?

With you example, “s.expect([“#”, “enable”, “>”])”, you ought to include in the list elements for pexpect.TIMEOUT and pexpec.EOF. It is very hand to capture these circumstances because you can do something “nicely” (like print a message that a TIMEOUT waiting for one of the expect patterns or EOF, meaning that the ssh session was lost) rather than the exception being triggered (which is what is exemplified through the text: "pexpect.exceptions.TIMEOUT: Timeout exceeded.”.

From your list of prompts what is needed to be known is whether there is a space between the last character of the prompt and the cursor, or not. At the end of the day, it is all about determining the regular expression that matches each of the prompts. That could take a bit of research.

So, for each prompt you could potentially try something like:
from pexpect import pxssh
from pexpect import TIMEOUT as pxTIMEOUT
from pexpect import EOF as pxEOF
s = pxssh.pxssh()
s.login(device, username, password, original_prompt="\S+#$|\S+# $|\(\S+\)$|\(\S+\) $|\S+>$|\S+> $”, auto_prompt_reset=False)

# result of s.login ought to be True
# interactively, here you can s.before and s.after
# s.after ought to contain the whole prompt of a part of the prompt that matches the original_prompt patterns

s.sendline(‘some command’)
expect_pattern_index = child.expect([r’\S+#$’, r’\S+# $’, r’\(\S+\)$’, r’\(\S+\) $’, r’\S+>$’, r’\S+> $’, pxTIMEOUT, pxEOF])
if expect_pattern_index == 0:
    # ought to match routerA or routerB dependant on whether there is a space between “#” and the cursor
elif expect_pattern_index == 1:
    # ought to match routerA or routerB dependant on whether there is a space between “#” and the cursor
elif expect_pattern_index == 2:
    # ought to match routerC dependant on whether there is a space between “)” and the cursor
elif expect_pattern_index == 3:
    # ought to match routerC dependant on whether there is a space between “)” and the cursor
elif expect_pattern_index == 4:
    # ought to match routerD dependant on whether there is a space between “>” and the cursor
elif expect_pattern_index == 5:
    # ought to match routerD dependant on whether there is a space between “>” and the cursor
elif expect_pattern_index == 6:
    # pexpect.TIMEOUT matched. None of the previous list elements (regular expressions for matching prompts) matched.
    # so you can do something that doesn’t raise an exception, like terminate your program gracefully.
elif expect_pattern_index == 7:
    # pexpect.EOF matched. This basically means that the ssh session terminated for some reason.
    # so you can do something that doesn’t raise an exception, like terminate your program gracefully.

Keep in mind, that s.before and s.after are very useful in helping work out what is going on so you can write your program so that it is more resilient and behaves as you would if you were using your ssh session interactively.



Cheers,
John

**Comment by 123troy** [comment]
I am using option #2 but using a try/except for my error catching.  

When I modify the script to run against my 4 testing router,  those with the ) or > work perfectly now.  Thank you for this.

However,  I am still getting errors for the routers with the #.  Using the s.before and the s.after I can see that it is capturing the prompt but for some reason it looks like it is skipping the if statements.

I have attached my script and pasted the debug below.
[pxssh.txt](https://github.com/pexpect/pexpect/files/2054904/pxssh.txt)

> directory/test_items/pxssh_test.py(21)<module>()
-> for router in routeServers:
(Pdb) n
> directory/test_items/pxssh_test.py(22)<module>()
-> router = router.strip()
(Pdb)
> directory/test_items/pxssh_test.py(23)<module>()
-> print('####connecting to####', router)
(Pdb)
####connecting to#### routerA
> directory/test_items/pxssh_test.py(24)<module>()
-> for i in range(max_retries):
(Pdb)
> directory/test_items/pxssh_test.py(25)<module>()
-> try:
(Pdb)
> directory/test_items/pxssh_test.py(26)<module>()
-> s = pxssh.pxssh()
(Pdb)
> directory/test_items/pxssh_test.py(27)<module>()
-> s.login(router,'username','password', original_prompt="\S+#$|\S+# $|\(\S+\)$|\(\S+\) $|\S+>$|\S+> $", auto_prompt_reset=False)
(Pdb)
> directory/test_items/pxssh_test.py(28)<module>()
-> print(s.after)
(Pdb)
b'routerA# '
> directory/test_items/pxssh_test.py(30)<module>()
-> pattern_index = s.expect([r'\S+#$', r'\S+# $', r'\S+> ', r'\S+>$'])
(Pdb)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pxssh.pxssh object at 0x7f9f19f8efd0>
command: /bin/ssh
args: ['/bin/ssh', '-q', '-l', 'intelliden', 'routerA']
buffer (last 100 chars): b''
 
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 42618
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'\\S+#$'")
    1: re.compile("b'\\S+# $'")
    2: re.compile("b'\\S+> '")
    3: re.compile("b'\\S+>$'")
> directory/test_items/pxssh_test.py(30)<module>()
-> pattern_index = s.expect([r'\S+#$', r'\S+# $', r'\S+> ', r'\S+>$'])
(Pdb)
> directory/test_items/pxssh_test.py(106)<module>()
-> except pexpect.EOF:
(Pdb)
> directory/test_items/pxssh_test.py(113)<module>()
-> except pexpect.TIMEOUT:
(Pdb)

**Comment by jnatschev** [comment]
Hey.

Nice that you have “(enable)” and “>” prompts working. Sad about “#” prompts not working. Strange.

The only thing I can think of, now, is remove “$” character from the pattern string. The “$” symbol denotes end-of-line. Maybe there is something about the prompt that is a bit strange.

Oh, actually, before you remove the “$” character from the pattern string, are you able to send me what s.before contains?

s.after contains pexpect.exceptions.TIMEOUT and ought to contain the prompt string based on the regular expression pattern match for a prompt. s.before will contain the string that you ought to be matching on. s.before, in this instance, will give us a better idea of what you ought to be matching on.



Cheers,
John Natschev

**Comment by Red-M** [comment]
I'd look into how to write regexes and setting `pxssh.pxssh().PROMPT`. You
can write a regex that matches all the prompts you're looking for.

**Comment by jnatschev** [comment]
Yeah, that’s what i had originally suggested. One question about it as I am not a pexpect guru: how can pexpect.TIMEOUT and pexpect.EOF be added to pxssh.pxssh().PROMPT?



Cheers,
John Natschev

**Comment by Red-M** [comment]
You don't need to, those are already conditions of calling for a prompt or anything expected.

**Comment by jnatschev** [comment]
Right? So how would i test for the conditions pexpect.TIMEOUT and pexpect.EOF?



Cheers,
John Natschev

**Comment by Red-M** [comment]
They'll get raised as errors.

**Comment by jnatschev** [comment]
Ah, right. Got it. Thanks, much appreciated.



Cheers,
John Natschev

**Comment by 123troy** [comment]
Hi John,

Here are the s.before and the s.after output even after I remove the $ (I get the same result with the $).

-> s.login(router,'username','password', original_prompt="\S+#|\S+# |\(\S+\)$|\(\S+\) $|\S+>$|\S+> $", auto_prompt_reset=False)
(Pdb)
> directory/pxssh_test.py(28)<module>()
-> print(s.before)
(Pdb)
b' \r\nCisco Nexus Operating System (NX-OS) Software\r\nTAC support: http://www.cisco.com/tac\r\nCopyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.\r\nThe copyrights to certain works contained in this software are\r\nowned by other third parties and used and distributed under\r\nlicense. Certain components of this software are licensed under\r\nthe GNU General Public License (GPL) version 2.0 or the GNU\r\nLesser General Public License (LGPL) Version 2.1. A copy of each\r\nsuch license is available at\r\nhttp://www.opensource.org/licenses/gpl-2.0.php and\r\nhttp://www.opensource.org/licenses/lgpl-2.1.php\r\n\r'
> directory/pxssh_test.py(29)<module>()
-> print(s.after)
(Pdb)
b'routerA#'
> directory/pxssh_test.py(31)<module>()
-> pattern_index = s.expect([r'\S+#', r'\S+# ', r'\S+> ', r'\S+>$'])
(Pdb)
 
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pxssh.pxssh object at 0x7f8a6bfdffd0>
command: /bin/ssh
args: ['/bin/ssh', '-q', '-l', 'intelliden', routerA']
buffer (last 100 chars): b' '
before (last 100 chars): b' '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 108674
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'\\S+#'")
    1: re.compile("b'\\S+# '")
    2: re.compile("b'\\S+> '")
    3: re.compile("b'\\S+>$'")


To take a step back, I chose option #2 because of what we are trying to do.  We have hundreds of devices that we need to connect to and get data from (these 4 represent the most common prompt types) and the commands that we need to run are based on the prompt.  

Unfortunately, this is a situation where we do not know what the prompt is until we log in and why I need to break out based on the prompt.  We have tried pexpect and the spawn and work fairly well, but some devices have a # in output as well as a # for the prompt, which causes errors in the ultimate output.

Thanks,
Troy

**Comment by Red-M** [comment]
Don't set original prompt.
Try this instead.
```python
s.PROMPT = "\S+#|\S+# |(\S+)$|(\S+) $|\S+>$|\S+> $"
s.login(router,'username','password', auto_prompt_reset=False)
```

If you are continuing to have issues with this I'd look at the outputs you're getting in a regex tester along with your `s.PROMPT` value and tweaking it so that it is only ever going to match a prompt and not text.

A good way to do that is using both `^` and `$` for your regex.

**Comment by 123troy** [comment]
I will give the s.PROMPT a shot when I return to the office.  

In the meantime, I will need to use the expect as "#", ">", and "> (enable)"  (the three prompts I am looking for) all require different sets of commands that are ran against them.

**Comment by Red-M** [comment]
With pxssh, do not use `.expect()`.

You should be using the library like this:
```python
from pexpect import pxssh
import getpass
try:
    s = pxssh.pxssh()
    hostname = raw_input('hostname: ')
    username = raw_input('username: ')
    password = getpass.getpass('password: ')
    s.login(hostname, username, password)
    s.sendline('uptime')   # run a command
    s.prompt()             # match the prompt
    print(s.before)        # print everything before the prompt.
    s.sendline('ls -l')
    s.prompt()
    print(s.before)
    s.sendline('df')
    s.prompt()
    print(s.before)
    s.logout()
except pxssh.ExceptionPxssh as e:
    print("pxssh failed on login.")
    print(e)
```
If you want to mess with the prompt to get it going with other devices this is what you'd use:
```python
from pexpect import pxssh
import getpass
try:
    s = pxssh.pxssh()
    s.PROMPT = "\S+#|\S+# |(\S+)$|(\S+) $|\S+>$|\S+> $"
    hostname = raw_input('hostname: ')
    username = raw_input('username: ')
    password = getpass.getpass('password: ')
    s.login(hostname, username, password, auto_prompt_reset=False)
    s.sendline('uptime')   # run a command
    s.prompt()             # match the prompt
    print(s.before)        # print everything before the prompt.
    s.sendline('ls -l')
    s.prompt()
    print(s.before)
    s.sendline('df')
    s.prompt()
    print(s.before)
    s.logout()
except pxssh.ExceptionPxssh as e:
    print("pxssh failed on login.")
    print(e)
```

**Comment by 123troy** [comment]
Thank you John and Red for all of your help.  I found that I also needed a sendline() belore the pattern_index to make it all work.

`      s = pxssh.pxssh()
      s.PROMPT = "\S+#|\S+# |(\S+)$|(\S+) $|\S+>$|\S+> $"
      s.login(router,'username','password', auto_prompt_reset=False)
      s.sendline()
      pattern_index = s.expect([r'\S+#$', r'\S+# $', r'\S+> ', r'\S+>$'])
      if pattern_index == 0 or pattern_index == 1:`

Thank you again for your help.

Troy

**Comment by jnatschev** [comment]
Yep. that will do it. whatever the command is, it needs the “Return”/“Enter” key at the end. Good work.



Cheers,
John Natschev
