### ISSUE TITLE
Timeout on extremely large files

### ISSUE THREAD

**Issue by 123troy** [pexpect/pexpect#496]
Hello,

I am trying to do a cat on a file with 750,000 lines in it.  I have maxread set to 1,000,000 and the timeout set to 5 minutes.  However my script is timing out before this and only getting about 250,000 lines of it.

Any thoughts?

Error
----------------------------------------------------------------
ppexpect.exceptions.TIMEOUT: <pexpect.pty_spawn.spawn object at 0x7f3898bb1cc0>
command: /bin/ssh
args: ['/bin/ssh', 'username@firewall1']
buffer (last 100 chars): b'\n\t\t\t\t\t:dual_wan (false)\r\n\t\t\t\t\t:officialname (Vlan1001)\r\n\t\t\t\t\t:monitored_by_cluster (false)\r\n\t\t\t\t\t:an'
before (last 100 chars): b'\n\t\t\t\t\t:dual_wan (false)\r\n\t\t\t\t\t:officialname (Vlan1001)\r\n\t\t\t\t\t:monitored_by_cluster (false)\r\n\t\t\t\t\t:an'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 24005
child_fd: 7
closed: False
timeout: 300
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.BufferedWriter name='/opt/pexpext/output/firewall1.data'>
logfile_read: None
logfile_send: None
maxread: 1000000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("b'\\S+]#'")

Code
--------------------------------------------------------

```python
#!/usr/local/bin/python3
#Using python 3.6.4 at the time of creation - 02/26/2018
 
import sys
import pexpect
from pexpect import pxssh
import time
import subprocess
import pdb
 
username = 'username'
password = 'password'
 
CWD = '/opt/pexpext'
BIN = CWD+'/bin'
DATA = CWD+'/data/firewall.commands'
TMP = CWD+'/tmp/test.hosts'
 
max_retries = 3
 
routerFile = open(TMP,'r')
routeServers = [i for i in routerFile]
commandFile = open(DATA,'r')
commands = [i for i in commandFile]
 
pdb.set_trace()
for router in routeServers:
  ##This strip is needed to remove any junk after the router name
  router = router.strip()
  print('####connecting to ', router)
  for i in range(max_retries):
    try:
      s = pexpect.spawn('ssh '+username+'@'+router, maxread=1000000, timeout=300)
      pattern_index = s.expect(["The authenticity of host", "WARNING:", "word:"])
      if pattern_index == 0:
        s.sendline('yes')
        s.expect('word:')
        s.sendline(password)
      elif pattern_index == 1:
        subprocess.call(["ssh-keygen", "-R", router])
        subprocess.call(["ssh-keyscan", "-H", router, ">> ~/.ssh/known_hosts"])
        s.sendline()
      elif pattern_index == 2:
        s.sendline(password)
        s.expect(r'\S+]#')
      for commanddata in commands:
        commanddata = commanddata.strip()
        command,outputext = commanddata.split('@')
        fout = open(CWD+'/output/'+router+'.'+outputext, 'wb')
        s.logfile = fout
        s.send(command)
        print(command)
        s.send('\r')
        s.expect(r'\S+]#')
        #removes the ctrl+M that is added to the files
        subprocess.call([BIN+'/firewall_cleanup.sh', CWD+'/output/'+router+'.'+outputext, command])
    except pexpect.EOF:
      print ('#####Retrying access to ' + router + '. Rety #' + str(i))
      print (str(pexpect.EOF))
      continue
    except pexpect.TIMEOUT:
      print ('#####Retrying access to ' + router + '. Rety #' + str(i))
      print (str(pexpect.TIMEOUT))
      continue
    except Exception as e:
      print ('!!!!!ERROR!!!!! Issue with host', router)
      print (str(e))
      s = None
```

**Comment by takluyver** [comment]
Pexpect is not designed for reading large amounts of data, and it's probably massively inefficient at doing so. It's a good idea to use a tool like sftp or scp to transfer the data instead of cat-ing it inside pexpect.

**Comment by 123troy** [comment]
Thank you.  I was trying to avoid using scp as the end user wants to see the prompt and cat command at the top of the file and the prompt at the bottom.  I went ahead, did the scp them wrote a bash script to tweak the resulting file to the way that the end user wants the data.
