### ISSUE TITLE
why this work line by line but not as a function

### ISSUE THREAD

**Issue by kw-andy** [pexpect/pexpect#500]
When I'm using this , I can connect and I can create a file on my remote server

```python
child = pexpect.spawn('ssh pi@192.168.1.32')
child.expect('password:')
child.sendline('XXX')
child.sendline('touch 123toto.txt')
child.sendline('exit') 
```

However, when I'm doing that through a function, the file is not created.

```python
def connect_wr():
    child = pexpect.spawn('ssh pi@192.168.1.32')
    child.expect('password:')
    child.sendline('XXX')
    child.sendline('touch 123toto.txt')
    child.sendline('exit')
```

How come?

**Comment by takluyver** [comment]
When it's not in a function, are you doing it manually with a pause between each line?

You may need to expect a prompt before sending each command.

**Comment by kw-andy** [comment]
Hi @takluyver ,

Actually, I do an enter after each line , for the non function one. Can it be seen as a pause between each each line?

Cheers

**Comment by kw-andy** [comment]
thanks @takluyver .

Would something like that work...?

```python
child.expect(prompt())
```

Best

**Comment by takluyver** [comment]
If `prompt()` returns something like `'$'` (or whatever the prompt is).

**Comment by kw-andy** [comment]
Cool @takluyver . Thank you v much for your help, I should be able to deal with the prompt part.

**Comment by kw-andy** [comment]
After some testing, it worked

```python
In [19]: def conn_wr():
    ...:     child = pexpect.spawn('ssh pi@192.168.1.32')
    ...:     child.expect('password:')
    ...:     child.sendline('XXX')
    ...:     child.expect('pi')
    ...:     child.sendline('touch 123toto.txt')
    ...:     child.expect('pi')
    ...:     child.sendline('exit')
```
After `child.sendline('touch 123toto.txt')`, just make sure that you have part of your prompt whatever it is. In my case my prompt is like this `[pi:/home/pi]$`. So I'm only using pi as the regex in `pexpect` will look for `pi`.

Once done, you can put as many commands as you wish.
