### ISSUE TITLE
except exception?

### ISSUE THREAD

**Issue by kw-andy** [pexpect/pexpect#508]
I've created this function

```python
def cre_file_conn(ip_addr,username,priv_keys):
    try:
        cmd = ("ssh -i {} {}{}{}").format(priv_keys,username,"@",ip_addr)
        child = pexpect.spawn(cmd)
        child.expect(username)
        child.sendline('touch 123toto.txt')
        child.expect(username) 
        child.sendline('exit')
    except Exception as e:
        print(str(e))       
```
The `except Exception as e` works well. But I was not able to find the mention on the docs.

What is the difference between `except Exception as e` and `except pexpect.EOF as e`?

I know that `except pexpect.EOF as e` will try to catch all EOF. But how about `except Exception`?

**Comment by takluyver** [comment]
`except Exception` catches any Python error (minus a couple of special ones, like `KeyboardInterrupt`). It's generally not recommended because it makes it harder to debug code when something's going wrong. If `pexpect.EOF` is the only error that ever comes up, it will achieve the same thing, but it's better to be more specific.

**Comment by kw-andy** [comment]
Hi @takluyver,

Thank you for your answer.

One last question:

- Is there somewhere in the doc that mentions all the possible exceptions?

Cheers

**Comment by takluyver** [comment]
The exceptions defined by Pexpect are documented here:
http://pexpect.readthedocs.io/en/stable/overview.html#exceptions

Python's general exceptions are documented here:
https://docs.python.org/3/library/exceptions.html

Of course, other packages can also define their own exception types.

**Comment by kw-andy** [comment]
Cheers @takluyver
