### ISSUE TITLE
issue importing pexpect into python

### ISSUE THREAD

**Issue by farhadkam** [pexpect/pexpect#543]
Hi,
I have already installed pexpect but I am not able to import it into python.
Can anyone please assist me?
Thanks
Some outputs:

$ sudo -H  pip install pexpect                           
Requirement already satisfied: pexpect in /usr/local/lib/python3.6/site-packages (4.6.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/site-packages (from pexpect) (0.6.0)
$ python
Python 2.7.14 (default, Apr 25 2018, 15:22:05) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexpect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pexpect

**Comment by jnatschev** [comment]
Hi, the answer is already in the output.

Not sure how your python versions are installed on your apple computer. However, when you ran the “sudo -H pip install pexpect” the output states that it has been installed in the python3.6 installation.

When you execute the “python” command you are placed in version 2.7.14.

Potentially you ought to execute:
python3

See how that goes. Unless you want to use python2.7 specifically. Then you’ll need to get pexpect installed into the python2.7 installation. Or alternatively have pip install into your “user” space; usually:
~/.local/lib/python2.7/site-packages #for python 2.7
~/.local/lib/python3.5/site-packages #for python 3.5
~/.local/lib/python3.6/site-packages #for python 3.6
and so on.

good luck...



Cheers,
John Natschev

**Comment by farhadkam** [comment]
Hi,

Thanks for your reply.
How can I install it for python 2.7 :)


Regards,
Farhad

Regards,
Farhad


On 30 Oct 2018, at 8:45 pm, John Natschev <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]

Hi, the answer is already in the output.

Not sure how your python versions are installed on your apple computer. However, when you ran the “sudo -H pip install pexpect” the output states that it has been installed in the python3.6 installation.

When you execute the “python” command you are placed in version 2.7.14.

Potentially you ought to execute:
python3

See how that goes. Unless you want to use python2.7 specifically. Then you’ll need to get pexpect installed into the python2.7 installation. Or alternatively have pip install into your “user” space; usually:
~/.local/lib/python2.7/site-packages #for python 2.7
~/.local/lib/python3.5/site-packages #for python 3.5
~/.local/lib/python3.6/site-packages #for python 3.6
and so on.

good luck...



Cheers,
John Natschev

**Comment by farhadkam** [comment]
ok tried this but still failed:

$ sudo -H pip2 install pexpect
Requirement already satisfied: pexpect in /Library/Python/2.7/site-packages (4.6.0)
Requirement already satisfied: ptyprocess>=0.5 in /Library/Python/2.7/site-packages (from pexpect) (0.6.0)
$ 
$ python
Python 2.7.14 (default, Apr 25 2018, 15:22:05) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexpect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pexpect
>>>

**Comment by jnatschev** [comment]
Who knows now.

One way you can try and work it out is to import sys. Once sys has been imported, execute:
sys.path

Look at the output of sys.path. The output is a list of paths where python will look for packages. If none of the path list elements matches “/Library/Python2.7/site-packages”, then you need to work out which python you are running because there may be more than one python installation.

Also, your problem doesn’t actually seem to be “pexpect” related at all and, therefore, this is the wrong forum for your problem.



Cheers,
John Natschev

**Comment by MuellerSeb** [comment]
What helped in my case was:

    sudo -H pip2 install -I pexpect

**Comment by th3coop** [comment]
User virtualenv to isolate your environment THEN start installing packages, @farhadkam.  Then you know 1. what version of python and pip you're using 2. where they are 3. you can bail out of the VE to the regular env easily after.

**Comment by Red-M** [comment]
Closing as the issue seems to be unrelated and correct solutions have been offered.

**Comment by yagnadeep** [comment]
sir i've installed the pexpect but tstill i see [!] Something went wrong, printing the error: No module named 'pexpect'
 in setoolkit

**Comment by jnatschev** [comment]
Try:
1.	open a terminal
2.	pip uninstall pexpect
3.	pip install —user pexpect
	this will install pexpect semewhere in your home directory. hopefully in this directory “${HOME}/.local/lib/python2.7/site-packages/pexpect"
4.	python
5.	import pexpect


Cheers,
John
