### ISSUE TITLE
pxssh $TERM issue - error: TERM is not defined.\r\nTerminal type?

### ISSUE THREAD

**Issue by msharp9** [pexpect/pexpect#550]
I kept receiving the above error.  Digging into the code pexpect/pexpect/pxssh.py.  I was able to fix this by changing line 308.

from:
        session_regex_array = ["(?i)are you sure you want to continue connecting", original_prompt, password_regex, "(?i)permission denied", "(?i)terminal type", TIMEOUT]
 to:
        session_regex_array = ["(?i)are you sure you want to continue connecting", original_prompt, password_regex, "(?i)permission denied", "(?i)[t|T]erminal type", TIMEOUT]
 
Let me know if you have questions.  Thanks!

**Comment by Red-M** [comment]
I'm not exactly sure how that should fix this as the `(?i)` for regex sets case insensitive matching which should do this anyway.

**Comment by msharp9** [comment]
Yeah, I know!  Just thought I'd share this strange behavior.  I recently upgraded the server from RHEL 4.9 to 7.6, and no longer experiencing the same problem.  Feel free to close the case.
