### ISSUE TITLE
4.7.0 is ready for release

### ISSUE THREAD

**Issue by Red-M** [pexpect/pexpect#565]
Can you check that I haven't missed something and can we release this version?

**Comment by takluyver** [comment]
It looks OK at a glance. Let me know your PyPI username, and I'll add you as a maintainer there as well so you can upload releases. Are you familiar with how to make an sdist and wheel, upload them to PyPI, and tag the release on Github?

**Comment by takluyver** [comment]
I just noticed the docs on Readthedocs weren't updating, so I've configured the webhook so it can get Github events again.

**Comment by Red-M** [comment]
My username on PyPI is Red_M.
I have release onto PyPI before for my own projects and I can figure out how to tag a release on GitHub.

**Comment by jdemeyer** [comment]
Can I please test it on SageMath first before officially releasing it? We are a heavy user of pexpect.

**Comment by Red-M** [comment]
Sure, Just pull the current master branch and install that in a testing environment.

**Comment by takluyver** [comment]
Great, thanks. I've added you on PyPI, so once @jdemeyer is happy, go for it.

**Comment by jdemeyer** [comment]
Good to go from me.

**Comment by Red-M** [comment]
4.7.0 is released.

Thanks for the help guys!
