### ISSUE TITLE
AttributeError: 'module' object has no attribute 'spawn'

### ISSUE THREAD

**Issue by nagcassandra** [pexpect/pexpect#567]
Hello Team,

I am facing below error in pexpect module in python 2.7 version (Windows 10), it's throwing 'Attribute Error'

AttributeError: 'module' object has no attribute 'spawn'

Can someone help to resolve the issue,

Thanks
Nagendra

**Comment by takluyver** [comment]
Hi Nagendra, that's expected. Pexpect is primarily a Unix tool, and Windows support is very limited. See: https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows
