### ISSUE TITLE
How to make expect() stop eating input after a match?

### ISSUE THREAD

**Issue by JanMatCodasip** [pexpect/pexpect#589]
Is there, please, any way how to stop `expect()` from consuming the input data when a match is encountered? Or an alternative way how to achieve the functionality ?

Lets assume the spawned child produces the following output:

```
Certain message 1
Certain message 2
prompt>
```

What I would like to do is to check for the presence of the messages one by one by multiple calls to `expect()`. 

```
child.expect("Certain message 1")
child.expect("Certain message 2")
child.expect("prompt>")
```

This of course does not work since the first `expect()` call consumes the whole input and leaves the rest of the output in `child.after`.

What would help me would be e.g. an optional argument that would change the behavior or `expect()` so that it stops right after the match and leaves the rest of the input data for further processing (`child.after` would be empty).

```
child.expect("Certain message 1", stop_on_match=True)
child.expect("Certain message 2", stop_on_match=True)
child.expect("prompt>")
```

Can you recommend an alternative way how to achieve this functionality?
Or would this feature be something that may potentially be included into Pexpect?

Thank you.

**Comment by rustyhowell** [comment]
@JanMatCodasip Can you provide the versions of OS, python, pexpect that you are running. Your scenario works perfectly fine on Ubuntu 18.04, Python 3.6, pexpect 4.6.0

**Comment by JanMatCodasip** [comment]
Hi Rusty,

my OS is CentOS 7.6 with Python 2.7.5 and Pexpect 4.7.0

However, I have just tried to re-create the same scenario with a different spawned program - and it also all started to work for me! I am not sure what the original blocker was but am comfortable with closing this thread. Thanks for checking this with me.

BR, 
Jan
