### ISSUE TITLE
Has anyone been able to enter git credentials with pexpect on windows?

### ISSUE THREAD

**Issue by jwlodek** [pexpect/pexpect#591]
I am trying to write a python script that will allow me to enter my username and password once and store them as variables, and then every time I want to commit and push I hit enter and pexpect calls git push:
```
import pexpect
child = pexpect.spawn('git clone REPO')
child.expect('Username *')
child.sendline(USER)
child.expect('Password *')
child.sendline(PASS)
child.expect(EOF)
```
This simple script works great on linux, but on windows I couldn't get it to work with the `popen_spawn.PopenSpawn` call, it just gets stuck at `expect('Username *')`

Has anyone been able to get this to work for windows? If not, does anyone have an alternative? I already tried wexpect and had the same result.

**Comment by rustyhowell** [comment]
@jwlodek The main features of pexpect are not supported on Windows.

**Comment by slel** [comment]
Maybe an option would be to use Cygwin, where pexpect works.

**Comment by Red-M** [comment]
Pexpect does not support windows.

I'd highly suggest that you take a look at git's [configuration documentation](https://git-scm.com/docs/git-config) and how to use SSH keys.

Using a repository/global git config that has your remote git username and using SSH keys for authentication will mean you don't need to answer these prompts at all and instead will use your pre-configured username and the SSH key that is loaded in your ssh key agent.

If you need windows specific tools, tortoisegit and PuTTY's pageant will do these for you and provide you an easy to use git UI for windows.
