### ISSUE TITLE
Some update broke pexpect

### ISSUE THREAD

**Issue by T-2** [pexpect/pexpect#592]
Up until a few weeks ago pexpect worked just fine.

My setup: 
A Raspberry Pi 3B+ updated with the latest Raspbain: 
   4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

Latest python included with Raspbain: python3/oldstable,now 3.5.3-1 armhf [installed,automatic]
Latest pexpect included with Raspbain: python3-pexpect/oldstable,now 4.2.1-1 all [installed]

Simplified and sanitized version of my code:

import pexpect

child = pexpect.spawn('ssh -i /home/pi/.ssh/remote_box -o StrictHostKeyChecking=no -p 22 pi@remote_box ifconfig')
child.expect("remote_box': ")
child.sendline('secretpassword')
child.expect(pexpect.EOF, timeout=20)
print (child.before)

What happens is it sends the ssh command, it then gets two identical prompt lines for the passphrase instead of just one. However pexpect never sends the secretpassword. It just times out.

Tried many things including:
  Tried the ssh command line outside of python. - That works fine. The prompt comes back to enter the passphrase for the key. Enter that and you get the ifconfig output and it exits from the remote box.
  Changed timeout=None - just hangs there forever
  Changed the child.expect("remote_box': ") line with shorter and longer prompt strings - no change
  Replaced the child.expect("remote_box': ") line entirely with time.sleep(5) - no change

What can I try next?

**Comment by rustyhowell** [comment]
@T-2 Can you provide the output your test script? Also is the ssh session authenticating via the SSH key that you are adding to the command, and so it is never getting the password prompt at all?

**Comment by T-2** [comment]
In does get the password prompt but it is 2 of them. From above "What happens is it sends the ssh command, it then gets two identical prompt lines for the passphrase instead of just one." Also from above "Replaced the child.expect("remote_box': ") line entirely with time.sleep(5) - no change"

I don't think the sendline is working for some reason.

**Comment by T-2** [comment]
Here is the Traceback log:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pft.py", line 16, in <module>
    pfs.expect(pexpect.EOF, timeout=10)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x76a0d270>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-i', '/home/pi/.ssh/pi_pfsense', '-o', 'StrictHostKeyChecking=no', '-p', '22', 'pi@pfsense.sig', 'ifconfig', 'igb0']
buffer (last 100 chars): b"\r\nEnter passphrase for key '/home/pi/.ssh/pi_pfsense': "
before (last 100 chars): b"\r\nEnter passphrase for key '/home/pi/.ssh/pi_pfsense': "
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 13444
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: EOF

**Comment by rustyhowell** [comment]
So what happens if you run the ssh command by itself?
`/usr/bin/ssh -i /home/pi/.ssh/pi_pfsense -o StrictHostKeyChecking=no -p 22 pi@pfsense.sig ifconfig igb0`

It looks like the ssh key you are using requires a passphrase and pxssh doesn't know how to handle that.

**Comment by T-2** [comment]
Tried the ssh command line outside of python in a terminal. - That works fine. The prompt comes back to enter the passphrase for the key. Enter that and you get the ifconfig output and it exits from the remote box.

**Comment by Red-M** [comment]
Have you tried the pxssh submodule?

**Comment by T-2** [comment]
I have been trying your suggestion to use pxssh. I can't seem to figure out how to set it up to use a ssh key with a passphrase to unlock the key. There are lots of examples for using ssh keys but they are for using keys without a passphrase. Can you give an example on how to do this?

**Comment by Red-M** [comment]
When you use `login()` provide both `password` and `ssh_key`.

**Comment by T-2** [comment]
Still no joy. Got "Could not establish connection to host"

Here is what I tried:

#!/usr/bin/python3
from pexpect import pxssh
try:
  pfs = pxssh.pxssh(options={'port': '22', 'StrictHostKeyChecking': 'no'})
  pfs.login('pfsense.sig', 'pi', '<secretpassword>', ssh_key='home/pi/.ssh/pi_pfsense')
  pfs.sendline('ifconfig igb0')
  pfs.prompt()
  print (pfs.before)
  pfs.logout()
except pxssh.ExceptionPxssh as e:
  print(e)

Is this right?

**Comment by T-2** [comment]
When I posted my last response there was <secretpassowrd> in between the '' marks in the above login line.

**Comment by T-2** [comment]
Looks like posting strips anything between greater than and less than signs. So my login line does have the passphrase in the login line even if I cannot post that here.

**Comment by T-2** [comment]
It should read:
pfs.login('pfsense.sig', 'pi', 'passphrasepassword', ssh_key='home/pi/.ssh/pi_pfsense')

**Comment by Red-M** [comment]
Use the code format option on github.

**Comment by T-2** [comment]
I will remember that for next time.
Anyway am I using pxssh correctly?
Is there any way to get more detailed error info?

**Comment by Red-M** [comment]
That should be working.

**Comment by T-2** [comment]
So should the original pexpect version that was working before some update!
How do I fix or at least get more on why it's not working?

**Comment by Red-M** [comment]
I'd double check the command by running it manually and seeing what ssh
provides back to the terminal.

**Comment by T-2** [comment]
/usr/bin/ssh -i /home/pi/.ssh/pi_pfsense -o StrictHostKeyChecking=no -p 22 pi@pfsense.sig ifconfig igb0
comes back with "Enter passphrase for key '/home/pi/.ssh/pi_pfsense': "
You enter the passphrase and it spits back the results from the ifconfig command as expected.

**Comment by T-2** [comment]
Fixed it!
You will not believe what the problem was!
It was something in the ssh key passphrase password that breaks pexpect and pxssh.
I changed the password and both pexpect and pxssh work just fine. 
I always use random passwords with symbols in them.
Here is the old password that breaks things: "ab&wJqB\6-9YKt^TaX@"
I will leave it to you track down what actually gets broke with this but I am now working again.

**Comment by Red-M** [comment]
The '\' needs to be escaped to '\\' so it'd be 'ab&wJqB\\6-9YKt^TaX@' as a
python string.

**Comment by T-2** [comment]
Strange that that now matters as it did not before.  
So probably the python update I did to the pi.

**Comment by Red-M** [comment]
That is in every version of python.
