### ISSUE TITLE
Allow to configure the buffer/before length in __str__ / display all if failed

### ISSUE THREAD

**Issue by blueyed** [pexpect/pexpect#597]
I think it would be nice if you could extend the length of the displayed buffer/before values in `__str__`:
Code: https://github.com/pexpect/pexpect/blob/a803933ed539e521169c8093e77639655b9b9f3a/pexpect/pty_spawn.py#L215-L216

However, the specific use case at hand is with test failures, where the `__str__` is then used by pytest to display it:
```
>           raise TIMEOUT(msg)
E           pexpect.exceptions.TIMEOUT: Timeout exceeded.
E           <pexpect.pty_spawn.spawn object at 0x7f20a131c048>
E           command: /home/travis/build/pytest-dev/pytest/.tox/py37-pexpect/bin/python
E           args: ['/home/travis/build/pytest-dev/pytest/.tox/py37-pexpect/bin/python', '-mpytest', '--basetemp=/tmp/pytest-of-travis/pytest-0/test_trace_with_parametrize_handles_shared_fixtureinfo0/temp-pexpect', '--trace', '/tmp/pytest-of-travis/pytest-0/test_trace_with_parametrize_handles_shared_fixtureinfo0/test_trace_with_parametrize_handles_shared_fixtureinfo.py']
E           buffer (last 100 chars): b"gs\r\nmyparam = 1\r\nrequest = <FixtureRequest for <Function test_func_kw[1]>>\r\nfunc = 'func_kw'\r\n(Pdb) "
E           before (last 100 chars): b"gs\r\nmyparam = 1\r\nrequest = <FixtureRequest for <Function test_func_kw[1]>>\r\nfunc = 'func_kw'\r\n(Pdb) "
E           after: <class 'pexpect.exceptions.TIMEOUT'>
E           match: None
E           match_index: None
E           exitstatus: None
E           flag_eof: False
E           pid: 4150
E           child_fd: 13
E           closed: False
E           timeout: 10.0
E           delimiter: <class 'pexpect.exceptions.EOF'>
E           logfile: <_io.BufferedWriter name='/tmp/pytest-of-travis/pytest-0/test_trace_with_parametrize_handles_shared_fixtureinfo0/spawn.out'>
E           logfile_read: None
E           logfile_send: None
E           maxread: 2000
E           ignorecase: False
E           searchwindowsize: None
E           delaybeforesend: 0.05
E           delayafterclose: 0.1
E           delayafterterminate: 0.1
E           searcher: searcher_string:
E               0: b'func = 1\r\n'
```
(https://travis-ci.org/pytest-dev/pytest/jobs/604874226#L3052)

Therefore it could maybe automatically display all of it when it failed?

**Comment by Red-M** [comment]
I've added an option to allow setting that character read back value in my PR #598.

**Comment by blueyed** [comment]
@Red-M 
Thanks!
What about defaulting to displaying everything (or rather a huger limit like 10k) when it has failed?  (have not checked but I assume `__str__` can be made to be aware of if there was a previous failure, e.g. before raising in this case (if not done already))

**Comment by Red-M** [comment]
I don't think changing the default is the right way to go about this because I believe this was set at 100 characters because the traceback from just this object alone is large enough on a terminal. it may not match your use case in pytest but this has been a default for a very long time.

If you want a full read back I'd suggest setting the value to either a large number or to `0` which will print the entire buffer out.

**Comment by takluyver** [comment]
Yeah, I'd be open to tweaking the default if someone made a good argument that e.g. 150 characters would often show something that 100 wouldn't. But I don't think increasing it to 10k or unlimited is a good idea - it's going to be filling up terminals with data that's hard to read and often isn't useful.
