### ISSUE TITLE
Confusing "another exception occurred" message on Timeout or EOF in Python 3.x

### ISSUE THREAD

**Issue by eldipa** [pexpect/pexpect#605]
When an exception is raised (like a Timeout or an EOF), the raised exception triggers another exception (Timeout or EOF respectively.)

In Python 2.x this was not a problem but in Python 3.x this *chains* the traceback. In particular Python says something like this:

```
Traceback (most recent call last):
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
    ...
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT:  ....

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "df.py", line 41, in <module>
    i = child.expect ([pattern, pexpect.EOF], timeout=0.001)
    ....
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: ....
```

The phrase `During handling of the above exception, another exception occurred` looks like there is a bug but it isn't.

The code explicitly catches the exceptions and re-raises them (https://github.com/pexpect/pexpect/blob/7b073bfa10209d6b3836d7b3e2429df89e7bf305/pexpect/expect.py#L116-L119)

I would like to propose two possible solutions:
 - we could set to None the *cause* of the second exception and disable the chaining like in Python 2.x
 - we could set to the *cause* to the previous exception: this would replace the phrase `During handling of the above exception, another exception occurred:` by `The above exception was the direct cause of the following exception` which it is more correct.

If it is ok, I would like to propose a PR for the former solution.

Off topic: sorry by my English.

**Comment by Red-M** [comment]
This suggestion looks fine to merge.
