### ISSUE TITLE
pexpect will hangs up when bash lot of command

### ISSUE THREAD

**Issue by IsaacLiang** [pexpect/pexpect#610]
i want to use pexpect to update firewall policy. the policy more than 60000 rows. when the script bash about 2500 rows, the script will hangs up. 

++++++++++++++++++++++++++++++++
import pexpect
import time
import os

 
class CiscoSwitch():
     
    def __init__(self, host, username, password,pripasswd):
        self.username = username
        self.host = host
        self.password = password
        self.pripasswd = pripasswd
        
    def Login(self):
         ssh_newkey = 'Are you sure you want to continue connecting (yes/no)?'
         ssh_newkey2 = 'hit Cancel to abandon the connection.'
         print ('\r\n'+'*'*50+'\r\n'+'*'*50+'\r\n'+'NOW is logining: '+self.host +'\r\n'+'*'*50+'\r\n'+'*'*50+'\r\n')
         self.child = pexpect.spawn('ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no '+self.username+'@'+self.host)
         ret = self.child.expect([pexpect.TIMEOUT, ssh_newkey, '[P|p]assword:','>',ssh_newkey2],timeout=10)
         time.sleep(5)
         if ret == 4:
             print 'the key2 need to confirm yes'
             self.child.sendline('yes') 
             time.sleep(5)             
         if ret == 0:
             print self.child.before
             print '-'*50+'\r\n'+'-'*50+'\r\n'
             print 'connection error on first step in FW!!'
             return (self.child, self.child.before)
         if ret == 1:
             print 'the key need to confirm yes'
             self.child.sendline('yes')
             time.sleep(5)
         if ret == 2:
             print 'send password'
             self.child.sendline(self.password)
             time.sleep(5)    
         ret = self.child.expect([pexpect.TIMEOUT,ssh_newkey, '[P|p]assword:','>'],timeout=3)
         if ret == 0:
             print 'connection error in second step!!'
             return (self.child, self.child.before)
         if ret == 1:
             print '\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'[-] Could not accept new key from ' + self.host+'\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'
             return (self.child, self.child.before)
         if ret == 2:
             print ' enter login password!!'
             self.child.sendline(self.password)             
         if ret == 3:
             self.child.sendline('enable')
             time.sleep(5) 
         ret = self.child.expect([pexpect.TIMEOUT, '[P|p]assword:','>'],timeout=3)   
         if ret == 0:
             print '\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'[-]Timeout!' +'\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'  
         if ret == 1:
             print ' enter the pripassword !!!'
             self.child.sendline(self.pripasswd)
             time.sleep(3)
         if ret ==2:
             print ' enter enable'
             self.child.sendline('enable')
             time.sleep(3)             
         ret = self.child.expect([pexpect.TIMEOUT,'[P|p]assword:','#'])
         if ret == 0:
             print '\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'Error'+self.host+'\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'
             return (self.child, self.child.before)
         if ret == 1:
             self.child.sendline(self.pripasswd)
             return (self.child, self.child.before)
         if ret == 2:
             print ('\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'Loing successed:'+self.host+'\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n')
             return (self.child, self.child.before)             
         ret = self.child.expect([pexpect.TIMEOUT,'[P|p]assword:'],'#')
         if ret == 0:
             print '\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'Error'+self.host+'\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'
             return (self.child, self.child.before)         
         if ret == 1:
             print '\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'[-] The Prilivage Password is invalid!'+self.host+'\r\n'+'-'*50
             return (self.child, self.child.before)   
         if ret == 2:
             print ('\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n'+'Loing successed:'+self.host+'\r\n'+'-'*50+'\r\n'+'-'*50+'\r\n')
             return (self.child, self.child.before)

  def PolicyCmd(self,cmd):

        policytemp = []
        self.child.sendline(cmd)
        self.child.expect('#')
        self.child.sendline('confi t')
        self.child.expect('#')
        self.child.sendline('pager 0')
        self.child.expect('#')
        self.child.sendline('show running | i access-group')
        self.child.expect('#')
        
        with open('outputshow.txt','a') as f:
            f.write(self.child.before+'\r\n')
               
        cp = open("outputshow.txt","r")
        lines = cp.readlines()
        for line in lines: # for verify that there is outside 
            if 'access-group' and 'outside' in line:
                policytemp = line               
                print policytemp.split(' ')[1]
                policycheck = 1
                print 'oustide interface hava policy!!'
                break
                    
                                
            else:
                policycheck = 2
        print 'policycheck is :' + str(policycheck)  #for check the function             
        policy= open("policyupdate.txt","r")
        time.sleep(1)
        policylines = policy.readlines() 
        commtemp = 0
        timei = 0
        if policycheck == 1:
            print '-------- adding policy in outside --------'
            for policyline in policylines: #for add policy
                timei+=1
                if timei >= 50:
                    commtemp = 3                 
                    time.sleep(2)                                        
                if commtemp ==0: 
                    self.child.sendline(policyline) 
                    time.sleep(0.1)
                    commtemp = self.child.expect(['#', pexpect.EOF, pexpect.TIMEOUT],timeout=20)
                    print 'adding policy...'
                if commtemp ==1:
                    time.sleep(2)                    
                    print 'policy update error!!'
                    self.child.close(force=True)
                    break
                if commtemp ==2:
                    time.sleep(2)
                    print 'proccess time out!!'
                    self.child.close(force=True)
                    break
                if commtemp ==3:                   
                    print 'proccess taking a rest!!'
                    time.sleep(10)
                    commtemp = 0
                    timei = 0
        else:
            print 'policycheck value is:'+str(policycheck)

        cp.close()
        os.remove('outputshow.txt')            
        return (self.child, self.child.before)   

if __name__ == '__main__':

    Switch = CiscoSwitch('IP','USER','PASSWD','PASSWD')
    (obj,stdout) = Switch.Login()

    (obj,stdout) = Switch.PolicyCmd('updatedpolicy')
    print stdout

**Comment by Red-M** [comment]
Pexpect isn't designed to handle large amounts of text like that. I'd recommend using another SSH library to do automation like this or to not use regexes for matching as pexpect should then use the text based searcher which might get you just over the line, however this is obviously sub-optimal to do so.

**Comment by IsaacLiang** [comment]
> Pexpect isn't designed to handle large amounts of text like that. I'd recommend using another SSH library to do automation like this or to not use regexes for matching as pexpect should then use the text based searcher which might get you just over the line, however this is obviously sub-optimal to do so.

Thanks. I try to use another SSH library, Could you give me any suggestion?

**Comment by takluyver** [comment]
The [pxssh page of the docs](https://pexpect.readthedocs.io/en/latest/api/pxssh.html) recommends Paramiko or @Red-M's RedExpect library.

**Comment by IsaacLiang** [comment]
Thanks.
