### ISSUE TITLE
Pexpect: Could not set shell prompt

### ISSUE THREAD

**Issue by rakeshk121** [pexpect/pexpect#613]
I have referred a python script from https://pexpect.readthedocs.io/en/stable/api/pxssh.html in order to perform a ssh password based login.
Code is as follows:
```
from pexpect import pxssh
import getpass
try:
    s = pxssh.pxssh()
    hostname = input('hostname: ')
    username = input('username: ')
    password = getpass.getpass('password: ')
    s.login(hostname, username, password)
    s.sendline('uptime')   # run a command
    s.prompt()             # match the prompt
    print(s.before)        # print everything before the prompt.
    s.sendline('ls -l')
    s.prompt()
    print(s.before)
    s.sendline('df')
    s.prompt()
    print(s.before)
    s.logout()
except pxssh.ExceptionPxssh as e:
    print("pxssh failed on login.")
    print(e)
```

When i run the code, it prompts for hostname, username and password. After these inputs are provided through CLI,the ssh login fails with the exception as follows:
```
could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nUser1@167.254.225.14's password: \r\nUser1@167.254.225.14's password: ", expected: '\\[PEXPECT\\][\\$\\#] ').
```
The manual login works fine for the same ssh credentials.
```
Note:
Python version: 3.6
Pexpect version: 4.7 
```

**Comment by Red-M** [comment]
This is most likely due to your password being incorrectly typed as far as I can tell.

**Comment by rakeshk121** [comment]
> This is most likely due to your password being incorrectly typed as far as I can tell.

No, I have provided right password. Also cross verified by manual ssh login.

**Comment by Red-M** [comment]
If you're connecting to a non-linux device you can try in your `login()` call to turn off `auto_prompt_reset` by setting it to `False`.

Otherwise I am going to need more a traceback than what you've provided.

**Comment by rakeshk121** [comment]
> If you're connecting to a non-linux device you can try in your `login()` call to turn off `auto_prompt_reset` by setting it to `False`.
> 
> Otherwise I am going to need more a traceback than what you've provided.

The ssh is done to a VM with following Specifications:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
```
Any other trace-back or Specifications required?

One observation i found was: When i perform a manual ssh login to the above VM, It will take about 20 sec to prompt for password. Will this be the reason for Pexpect Error?

**Comment by rakeshk121** [comment]
> If you're connecting to a non-linux device you can try in your `login()` call to turn off `auto_prompt_reset` by setting it to `False`.
> 
> Otherwise I am going to need more a traceback than what you've provided.

The ssh is done to a Virtual Machine with following Specifications:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
```
Any other trace-back or Specifications required?

One observation i found was: When i perform a manual ssh login to the above VM, it will take about 20 seconds to prompt for password.
``` [infra1@cicada252 rakesh]$ ssh user1@167.254.225.14 ```

after 20 sec

```user1@167.254.225.14's password: ```

Will this be the reason for Pexpect Error?

Also note that the Pexpect login with the same above code in the question was working fine a month ago. Is the 20 sec delay in prompting the password is creating problem?

**Comment by Red-M** [comment]
Set `login_timeout` in your `login()` call to a much higher number and see how that goes.

**Comment by rakeshk121** [comment]
> Set `login_timeout` in your `login()` call to a much higher number and see how that goes.

Thanks this worked.
