### ISSUE TITLE
Class wrapping pexpect

### ISSUE THREAD

**Issue by lackdaz** [pexpect/pexpect#625]
Hi! I'm new to pexpect and which I'm developing a custom interface for my 3d printer.

I'm using an interactive session that interfaces with the printer port, which looks like this:
```
$ python pronsole.py
Welcome to the printer console! Type "help" for a list of available commands.
offline> connect
No port specified - connecting to /dev/cu.usbmodem20813183324D1 at 115200bps
Printer is now online
cu.usbmodem20813183324D1 -15°>
```
This was the simple python script I wrote which works great:
```
from pexpect import *

p = spawn('python pronsole.py')
p.expect('Welcome')
print(p.pid)
p.sendline('connect')
print('connecting...')
p.expect('Printer is now connected')
print('connected')
p.sendline('G28')
```

Now on to my problem. I'm looking to wrap the pexpect into another class to create a callable object that does the few fews that I need(e,g, homing, connecting, moving, etc), looking like this:
```
class Printer:
  def __init__(self):
    self.port = glob.glob('/dev/cu.usbmodem*')[0] #TODO: hard-coded for now
    self.p = pexpect.spawn('python pronsole.py')
    self.p.expect('Welcome')

  def connect(self):
    if self.p.isalive():
      print(self.port)
      self.p.sendline(f'connect {self.port}')
      logging.debug('Connecting...')
      index = self.p.expect(['Printer is now connected', 'something bad', pexpect.EOF, pexpect.TIMEOUT]) # <------ code is failing here
      if index == 0:
        logging.debug('Connected...')
        return true
      elif index == 1:
        logging.debug("Failed to connect")
        return false
        # TODO: error handler()
      elif index == 2:
        logging.debug("EOF")
        # TODO: error handler()
      elif index == 3:
        logging.error("timeout")
        # TODO: error handler()
    else:
      logging.error('Lost connection')
      return false
```
I'm now noticing that my string pattern matching stated above failing. When I probe and call pexpect myself in interactive mode, I'm getting strange integer outputs like 8 for 'connect', 11 for 'disconnect', 38 for something else. I'm guessing that these can now be used as exit statuses but I'm puzzled why they have changed. Does this have something to do with the async nature of my requests?

 My question is: 
1) Why is my return status changing from string (like "Welcome") to some integer output? 
2) Are we able to wrap pexpect into callable class objects

**Comment by Red-M** [comment]
1. Where are these integers coming from? The code you posted should only return `True` or `False` which is `1` and `0` respectively. For the strange integers themselves, they appear to be `len()` of the strings you're describing.
2. Yes, you just need to pick the classes you'd like to wrap.

I feel as if you've left some of the code out or you've since changed the code.
I'd recommend you take a look at octoprint for handling 3D printers as well as the project has been around for years and is very capable of handling 3D printers. (I've made a few plugins for octoprint myself :))

**Comment by lackdaz** [comment]
@Red-M Hey thanks for your super prompt response. I'm actually using printcore/pronsole to run this which is the library behind pronterface.

The integer outputs are console returns when I probe the initialised class object. I basically run `python -i myclass.py` and:

```
>>> foo = Camera()
>>> foo.connect()
>>> foo.p.isalive()
True
>>> foo.p.connect()
>>> foo.p.sendline('connect')   
8
>>> foo.p.sendline('disconnect')
11
```

If you're okay, I would love to contact you to ask a few more questions. As for the code its something I can put into the repository and link here in a bit.

**Comment by lackdaz** [comment]
Actually, could it be the case that `index = self.p.expect(['Printer is now connected', 'something bad', pexpect.EOF, pexpect.TIMEOUT]) # <------ code is failing here`
isn't actually running pattern matching, but has to score an exact match?

**Comment by Red-M** [comment]
> The integer outputs are console returns when I probe the initialised class object. I basically run python -i myclass.py and:

This is the number of bytes that pexpect sent to the process.

> Actually, could it be the case that index = self.p.expect(['Printer is now connected', 'something bad', pexpect.EOF, pexpect.TIMEOUT]) # <------ code is failing here
isn't actually running pattern matching, but has to score an exact match?

Change the strings to a regex string and you can use regexes.

**Comment by lackdaz** [comment]
@Red-M Thank you so much for clearing up my understanding! It does all work now brilliantly
