### ISSUE TITLE
REPLwrapper run_command() issues with multiple pexpect child applications

### ISSUE THREAD

**Issue by rvarium** [pexpect/pexpect#630]
I am facing a challenge with REPLwrapper.  I have two pexpect child applications (both are telnet sessions)  and I need to run shell commands on both of them using REPLWrapper's run_command().   In my code, I switch between the two pexpect child applications and use run_command() in both of them.  Each of them have their on prompts to differentiate between them. 

The problem is that the prompt is not printed by run_command().  

For ex, my code in a very simplified way looks like 
_________________________________
DUT-A.run_command('ifconfig')
DUT-B.run_command('ls')
_________________________________

In this example I use DUT-A# as prompt for the first telnet session and DUT-B# for the second. The output looks like :

ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 33136
        inet 127.0.0.1 netmask 0xff000000
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
wm0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        capabilities rx=7<IP4CSUM,TCP4CSUM,UDP4CSUM>
        capabilities tx=3f<IP4CSUM,TCP4CSUM,UDP4CSUM,TCP6CSUM,UDP6CSUM,TSO4>
        enabled=0
        address: 00:0c:29:04:76:95
        media: Ethernet autoselect (1000baseT full-duplex)
        status: active
        inet 172.16.109.100 netmask 0xffffff00 broadcast 172.16.109.255
        inet6 fe80::20c:29ff:fe04:7695%wm0 prefixlen 64 scopeid 0x11
        inet6 2001::a prefixlen 64
pflog0: flags=0 mtu 33136
DUT-A#ls
ls
DUT-B#.

Two issues here:  

1) There is no way from the output to know which child application "ifconfig" was run because the prompt DUT-A# is not printed preceding the output of that command. 
2) The "ls" command looks like it was executed on DUT-A# but actually it is on DUT-B#.   The prompt DUT-B# is not printed preceding the output so it is impossible to know that it was executed on DUT-B.

Is there any solution provided by REPLwrapper for this ?

**Comment by takluyver** [comment]
It's not entirely clear what you're doing, but replwrap by itself does not print anything. It's meant to return a string with the output of the given command, not including any prompts. If you want to display that output with an indication of where it came from, that should be easy to do in Python code, something like:

```python
child1_output = child1.run_command('ls')
print("child1:", child1_output)
```

**Comment by rvarium** [comment]
Thank you for the reply. The work around that I am using is to give a newline as in 

child1.run_command('\nls')

so that it forces the prompt to appear in the output log.
