### ISSUE TITLE
REPLWrapTestCase.test_bash_env fails if bashrc does not export PS1

### ISSUE THREAD

**Issue by whitley-delamora** [pexpect/pexpect#631]
The test `REPLWrapTestCase.test_bash_env` in `tests/test_replwrap.py` fails if the users bashrc does not have an environment variable `PS1`.

The variable `PS1` is not a environment variable per se and thus not shown by `env` (cf. [this stackoverflow question](https://stackoverflow.com/questions/41931855/why-env-does-not-print-ps1-variable)).

It can be made into an environment variable by exporting it with `export PS1`, which is some have in their bashrc but others (like me) don't.

To make the test consistent either

* test for a real environment variable, or
* export it before running `env` in the test, thus not relying on the user configuration.

Something like:
```
    def test_bash_env(self):
        """env, which displays PS1=..., should not mess up finding the prompt.
        """
        bash = replwrap.bash()
        res = bash.run_command("export PS1")  # <--- This line is new
        res = bash.run_command("env")
        self.assertIn('PS1', res)
        res = bash.run_command("echo $HOME")
        assert res.startswith('/'), res
```
should suffice.

**Comment by takluyver** [comment]
Thanks @whitley-delamora . This makes sense, and your proposed fix for the test looks good. Do you want to make a pull request with this change?

**Comment by whitley-delamora** [comment]
Wow, what a quick response.

> Do you want to make a pull request with this change?

Been there, done that. Thx.

**Comment by takluyver** [comment]
Thanks. I should say I'm not usually that quick, I just happened to have time to read and respond to your message. :wink:
