### ISSUE TITLE
spawn is really slow in docker container

### ISSUE THREAD

**Issue by vivintsmartvideo** [pexpect/pexpect#633]
I am spawning a process with pexpect inside a docker container, it is super slow!  Thoughts for why it would be so slow?  Any suggestions on how to debug it?

I'm on pexpect v4.6.0  Fedora 30 for my os (system and docker)

Here is how long it takes on my system:
```
# ipython3
Python 3.7.4 (default, Jul  9 2019, 16:32:37)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: import pexpect
[ins] In [2]: %timeit p = pexpect.spawn('bash')
101 ms ± 823 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Here is how long it takes in docker:
```
# ipython3
Python 3.7.6 (default, Jan 30 2020, 10:29:04)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

[ins] In [1]: import pexpect
[ins] In [2]: %timeit p = pexpect.spawn('bash')
5.73 s ± 566 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by vivintsmartvideo** [comment]
I also tested on the ubuntu 18.04 docker image
```
# ipython3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pexpect
In [2]: %timeit p = pexpect.spawn('bash')
6 s +- 953 ms per loop (mean +- std. dev. of 7 runs, 1 loop each)
```

**Comment by vivintsmartvideo** [comment]
I tried again on an ubuntu 18.04 machine with ubuntu 18.04 docker image, this time I saw ~100 ms on the machine and ~960 ms in docker (still 10x slower, but not 60x)

**Comment by vivintsmartvideo** [comment]
It was a problem with the pty module, a workaround is here:
https://github.com/docker/for-linux/issues/502

**Comment by takluyver** [comment]
NB the comments there link back to an issue proposing a workaround on ptyprocess (the base of pexpect): https://github.com/pexpect/ptyprocess/issues/50

I'm somewhat wary of changing the innards of pexpect/ptyprocess, because it's old code used in a range of situations which I don't know about until it breaks. But we could probably do this in an 'if linux' block and fall back to the existing code for other Unix platforms.

**Comment by vivintsmartvideo** [comment]
I used the provided hack as a workaround, I'll duplicate here for others:
`docker run -it --rm --ulimit nofile=X docker-benchmark python bench.py`
where X=1024, although you can adjust it to be a value you like.
