### ISSUE TITLE
Flushing the buffer?

### ISSUE THREAD

**Issue by lackdaz** [pexpect/pexpect#636]
Hi! from what I get: 
child.before = text before the match
child.match = the match
child.after = text.after the match

Is there some way I can flush the buffer, because I got text bleeding from previous expects and its causing some matches to fail/incorrectly match. I've got a child that is basically long running and doesn't have an EOF.

I've inferred the above from https://github.com/pexpect/pexpect/issues/588

**Comment by lackdaz** [comment]
basically it would be great if I could flush `child.after`

**Comment by vivintsmartvideo** [comment]
For my use case, I decided to flush the buffer one line at a time.  So my "hack" to flush the buffer looks something like this:

```
while True:
    try:
        child.expect('\n', timeout=0)
     except:
         break
```
Since the timeout is 0, it returns immediately if it doesn't find a newline in the buffer.  You could use a regular expression like "." to flush the buffer one character at a time.

**Comment by thisdougb** [comment]
@lackdaz I'm trying to figure this out as well.  See #639 

Currently matching on a timeout is working for me:
```
session.expect(pexpect.TIMEOUT, timeout=-1)
```
This appears to put everything in BEFORE, per call to sendline()

**Comment by vivintsmartvideo** [comment]
I like @thisdougb 's solution, but I think a slight modification improves it:
`session.expect(pexpect.TIMEOUT, timeout=0)`
This way you immediately have a timeout.

**Comment by Red-M** [comment]
I've had text "bleeds" before and what I've found over the years is what I've commented in #639.
