### ISSUE TITLE
pxssh access to remote server via jumphost/jumphosts (ssh)

### ISSUE THREAD

**Issue by f3rzko** [pexpect/pexpect#641]
I have a python script that connects via ssh to the remote server, performs some commands, and logout. But in some cases I need to connect to this server via jump host(hosts) like with ssh command:

`ssh -J (user@jumphost) (user@remote.internal.host) `

Here's code example
```

import pexpect
from pexpect import pxssh
import getpass
try:
    s = pxssh.pxssh(options={
                    "ProxyJump": "user@jumphost"})
    hostname = "remote.internal.host"
    username = "user"
    port = ""
    password = getpass.getpass('Password: ')
    s.login(hostname, username, password, port=port)
    s.sendline('command1')
    s.prompt()
    s.sendline('command2')
    s.prompt()
    s.sendline('command3')
    s.prompt()
    s.logout()
   except pxssh.ExceptionPxssh as e:
    print("Login failed.")
    print(e)
```

The result of this script that I have "permission denied", and it means that pxssh doesn't enter a password for jump host, I even try to use pexepect for it, but somehow it doesn't work. Maybe someone knows how to enter password in password prompt for jumphost with option "Proxyjump"?

**Comment by Red-M** [comment]
I heavy do not encourage the use of pxssh anymore as alternate solutions work way better in many aspects. [As per the notice on the documentation](https://pexpect.readthedocs.io/en/stable/api/pxssh.html)

However, as per the [pxssh documentation here](https://pexpect.readthedocs.io/en/stable/api/pxssh.html#pexpect.pxssh.pxssh.login), simply call login again with whatever you need to connect to the next server. So you use `login()` once to the jump server then call `login()` again to then connect to the next server by calling `login()` with `spawn_local_ssh` set to `False`.
