### ISSUE TITLE
How to handle multiple users (sessions, threads)?

### ISSUE THREAD

**Issue by GraphGrailAi** [pexpect/pexpect#642]
I use pexpect to interact with stdout like a chat, this works:

    import pexpect
    botterminal = pexpect.spawnu('/root/anaconda3/bin/python3.6 /var/www/scripts/interactive.py -t talk')
    botterminal.sendline('user_message 1')
    botterminal.expect([pexpect.TIMEOUT, '> ', pexpect.EOF]) 
    botterminal_before = print(botterminal.before)
    botterminal.sendline('user_message 2')

But, what if another user form another PC send commands `botterminal.sendline('user_message 1')` ?

Another words: how do i direct `sendline` commands to different processes(threads?) to control input and output for every user separated, with no mess?

**Comment by Red-M** [comment]
This isn't supported as pexpect only deals with stdout, stderr and stdin for processes and cannot interact with threads or multiple processes within a single `pexpect.spawn()` call.
