### ISSUE TITLE
telnet in REPLwrapper 

### ISSUE THREAD

**Issue by rvarium** [pexpect/pexpect#653]
I have a telnet session inside REPLwrapper as in the code below:

    tn = pexpect.spawnu("telnet 127.0.0.1",echo=False)
    tn.expect("login:")
    tn.sendline("abcd")
    tn.expect("Password")
    tn.sendline("abcd")
    prompt_change = "PS1={0}".format("#")
    repl = REPLWrapper(tn, "\$", prompt_change, "#")

When I step into the REPLWrapper() using a python debug application, I can see that the command 

PS1="#"

executed by REPLWrapper is echoed into the output of this command in spite of echo being disabled.  This is true about every following command that I give using repl.run_command().  I get the input echoed as part of the output.  I wonder why that is so.

**Comment by takluyver** [comment]
I'm not exactly sure, but I'd guess that telnet always disables the echo on the local terminal, and the echoing comes from the remote system you're connected to, which pexpect can't directly manipulate.

**Comment by rvarium** [comment]
You are right.  When I captured telnet packets in wireshark, I could see that the server echoes back the command and pexpect does not parse the output to see if the input command is present in the output string from server.
