### ISSUE TITLE
macOS: Slave PTY output discarded on child process exit

### ISSUE THREAD

**Issue by k15tfu** [pexpect/pexpect#662]
Hi! Just found an issue with discarding slave PTY output on child process exit (https://developer.apple.com/forums/thread/663632).

As described, Pexpect will fail on macOS if there is a delay between `spawn()` and the first `.expect()`:
```python
import pexpect, time

child = pexpect.spawn('python3 -c \'print("%s", flush=True)\'' % ("0123456789" * 10))
time.sleep(2)
child.expect("0123456789" * 10)
```

results to:
```sh
$ python3 pexpect_test.py
Traceback (most recent call last):
  File "pexpect_test.py", line 5, in <module>
    child.expect("0123456789" * 10)
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/usr/local/lib/python3.8/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.8/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
```

This doesn't look like https://pexpect.readthedocs.io/en/stable/commonissues.html#truncated-output-just-before-child-exits issue, because in this case I flush stdout before exiting.

As a workaround, it has been suggested to "keep an open slave fd in the parent process", or alternatively, you can switch to your own `_fork_pty.fork_pty()` implementation on macOS (https://github.com/pexpect/ptyprocess/blob/5436e55d81d114edef254e79e3478306a1489da1/ptyprocess/ptyprocess.py#L32), which does open `/dev/tty` in `pty_make_controlling_tty()` (https://github.com/pexpect/ptyprocess/blob/5436e55d81d114edef254e79e3478306a1489da1/ptyprocess/_fork_pty.py#L77), and that actually works:
```sh
$ python3 pexpect_test.py
$
```

--
pexpect 4.8.0
ptyprocess 0.6.0

**Comment by strager** [comment]
I encountered this issue with pexpect 4.8.0 and ptyprocess 0.7.0 on Python 3.10 on macOS 13.2.

I also encountered this issue with the following C program, so I don't think it's a subtlety of pexpect:
```c
// This program creates a child process with a pty. The child writes a string
// and the parent reads the string.
//
// Expected output:
//
//     forkpty() = 64766, errno=0 (Undefined error: 0), raw_tty_fd=3
//     read(3, buffer, 10) = 5, errno=0 (Undefined error: 0)
//     data = "hello"
//     waitpid(64766, status, 0) = 64766, errno=0 (Undefined error: 0)
//     status: exited=1 exitstatus=0
//
// If I add a delay in the parent after forking but before reading, the parent
// doesn't see the data written by the child:
//
//     forkpty() = 64638, errno=0 (Undefined error: 0), raw_tty_fd=3
//     read(3, buffer, 10) = 0, errno=0 (Undefined error: 0)
//     data = ""
//     waitpid(64638, status, 0) = 64638, errno=0 (Undefined error: 0)
//     status: exited=1 exitstatus=0
//
// Tested on macOS 13.2.

#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <util.h>

int main() {
  int tty_fd = -1;
  errno = 0;
  pid_t pid = forkpty(&tty_fd, /*name=*/NULL, /*termp=*/NULL, /*winp=*/NULL);
  if (pid != 0) {
    // Parent.
    fprintf(stderr, "forkpty() = %d, errno=%d (%s), raw_tty_fd=%d\n", (int)pid, errno, strerror(errno), tty_fd);
  }

  if (pid == 0) {
    // Child.
    ssize_t rc = write(STDOUT_FILENO, "hello", 5);
    if (rc == -1) {
      exit(1);
    }
    if (rc != 5) {
      exit(2);
    }
    exit(0);
  } else {
    // Parent.
    sleep(1);

    char buffer[10];
    errno = 0;
    ssize_t rc = read(tty_fd, buffer, sizeof(buffer));
    fprintf(stderr, "read(%d, buffer, %d) = %d, errno=%d (%s)\n", tty_fd, (int)sizeof(buffer), (int)rc, errno, strerror(errno));
    if (rc >= 0) {
      fprintf(stderr, "data = \"%.*s\"\n", (int)rc, buffer);
    }

    int status = -1;
    errno = 0;
    pid_t wait_rc = waitpid(pid, &status, /*options=*/0);
    fprintf(stderr, "waitpid(%d, status, 0) = %d, errno=%d (%s)\n", pid, (int)wait_rc, errno, strerror(errno));
    if (wait_rc >= 0) {
      fprintf(stderr, "status: exited=%d exitstatus=%d\n", WIFEXITED(status), WEXITSTATUS(status));
    }

    close(tty_fd);
  }

  return 0;
}
```

**Comment by strager** [comment]
The workaround mentioned by @k15tfu (using `ptyprocess`'s own `pty_make_controlling_tty`) works on my machine. However, there's a "simpler", less invasive fix: Add `close(open("/dev/tty", O_WRONLY));` in the beginning of the child. (I think this is the magic sauce which makes `pty_make_controlling_tty` work.) Patch for my example C program:
```diff
   if (pid == 0) {
     // Child.
+    close(open("/dev/tty", O_WRONLY));  // TODO: error checking
     ssize_t rc = write(STDOUT_FILENO, "hello", 5);
```
If it's hard to modify `ptyprocess` for whatever reason, this could be done inside `pexpect`'s code.

**Comment by strager** [comment]
I figured out why the open("/dev/tty") hack worked. Here's a detailed explanation (including links to XNU code and example programs) of what happens with and without the hack:

https://github.com/quick-lint/quick-lint-js/blob/18ca709392f9089ce89ff3c0c09a7c1a1117b13c/src/quick-lint-js/port/pty.cpp#L205

I'm not interested in pexpect exactly, so I am not going to carry the torch, but I think a fix for pexpect/ptyprocess should be straightforward.

**Comment by Red-M** [comment]
If someone would like to do a PR for this, patches are welcome.
