### ISSUE TITLE
can pexpect send function keys, arrow keys, home key etc. ?

### ISSUE THREAD

**Issue by spren-github** [pexpect/pexpect#673]
Hi all,
can pexpect send function keys, arrow keys, home key etc. ? I have tried but failed.
I tried like :  pexpect.send('\x1b[B') 

Thanks.

**Comment by MuhammadWaqar96** [comment]
Hey, did you get any solution against this problem? i want to execute function key to session

**Comment by nabaco** [comment]
worked for me:
```py
ESC="\x1b\r"
child.send(ESC)
```

Not sure if the `\r` is required in the end, but it works :)
