### ISSUE TITLE
pxssh does not support async

### ISSUE THREAD

**Issue by eduardofcgo** [pexpect/pexpect#676]
The expect all support an the optional keyword argument `async_`. `pxssh` does not seem to support this.

**Comment by Red-M** [comment]
There are no plans to add async support in pexpect.

I heavy do not encourage the use of pxssh anymore as alternate solutions work way better in many aspects. [As per the notice on the documentation](https://pexpect.readthedocs.io/en/stable/api/pxssh.html)
