### ISSUE TITLE
PopenSpawn.kill behaves strangely on Windows

### ISSUE THREAD

**Issue by tromey** [pexpect/pexpect#679]
I'm using `PopenSpawn` on Windows and I've found it behaves somewhat strangely.  In particular, my program does not seem to terminate, but instead I get errors like `PermissionError: [WinError 5] Access is denied`.

I switched my wrapper class to use `proc.terminate` and `proc.send_signal`, and this seems to have solved my problems.  Perhaps `PopenSpawn` should do the same, rather than using `os.kill`.

**Comment by Red-M** [comment]
Pexpect doesn't support windows.

**Comment by slel** [comment]
Though it works in Cygwin.

**Comment by tromey** [comment]
> Pexpect doesn't support windows.

Perhaps then the docs should be updated:

https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows

**Comment by Red-M** [comment]
My apologies, my understanding has been that windows doesn't necessarily work properly.
I'll take a deeper look into this when I get the time.

**Comment by Red-M** [comment]
In retrospect, this should be noted in the documentation that `.kill()` will not work correctly on windows.
I'm happy for a PR to either change `.kill()` on windows to do such calls as you've mentioned or fix the documentation or both.
