### ISSUE TITLE
sort out migration from sourceforge.net

### ISSUE THREAD

**Issue by ssbarnea** [pexpect/pexpect#68]
I observed only now the move of the project but I fully support it. I didn't had any time for pexpect but maybe it would help to do some cleanup on sf.net so people will not be redirected to the wrong location.

Can I remove the bugs of SF? Or other sections from:
https://sourceforge.net/p/pexpect/admin/tools?limit=200&page=0

**Comment by jquast** [comment]
Closing, nobody has so far reported confusion about having moved from sourceforge. The banner, "As of 2014-06-03, this project may now be found at https://github.com/pexpect/pexpect." seems to be very successful so far in driving issue reporters and code hunters here.
