### ISSUE TITLE
How to press function F7 to PXSSH session

### ISSUE THREAD

**Issue by MuhammadWaqar96** [pexpect/pexpect#682]
Hi ,

i am unable to execute function+f7 command on pxssh session.

**Comment by Red-M** [comment]
You'll need to look up what key character that is in binary and send that to the remote session.

I heavy do not encourage the use of pxssh anymore as alternate solutions work way better in many aspects. [As per the notice on the documentation](https://pexpect.readthedocs.io/en/stable/api/pxssh.html)
