### ISSUE TITLE
Can't set prompt...

### ISSUE THREAD

**Issue by KeithProctor** [pexpect/pexpect#687]
I recently integrated pexpect.spawn() for local testing and pxssh.pxssh() remote testing into my unittest framework.  Before integration I tested local and remote operations against MacOS 10.15.  Which worked fine.  After integration... I moved to remote testing of MacOS 11.2.3 and I get the following error.

```test_Auto (__main__.CLI_AutoRestart) ... --- programCnt: 		0
--- EX1a: 		

> Connection Error: could not set shell prompt (received: "Last login: Wed May 12 21:46:01 2021 from
> theIP\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r 
> \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hu\x08unset
> PROMPT_COMMAND\x1b[?2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                              
> \r \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hP\x08PS1='[PEXPECT]\\$ '\x1b[?
> 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004hs\x08set prompt='[PEXPECT]\\$ '\x1b[
> 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r 
> \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004h", expected: '\\[PEXPECT\\][\\$\\#] ').


--- EX2: 		
--- programCnt: 		0
--- EX1a: 		
> Connection Error: could not set shell prompt (received: "Last login: Wed May 12 22:00:45 2021 from
> theIP\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hu\x08unset
> PROMPT_COMMAND\x1b[?2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               
> \r \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hP\x08PS1='[PEXPECT]\\$ '\x1b[?
> 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004hs\x08set prompt='[PEXPECT]\\$ '\x1b[?
> 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004h", expected: '\\[PEXPECT\\][\\$\\#] ').
--- EX2: 		
FAIL

======================================================================
FAIL: test_Auto (__main__.CLI_AutoRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cliAutoRestart.py", line 61, in test_Auto
    tAutoRestart( td )
  File "cliAutoRestart.py", line 19, in tAutoRestart
    res = tDoCLITest( td )
  File "/Users/userName/Programming/Projects/Work/Source/QA/19/fms-admin-cli/Tests/cli.py", line 397, in tDoCLITest
    verifyCLI( cliOutput, td )
  File "/Users/userName/Programming/Projects/Work/Source/QA/19/fms-admin-cli/Tests/cli.py", line 423, in verifyCLI
    ti.ExactVerify( curCLIVal, cliOutput, 'CLI: ' + str( curCLIVal ))
  File "/Users/userName/Programming/Projects/Work/Source/QA/19/fms-admin-cli/Tests/../../fms-python-utilities/TestInfo.py", line 147, in ExactVerify
    return self.Verify( baseStr, '^' + str( findStr ) + '$', note )
  File "/Users/userName/Programming/Projects/Work/Source/QA/19/fms-admin-cli/Tests/../../fms-python-utilities/TestInfo.py", line 176, in Verify
    assert result, 'Note: ' + str( note ) + ': Result: ' + str( findStr ) \
AssertionError: Note: CLI: Error: 11000 \(Invalid command\): Result: ^Last login: Wed May 12 22:00:45 2021 from 17.150.213.86
userName@kp-m8 ~ % unset PROMPT_COMMAND
userName@kp-m8 ~ % PS1='[PEXPECT]\$ '
[PEXPECT]\$ set prompt='[PEXPECT]\$ '
[PEXPECT]\$ $ Expected: Error: 11000 \(Invalid command\)

----------------------------------------------------------------------
Ran 1 test in 62.893s

FAILED (failures=1)
 *** Length: 0:01:03.298291
 *** Validations: 2
----------------------------------------------------------------------
```

As you can see, in the last few lines, it does make a connection to the server as userName@kp-m8 is the correct prompt on that server and the prompt does get set.  After PS1='[PEXPECT]\$ ' the correct prompt is displayed.  Unfortunately, I think some sort of ansii terminal issue is occurring and Expect cannot read the terminal coming back.  If I'm right what can I do about this.  I think that PExpect is getting out of sync and my command is being run when the system isn't ready.

**Comment by KeithProctor** [comment]
Thought I would come back and verify that this only happens when Pexpect SSH's into MacOS 11.  It does not happen on MacOS 10.15.

**Comment by dstromberg** [comment]
I think this is because macOS' default shell is /bin/zsh.  I'm encountering a similar issue with a macOS 11.5.1 host using an account with /bin/zsh as its shell. If I change its shell to /usr/local/bin/bash (from homebrew), pxssh is happy with the same account.

I think zsh needs:
self.PROMPT_SET_ZSH = r"PS1='[PEXPECT]$ '"
...in pxssh.__init__, and code to use it in pxssh.set_unique_prompt.

PROMPT_SET_ZSH is the same as PROMPT_SET_SH, except there's no backslash before the dollar sign.

**Comment by dstromberg** [comment]
BTW, there's a PTY-like interface in Windows 10, I gather:
https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by Red-M** [comment]
> I think this is because macOS' default shell is /bin/zsh. I'm encountering a similar issue with a macOS 11.5.1 host using an account with /bin/zsh as its shell. If I change its shell to /usr/local/bin/bash (from homebrew), pxssh is happy with the same account.

No, this is due to the prompt not matching.
Clearly shows it in the exception message:

> > Connection Error: could not set shell prompt (received: "Last login: Wed May 12 21:46:01 2021 from
> > theIP\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r 
> > \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hu\x08unset
> > PROMPT_COMMAND\x1b[?2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                              
> > \r \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hP\x08PS1='[PEXPECT]\\$ '\x1b[?
> > 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> > \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004hs\x08set prompt='[PEXPECT]\\$ '\x1b[
> > 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r 
> > \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004h", expected: '\\[PEXPECT\\][\\$\\#] ').


Considering this is a default and you can change this at any time, I'd suggest read the documentation on what you'll need to change, the [`PROMPT` attribute of and instanced `pxssh.pxssh()` object](https://pexpect.readthedocs.io/en/stable/api/pxssh.html#pexpect.pxssh.pxssh.PROMPT) is probably the best starting point.

Just note that pxssh isn't the recommended way to handle remotely controlling SSH, as per the [information box on pxssh's documentation](https://pexpect.readthedocs.io/en/stable/api/pxssh.html). Please also keep in mind that pxssh is just a text scrapper strapped to an SSH client, something a little more integrated into SSH (like the other libraries listed in the documentation) are a bit more understanding of the situation they're in.

> I think zsh needs:
> self.PROMPT_SET_ZSH = r"PS1='[PEXPECT]$ '"

This won't work and will break many other people's systems because `\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\\$ \x1b[K\x1b[?2004h` isn't going to be matched by `[PEXPECT]$ `. What needs to happen is that colours and and formatting in the terminal needs to be turned off by setting the [following option and using `auto_prompt_reset=False`](https://pexpect.readthedocs.io/en/stable/api/pxssh.html#pexpect.pxssh.pxssh.PROMPT) to not automatically set the prompt, so that you can prepare the terminal then allow the prompt to be set correctly on the remote session and for the regex that will match a prompt line.

**Comment by KeithProctor** [comment]
Hey just trying to refocus this issue.  After connection pexpect API is tries to change the prompt.  I believe pexpect requires a specific prompt and is used to validate completion of a command.  The issue does NOT happen locally but does happen remotely.  Same OS on both sides.  So it's more about the shell environment NOT that Bash or ZSH is being used.  Finally, this is for automation and I won't have control of the environment on the other side.  Hope this helps understand the issue more.  TY!!

**Comment by dstromberg** [comment]
> > I think this is because macOS' default shell is /bin/zsh. I'm encountering a similar issue with a macOS 11.5.1 host using an account with /bin/zsh as its shell. If I change its shell to /usr/local/bin/bash (from homebrew), pxssh is happy with the same account.
> 
> No, this is due to the prompt not matching.
> Clearly shows it in the exception message:
> 
> > > Connection Error: could not set shell prompt (received: "Last login: Wed May 12 21:46:01 2021 from
> > > theIP\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> > > \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hu\x08unset
> > > PROMPT_COMMAND\x1b[?2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m
> > > \r \r\r\x1b[m\x1b[m\x1b[m\x1b[JuserName@kp-m8 ~ % \x1b[K\x1b[?2004hP\x08PS1='[PEXPECT]\$ '\x1b[?
> > > 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> > > \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\$ \x1b[K\x1b[?2004hs\x08set prompt='[PEXPECT]\$ '\x1b[
> > > 2004l\r\r\n\x1b[1m\x1b[7m%\x1b[m\x1b[1m\x1b[m                                                                               \r
> > > \r\r\x1b[m\x1b[m\x1b[m\x1b[J[PEXPECT]\$ \x1b[K\x1b[?2004h", expected: '\[PEXPECT\][\$\#] ').

I know it's about the prompt, but it's also about the shell.  Between zsh and bash, \$ in a prompt string has different meanings.

**Comment by KeithProctor** [comment]
except is suppose to change the prompt so it's functionality will work.  It's failing to change the prompt.

**Comment by dstromberg** [comment]
> The pexcept API is suppose to change the prompt so it's functionality will work. It's failing to change the prompt.

Actually, zsh sets the prompt successfully, it just sets it to something unexpected by pexpect because of a prompt escape code difference.

Should I cut and paste so you can see it?

**Comment by KeithProctor** [comment]
That sounds like a likely description of what is happening.  Either way though pexpect API is still NOT successful at setting the prompt and should be considered a bug for pexpect to fix.  IOW:  Be sure that the prompt is set.  So additional functionality works later.
