### ISSUE TITLE
pexpect causing SSH ControlPersist socket to be removed when using a jump host

### ISSUE THREAD

**Issue by TurboTurtle** [pexpect/pexpect#688]
Currently, we're using pexpect to initiate an SSH login that uses the ControlPersist feature so that we can run commands on remote hosts. This works well - the control socket is created, login handling is straight-forward enough, all is good.

Here's an example of the command currently being run via `spawn()`:

```
ssh <key if used>  -oControlPersist=600 -oControlMaster=yes -oStrictHostKeyChecking=no -oControlPath=<path> <user>@<host> \"echo Connected\"
```
Again, this works as expected - after `spawn.close()` the control socket remains and we can leverage that for our command execution.

However, I'm now trying to add the ability to use a jump/bastion host (the `-J` option for ssh) and I've found that when using pexpect the control socket gets removed after the initial connection closes with `spawn.close()`. The command when run manually in a shell works as expected and the control socket doesn't get removed until the set time expires. This is the command being run, as you can see the only difference is `-J`:

```
ssh <key if used> -J <jump_host>  -oControlPersist=600 -oControlMaster=yes -oStrictHostKeyChecking=no -oControlPath=<path> <user>@<host> \"echo Connected\"
```

Caveat: ssh documents that for key auth with jump hosts, you need to configure it in `~/.ssh/config`. This is accounted for in these attempts.

Normally I'd say this is thoroughly an ssh bug, but since I can only reproduce it via `pexpect.spawn()`, I'm wondering if there is something happening (or not happening) under the hood of `spawn` that may be triggering the removal of the socket. For the record I've tried values of 600, 0, and 'yes' for `-oControlPersist` and it is all the same behavior - socket removed after initial connection closes with `spawn.close()`.

**Comment by TurboTurtle** [comment]
Oh, would probably help:

Fedora 33
python3-pexpect-4.8.0-5.fc33.noarch
openssh-8.4p1-5.fc33.x86_64

**Comment by Red-M** [comment]
The pty that is spawned is killed when `.close()` is called, so any child processes that would rely on the initial parent process being there (eg, a background process that is forked from your initial SSH client to keep the SSH connection to the jump server) is killed too.
