### ISSUE TITLE
Weird utf-8 and backspace behaviour of Python's `input()` inside the spawned shell

### ISSUE THREAD

**Issue by pomidoroshev** [pexpect/pexpect#689]
Hi! Working under `poetry shell` (https://github.com/python-poetry/poetry) which spawns a new shell with [`pexpect.spawn()`](https://github.com/python-poetry/poetry/blob/9591e88492508d4dba260952d53266a0032c04c7/poetry/utils/shell.py#L72) I faced a problem which led me to this repository.

Say, I run `poetry shell` and then I want to execute Python's `input()` function, type some Cyrillic letters, remove two of them pressing Backspace and print the result:

```
> poetry shell
Spawning shell within <...>
source <...>/bin/activate.fish
<...>
> python -c 'print(input())'
жжжж <then backspace twice>
жжж
```

As you can see, there were four letters, I removed two of them, and then I got three letters instead of two. If I press backspace three times, there will be something like this:

```
> python -c 'print(input())'
жжжж <backspace three times>
жж�
```

The last character is `\udcd0`, it's a half of this letter.

Btw, everything works fine if I run `python` right from venv, without spawning a shell.

---

Minimal example with `bash` and direct `pexpect` usage:

```
bash-3.2$ python -c "import pexpect;c = pexpect.spawn('/bin/bash');c.interact();c.close()"
bash-3.2$ python -c 'print(input())'
жжжж <backspace twice>
жжж
bash-3.2$ exit  # quit pexpect
exit
bash-3.2$ python -c 'print(input())'
жж <backspace twice>
жж
```

Of course, you can use any unicode symbol here.

---

Python 3.9.4
macOS 11.3
pexpect 4.8.0

**Comment by Red-M** [comment]
pexpect is not a terminal emulator, sorry.
