### ISSUE TITLE
Pexpect pattern ".+" not worked as documented. 

### ISSUE THREAD

**Issue by atline** [pexpect/pexpect#692]
From [official document](https://pexpect.readthedocs.io/en/stable/overview.html?highlight=after#beware-of-and-at-the-end-of-patterns), it mentioned next:

> **Beware of + and * at the end of patterns**
> Remember that any time you try to match a pattern that needs look-ahead that you will always get a minimal match (non greedy). For example, the following will always return just one character:
> `child.expect ('.+')`
> 
> This example will match successfully, but will always return no characters:
> `child.expect ('.*')`

But my next code:

__test.py:__

```
import pexpect
import sys

p = pexpect.spawn("ping 10.192.225.199", encoding="utf-8")
while True:
    try:
        index = p.expect([".+", pexpect.EOF, pexpect.TIMEOUT], timeout=1)
        if index == 0:
            print("===")
            print(p.after)
            print("===")
    except Exception as e:
        print(e)
```

The execution will output:

```
$ python3 test.py
===
PING 10.192.225.199 (10.192.225.199) 56(84) bytes of data.

===
===
64 bytes from 10.192.225.199: icmp_seq=1 ttl=63 time=0.607 ms

===
===
64 bytes from 10.192.225.199: icmp_seq=2 ttl=63 time=0.587 ms

===
...
```

Why every `print(p.after)` not just output one character as documentation said? It print whole line.

And, if I change `.+` to `.*`, for this, the output behavior is just same as documentation said: every time the `print(p.after)` output empty.

Why `.+` not works as documentation said? Possible bug or documentation issue?  
I also raise the question in [so](https://stackoverflow.com/questions/68221694/what-does-pexpect-pattern-do), but did not get a clear answer, so need you help to confirm if it's a bug？

**Comment by atline** [comment]
If possible the document as some out of date for next:

> For example, the following will always return just one character:
> child.expect ('.+')

I also tried this, but its behavior not same with document:

```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexpect
>>> import time
>>> p = pexpect.spawn("ping -c 4 10.192.225.199", encoding="utf-8")
>>> time.sleep(10)
>>> p.expect(".+")
0
>>> p.after
'PING 10.192.225.199 (10.192.225.199) 56(84) bytes of data.\r\n64 bytes from 10.192.225.199: icmp_seq=1 ttl=63 time=0.333 ms\r\n64 bytes from 10.192.225.199: icmp_seq=2 ttl=63 time=0.582 ms\r\n64 bytes from 10.192.225.199: icmp_seq=3 ttl=63 time=0.584 ms\r\n64 bytes from 10.192.225.199: icmp_seq=4 ttl=63 time=0.592 ms\r\n\r\n--- 10.192.225.199 ping statistics ---\r\n4 packets transmitted, 4 received, 0% packet loss, time 3063ms\r\nrtt min/avg/max/mdev = 0.333/0.522/0.592/0.113 ms\r\n'
>>> p.before
''
```

**Comment by atline** [comment]
Hello, maintainers,

Could you kindly confirm if next sentence in doc outdated or not?

> For example, the following will always return just one character:
> child.expect ('.+')

**Comment by Red-M** [comment]
`.after()` is for the text received after the matching regex.
That documentation is talking about `.before()`
