### ISSUE TITLE
output is messy

### ISSUE THREAD

**Issue by alexkoganov** [pexpect/pexpect#693]
Hi guys

pretty new to python and coding.
i am trying to get a proper output from a swicth that suppose to look like this:
 Status and Counters - VLAN Information

  Maximum VLANs to support : 64                   
  Primary VLAN : DEFAULT_VLAN
  Management VLAN :             

  VLAN ID Name                             | Status     Voice Jumbo
  ------- -------------------------------- + ---------- ----- -----
  1       DEFAULT_VLAN                     | Port-based No    No   
  10      Switch_mgmt                      | Port-based No    No   
  16      VLAN16                           | Port-based No    No   
  17      VLAN17                           | Port-based No    No   
  20      VLAN20                           | Port-based No    No   
  21      VLAN21                           | Port-based No    No   
  23      VLAN23                           | Port-based No    No   
  24      VLAN24                           | Port-based No    No   
  28      VLAN28                           | Port-based No    No   
  99      VLAN99                           | Port-based No    No   
  260     VLAN260                          | Port-based No    No   
 

but instead it looks like this:
b' \x1b[24;1H\x1b[24;36H\x1b[24;1H\x1b[?25h\x1b[24;36H\x1b[24;36Hsh vlan\x1b[24;36H\x1b[?25h\x1b[24;43H\x1b[1;0H\x1b[1M\x1b[24;1H\x1b[1L\x1b[24;43H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1H\r\r\n\x1b[?25h\x1b[24;1H\x1b[?25h\x1b[24;1H\r\n Status and Counters - VLAN Information\r\n\r\n  Maximum VLANs to support : 64                   \r\n  Primary VLAN : DEFAULT_VLAN\r\n  Management VLAN :             \r\n\r\n  VLAN ID Name                             | Status     Voice Jumbo\r\n  ------- -------------------------------- + ---------- ----- -----\r\n  1       DEFAULT_VLAN                     | Port-based No    No   \r\n  10      Switch_mgmt                      | Port-based No    No   \r\n  16      VLAN16                           | Port-based No    No   \r\n  17      VLAN17                           | Port-based No    No   \r\n  20      VLAN20                           | Port-based No    No   \r\n  21      VLAN21                           | Port-based No    No   \r\n  23      VLAN23                           | Port-based No    No   \r\n  24      VLAN24                           | Port-based No    No   \r\n  28      VLAN28                           | Port-based No    No   \r\n  99      VLAN99                           | Port-based No    No   \r\n  260     VLAN260                          | Port-based No    No   \r\n \r\n\r\n\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1HMTR-F-1-SW-LAB-R4-4-SW166(config)'
10.210.100.166 :  DONE

what should i consider when building a script when working with networking appliances ?

my simple code :

def hp_general_ssh(ip):

    try:
        child = pexpect.spawn(f'ssh -o StrictHostKeyChecking=no <user>@{ip}')
        child.expect('password:')
        child.sendline('<pass>')
        child.expect('Press any key to continue',timeout=10)
        child.sendline('\n')
        child.expect('#',timeout=10)
        child.sendline('conf t')
        child.expect('#',timeout=10)
        child.sendline('sh vlan')
        child.expect('#',timeout=10)
        child.sendline('\n')
        child.expect('#',timeout=10)
        print(child.before)
        print(ip,":"," DONE")

tnx

**Comment by Red-M** [comment]
[I'd suggest using something else to automated SSH than pexpect (as per the information note on this page)](https://pexpect.readthedocs.io/en/stable/api/pxssh.html) but what is happening here is that the network device on the other end is detecting you have a compatible terminal to send colours and formatting, so what you can do is either tell the SSH server to turn it off (if the remote server supports it via a command) or to disable it via setting the terminal string in the environment to something that doesn't support colours and formatting.

**Comment by alexkoganov** [comment]
Tnx Red-M
i am using OpenSSH_7.6p1 Ubuntu-4ubuntu0.3.
