### ISSUE TITLE
pxssh - "Could not synchronize with original prompt"

### ISSUE THREAD

**Issue by firefox1990** [pexpect/pexpect#7]
Hey,

I have tested your pxssh example (http://pexpect.readthedocs.org/en/latest/api/pxssh.html). When I tried to connect to the SSH Server it says "pxssh failed on login. could not synchronize with original promt.". I tried several ways to solve it. 
An interessting thing: After removing .ssh/known_hosts the login was successfull. A second login gave me the error again. Any ideas?

Thanks!

**Comment by jquast** [comment]
Thanks, I can only suggest, maybe because it is embedded that the prompt could have been slow? This debug script has 1-second timeouts, I would suggest increasing the timeouts if it happens again, thanks for the report
