### ISSUE TITLE
Unable to call read_nonblocking after expect()

### ISSUE THREAD

**Issue by MarkBaggett** [pexpect/pexpect#702]
Is it expected behavior for expect to consume all of the data in the processes output buffer?  How would I read the data after an expected value when I do not have any known character to expect after it?

This example generates an EOF even though there is still unread data generated by the process (6789).

```
>>> proc = pexpect.spawn("echo '123456789'")
>>> proc.read_nonblocking(2, 5)
b'12'
>>> proc.expect("5",90)
0
>>> proc.before
b'34'
>>> proc.after
b'5'
>>> proc.eof()
False
>>> proc.read_nonblocking(2, 5)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
```

This example generates a timeout even though the expected value "should be*" in the buffer.

* At least it should be in my possibly flawed understanding of how this works.

```
>>> proc = pexpect.spawn("bash -c 'echo 123456789; while [ 1 ]; do sleep 1; done")
>>> proc.read_nonblocking(2, 5)
b'12'
>>> proc.expect("5",90)
0
>>> proc.before
b'34'
>>> proc.after
b'5'
>>> proc.eof()
False
>>> proc.read_nonblocking(2, 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.
```

But it works fine when done individually.

``
>>> proc = pexpect.spawn("bash -c 'echo 123456789; while [ 1 ]; do sleep 1; done")
>>> proc.read_nonblocking(2, 5)
b'12'
>>> proc.read_nonblocking(2, 5)
b'34'
>>> proc.read_nonblocking(2, 5)
b'56'
>>> proc.read_nonblocking(2, 5)
b'78'
>>> proc.read_nonblocking(2, 5)
b'9\r'
>>> proc.read_nonblocking(2, 5)
b'\n'
>>> proc.read_nonblocking(2, 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.
>>> proc = pexpect.spawn("bash -c 'echo 123456789; while [ 1 ]; do sleep 1; done")
>>> proc.expect("12",5)
0
>>> proc.expect("56",5)
0
>>> proc.expect("89",5)
0
>>> proc.expect("\r\n",5)
0
>>> proc.expect("\r\n",)
... times out as expected.
```

**Comment by Red-M** [comment]
>Is it expected behavior for expect to consume all of the data in the processes output buffer?

This is dependant entirely on what you're trying to do, but generally speaking, you `expect()` for a known string which is something you "react" to. At this stage you can either do something else entirely because you know that a command has done something and you don't need the output OR you parse the output and keep interacting with the output from the PTY.

>How would I read the data after an expected value when I do not have any known character to expect after it?

Are you asking me to explain how to expect something that is unexpected?

**Comment by MarkBaggett** [comment]
_"Are you asking me to explain how to expect something that is unexpected? (I am confused)"_

lol... yes.  I suppose I am.  :)    Seems like a silly question when you boil it down like that.   But I think the answer is to use .read() instead of read_nonblocking().  Because read_nonblocking() raises an exception if an EOF was raised I was running into problems reading the rest of the output when I didn't know for what to expect.  Rereading the documentation got me the answers I needed and I forgot I had even opened this ticket.   Is reRTFM a thing? Thank you for taking the time to respond and for supporting this module.

**Comment by Red-M** [comment]
I'm glad you figured it out and got my humour.
We get a lot of issues like this and most of the time, letting the other person figure it out on their own is better for everyone.
