### ISSUE TITLE
Cannot send a file with sendline

### ISSUE THREAD

**Issue by flixman** [pexpect/pexpect#704]
I am establishing a ssh connection, and during the authentication phase I need to send a token. Right now I am reading the contents of the file on a variable and then sending it like:
```python
child = pexpect.spawn('ssh gateway', encoding='utf-8')
child.expect('Please provide a token or press ENTER')
print('sending token length: {}'.format(len(token)))
nbytes=child.sendline(token)
print('sent token length: {}'.format(nbytes))
```
on this code ```python len(token) == nbytes```, and equals to 1166, so everything is sent as expected. However, on the other end of the connection, I receive only 1023 (so, the token gets partially received).

The same flow has been performed by a .Net application flawlessly for years, which means that a) the other end of the connection is behaving as expected, and b) there is something in my environment playing me off :-/. As a side note, as I do not know if this is the reason for this issue, I have seen there is a remark on the documentation of send, about PC_MAX_CANON, saying it should be 4096 in Linux. In my computer, running CentOS 8.4, I get the following:

```python
>>> from os import fpathconf
>>> print(fpathconf(0, 'PC_MAX_CANON'))
255
```
Is this a problem on pexpect? on my system? on both?

**Comment by Red-M** [comment]
I don't recommend using pexpect for ssh as you out on a lot of features from other ssh libraries that you might want to use in the future.

I could recommend a `flush()` call after the `send()` because it might be in a buffer.
