### ISSUE TITLE
Pexpect Infinite timeout.

### ISSUE THREAD

**Issue by A-noximous** [pexpect/pexpect#707]
I'm hosting a Minecraft Server for a few friends, and I tried to use a combination of pexpect and urwid to make the server console better([Here](https://github.com/A-noximous/py-ServerTerminal)) However, I'm having issues with the Pexpect's timeout, as if nothing is read or sent to the server, the timeout is exceeded and my server stops. Is there anyway to fix this apart from some sort of keep alive?(eg: sending a command to the server every now and then to reset the timeout).

**Comment by ElisonLima** [comment]
as I understand it, you need a timeout change at runtime, is that it?
