### ISSUE TITLE
Control writing speed in send() and sendline()

### ISSUE THREAD

**Issue by nabaco** [pexpect/pexpect#714]
Related to #231. In some cases I need to control the speed of the stream sent through send() or sendline().
In TCL Expect I can do:
```tcl
set send_human {.1 .3 1 .05 2};
send -h "Type like a human";
set send_slow {10 .1};
send -s "Type slowly";
```

See TCL expect's man page for the `send` command: https://www.tcl.tk/man/expect5.31/expect.1.html
There is no such option in pexpect. Would be glad if you could add that.

**Comment by Red-M** [comment]
PRs are always welcome.
