### ISSUE TITLE
Spurious space-backspace in output

### ISSUE THREAD

**Issue by metageek** [pexpect/pexpect#716]
I'm using pexpect to drive a database repl, for testing. In tests with large amounts of output (say, 100+ lines), sometimes we see a spurious space+backspace sequence (bytes 32 and 8) in the log. Apparently this is a known problem with expect (citation needed), and now we're seeing the same thing with pexpect. Is this something known? I wouldn't be surprised if it were a deliberate emulation of expect, to keep compatibility; if that's the case, I'll probably try to submit a patch to make it optional.

Thanks! Apologies if this is a FAQ; I did search the issues, but didn't find anything.

**Comment by Red-M** [comment]
I'd need to see example code and output of this and a repeatable test which also agrees with what you're saying.
If this is such an issue in expect and is widely known I'd expect to see something to agree with this but this is the first time I've heard and/or seen of such an issue.

Sometimes these kinds of issues are not in (p)expect but are in your environment (#669) and its better for compatibility and transparency that pexpect not remove any characters but instead provide the rawest output available to allow the user the most control over how to handle such data.

If you were to provide a PR to "make it optional", I'd be very surprised to find the code that actually does this.

**Comment by metageek** [comment]
Unfortunately, I can't provide repo code, because it's too flaky.

I'm going to look into whether it's actually a bug in the program I'm controlling, and close this.
