### ISSUE TITLE
Line isn't executed when sending a command + the os linesep to Nushell

### ISSUE THREAD

**Issue by efugier** [pexpect/pexpect#721]
### Bug description

Line isn't executed when sending a command + the os line separtor to Nushell through `pexpect`.

not sure on which side the issue is so I created one in both repo!

### How to reproduce

in a `test.py` file

```python
import pexpect

c = pexpect.spawn("nu", ["-i"])
c.setecho(False)
c.sendline("echo aaa")
c.interact(escape_character=None)
```

then

```
python test.py
```

output

```
❯ python test.py
❯ echo aaa
```
last line is pre-filled but bot executed

### Expected behavior

```
❯ python test.py
aaa
❯
```

### Additional context

Discovered when doing this https://github.com/python-poetry/poetry/pull/6063

relevant issue on the nushell repo: https://github.com/nushell/nushell/issues/6225

**Comment by Red-M** [comment]
Pexpect can't be expected to support every executable under the sun, as far as I can see this is an issue with this particular shell.
Please re-open this if the nushell developers can confirm that this is an issue caused by pexpect but every other shell works.

**Comment by efugier** [comment]
Sounds good to me, I do think it's more on nushell's side :slightly_smiling_face:
