### ISSUE TITLE
Update docs to use context manager when it is possible

### ISSUE THREAD

**Issue by rafrafek** [pexpect/pexpect#727]
I think having examples of how to use `pexpect` with context manager in the docs would be great.

For example how to spawn process here:

https://pexpect.readthedocs.io/en/stable/api/pexpect.html

Similar comment: https://github.com/pexpect/pexpect/issues/111#issuecomment-462402865

**Comment by Red-M** [comment]
This is only possible for `pexpect.spawn()` AFAIK, I'm not sure why the documentation doesn't list this but we do have tests for this.
A PR is welcome to add the documentation if you'd like to.
