### ISSUE TITLE
GitHub Actions: allow actions/checkout@v3 and actions/setup-python@v4

### ISSUE THREAD

**Issue by swt2c** [pexpect/pexpect#738]
Hi @Red-M, the GitHub actions setup is not working correctly because the repository is not configured to allow these actions:
actions/checkout@v3 and actions/setup-python@v4.  Can you please update the GitHub configuration to enable this?  This is the error being reported:

```
Error: .github#L1
actions/checkout@v3 and actions/setup-python@v4 are not allowed to be used in pexpect/pexpect. Actions in this workflow must be: within a repository owned by pexpect.
```

See: https://github.com/pexpect/pexpect/actions/runs/4071108953

**Comment by Red-M** [comment]
Let me see how I can enable that.

**Comment by Red-M** [comment]
I've fixed that
