### ISSUE TITLE
Are there any plans to release a new version?

### ISSUE THREAD

**Issue by GasonChen** [pexpect/pexpect#746]
Hi @Red-M, are there any plans to release a new version?

**Comment by Red-M** [comment]
I'm waiting on a few PRs to be merged first as they have features and fixes that need to be in the next release.
I can't give a timeline on that other than, "its ready when its ready".

I don't want to drag a release out but at the same time I don't want to release every time a new commit is in the repo.
Async fixes for newer versions of Python and a few bug fixes are the main contenders as stable release versions are better than rushing something out for the latest and greatest.

If you'd like the latest and greatest, there is nothing wrong with using the latest master as a target for pip to install but you will lose out on all the stability that a fully released version would have.
