### ISSUE TITLE
run() does not raise TIMEOUT or EOF

### ISSUE THREAD

**Issue by devenyiat** [pexpect/pexpect#754]
run() method silently absorbs TIMEOUT and EOF exceptions raised during command execution. Although it returns after timeout, given no exception raised you can believe the command successfully ran which can be misleading.

Suggestion: run() should handle TIMEOUT and EOF events the same way as expect() does, raising respective exceptions if not overridden with events parameter.

**Comment by Red-M** [comment]
https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.run
>If you set ‘withexitstatus’ to true, then run will return a tuple of (command_output, exitstatus). If ‘withexitstatus’ is false then this returns just command_output.

From the [same page](https://pexpect.readthedocs.io/en/stable/api/pexpect.html#module-pexpect):
>This is a handy replacement for os.system().

>The spawn class is the more powerful interface to the Pexpect system.

If you want to have more information than something that is designed to be little more than `os.system()` can provide, use `pexpect.spawn()`.

A change like this would not be backwards compatible and could be provided via your own custom class.
