### ISSUE TITLE
PEP-0561 pexpect is not typed (py.typed)

### ISSUE THREAD

**Issue by ssbarnea** [pexpect/pexpect#759]
It seems that pexpect is one of the few popular python libraries which still did not add type hints.

Related:
- https://peps.python.org/pep-0561/
- https://peps.python.org/pep-0484/
- https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/

**Comment by Red-M** [comment]
Related: #706
