### ISSUE TITLE
Issue with Select module

### ISSUE THREAD

**Issue by UP929312** [pexpect/pexpect#761]
```py
def interface_with_saml2aws(file_location: str, password: str) -> list[str]:
    child = pexpect.spawn(command=file_location, args=["login", "--force", "--skip-prompt", f"--password={password}"], maxread=100000)
    # Send initial command ==========
    child.send(os.linesep)
    child.read_nonblocking(10000, timeout=5)  # This is needed
    # Press enter (for preset email)
    child.send(password + os.linesep)
    child.read_nonblocking(100, timeout=5)
    child.read_nonblocking(100, timeout=25)
    child.read_nonblocking(100, timeout=25)
    verification_code = input("Enter verification code: ")
    child.send(verification_code + os.linesep)
    data = child.read_nonblocking(100, timeout=5)
    ##########################
    print(">>>>>>>> Gets to here")
    child.read_nonblocking(1, timeout=None)  # This is needed
    print(">>>>>>>> Doesn't get to here")
    ##########################
    output = child.read_nonblocking(10000, timeout=-1)
    print(f"Final {output=!s}")
    return []
```
However, as you can see, it won't pass the child.read_nonblocking line, even though it's trying to read 1 byte.
After further debugging, I can see that it gets stuck on this line, from the default select library:
```py
return select.select(iwtd, owtd, ewtd, timeout)
```
Which is in the utils file from this library:
```py
def select_ignore_interrupts(iwtd, owtd, ewtd, timeout=None):
```

It will just hang forever, before the regular method times out.
I am running an M2 Mac, and trying to interface with a tool called saml2aws.
Running latest version of MacOS
Also tried with
```py
use_poll=True
```

**Comment by UP929312** [comment]
@Red-M Is this something that the library can support working, or is there anything I can do in this case?

**Comment by UP929312** [comment]
@Red-M I hate to keep pinging you, but I really need help, any would be very much appreciated

**Comment by Red-M** [comment]
Not an issue with pexpect, `select.select()` is a python wrapper around your operating system's `select()` C call. You should more closely inspect the output from your program and additionally using an `expect()` call instead of arbitrarily reading data with a timeout.

Please do not ping people like this again.
