### ISSUE TITLE
Support for new release

### ISSUE THREAD

**Issue by fcollonval** [pexpect/pexpect#762]
Hey @Red-M 

Is there something I can do to help having a new release out that works with 3.11 (and 3.12 - final is around the corner)?

**Comment by Red-M** [comment]
A release is waiting on async tests being written for https://github.com/pexpect/pexpect/pull/732#issuecomment-1466957747

**Comment by karrukola** [comment]
I have asked @musthafak to provide the tests within the next 2 weeks.
They will be closing issue #752

**Comment by margars** [comment]
Is there any estimate on a new release date?
