### ISSUE TITLE
Docs don't adequately describe use of "match" attribute

### ISSUE THREAD

**Issue by dperkins3600** [pexpect/pexpect#77]
When a pattern is specified in an expect method, and a match occurs, the attribute 'match' is set to an RE match object (type is _sre.SRE_Match).  There are interesting operations that can be done using the match object. It has attribute string, and methods group, groups, groupdict, start, end, span, and expand.
However, if there was a match on pexpect.EOF or pexpect.TIMEOUT, the type of the "match" attribute is not _sre.SRE_Match!
Also note that if method expect_exact is used, the result has type str (string) and not type _sre.SRE_Match!
It appears that attribute 'before' is always of the type 'str'.

**Comment by jquast** [comment]
Superseded by pull request #252
