### ISSUE TITLE
Incorrect DEVELOPERS.rst

### ISSUE THREAD

**Issue by rosik** [pexpect/pexpect#771]
Subj: [DEVELOPERS.rst (permalink)](https://github.com/pexpect/pexpect/blob/6e2bbd5568fb8468c176c2c9b7f20d4f4bf7dd71/DEVELOPERS.rst)

It doesn't provide much information. No installation commands are listed. And `pytest` is misspelled for some reason.

**Comment by Red-M** [comment]
PRs are always welcome.
