### ISSUE TITLE
Time for a release: any reason to delay?

### ISSUE THREAD

**Issue by dluyer** [pexpect/pexpect#779]
@Red-M @takluyver @jquast @noahsquaretrade @jdemeyer 

The latest release doesn't work with Python 3.11 due to the async changes.

Should we cut a release in the next couple of days?  Is there any pending change or anything which needs more testing?

**Comment by Red-M** [comment]
I've been meaning to cut the release but the changelog needs to be updated.

**Comment by Red-M** [comment]
I've released the latest version now.
I'm not sure if we should document this a little more clearly so other people can do this but evaluating when a release is best to release might be difficult as its mostly a feels based thing, I might think about that a little bit as well.

**Comment by dirkmueller** [comment]
could you please also add a source distribution to the pypi release? currently it only has a wheel

**Comment by Red-M** [comment]
I can but its a pure python package already

**Comment by dirkmueller** [comment]
Thanks, works great!
