### ISSUE TITLE
add contribution documentation

### ISSUE THREAD

**Issue by eleanorjboyd** [pexpect/pexpect#792]
Hello!

For another project I was looking through a variety of python repos on github and trying to get them working in a dev environment. My goal can be boiled down to wanting to clone the repo and then run the tests of the repo since running tests helps me verify if my dev environment is configured correctly. I was successfully able to do so on your repo but found no written location of these steps on your repo which might help others. Could you add a contribution.md or something similar explaining the install steps for this repo? The ones I took (which I am not sure if are exactly correct) was:

1. clone repo from github
2. create a venv and activate this venv
3. install dependencies by running `python -m pip install -e . -r requirements-testing.txt`
4. install pytest with `python -m pip install pytest`
5. run tests with pytest

I also ran into a small issue where I could successfully run up to 14% of the tests but then the test run got stuck for a long period of time, in tests/test_expect.py, not sure if I just didn't wait long enough.

Thanks!

**Comment by Red-M** [comment]
[PRs are welcome.](https://github.com/pexpect/pexpect/blob/master/DEVELOPERS.rst)
