### ISSUE TITLE
The test_spawn_uses_env test fails on some machines

### ISSUE THREAD

**Issue by U2FsdGVkX1** [pexpect/pexpect#799]
https://github.com/pexpect/pexpect/blob/master/tests/test_env.py#L65
This test unit spawns a script, then run the readline & expect function, and then checks whether exitstatus is 0.

https://github.com/pexpect/pexpect/blob/master/pexpect/pty_spawn.py#L709
Normally, exitstatus will be updated indirectly by the expect function. Because after calling readline function, the child process may no longer be alive. So when the expect function is called, the child process must be terminated, otherwise exitstatus will not be updated.
But on some machines, I found that after calling the readline function, the child process has not terminated, causing exitstatus to be None instead of 0, and finally the test_spawn_uses_env test will fail.

I wrote a program and it works as expected on x86 machines.
```
sh-5.2# cat test.py
import pexpect

p = pexpect.spawn("ls /")
p.readline()
p.expect(pexpect.EOF)
print(p.ptyproc.isalive())
print(p.exitstatus)

sh-5.2# python3 test.py
False
0
sh-5.2#
```
However, the situation I mentioned above will occur on some RISC-V machines.
```
sh-5.2# cat test.py
import pexpect

p = pexpect.spawn("ls /")
p.readline()
p.expect(pexpect.EOF)
print(p.ptyproc.isalive())
print(p.exitstatus)

sh-5.2# python3 test.py
True
None
sh-5.2#
```

**Comment by Red-M** [comment]
pexpect is a pure python library and does not have a check for CPU architecture, you need to look at your environment.

**Comment by Xinlong-Chen** [comment]
@U2FsdGVkX1 same question we meet in risc-v machine, did u have any way to deal with it?
