### ISSUE TITLE
API to execute code in child process before execv?

### ISSUE THREAD

**Issue by takluyver** [pexpect/pexpect#81]
I just came across an issue where the parent process was ignoring SIGINT using `signal.signal(SIGINT, SIG_IGN)`, but I wanted the child to be interruptible. The UNIX model has child processes inherit their parents signal handlers on a fork, and while function handlers are reset by exec*, ignore handlers are not. For now, I'm temporarily changing the signal handler, spawning, and changing it back, but this doesn't seem ideal.

I'm thinking of introducing a new optional parameter to `spawn`, which would be None (by default) or a callable taking no arguments. If supplied, it would be called in the child process just before we call execv/execvpe.

This presumably won't work with our upcoming Windows support, because you don't start processes on Windows by forking. I think it's reasonable to raise NotImplementedError in that case.

**Comment by jquast** [comment]
Closing, keyword argument ``preexec_fn`` of ``spawn()`` satisfies this issue.
