### ISSUE TITLE
ANSI doesn't allow nonprintable characters

### ISSUE THREAD

**Issue by dcoshea** [pexpect/pexpect#83]
In 345eb58, in write_ch():

```
if ch not in string.printable:
    fout = open ('log', 'a')
    fout.write ('Nonprint: ' + str(ord(ch)) + '\n')
    fout.close()
    return
```

I would like non-printable characters to be accepted, since I am dealing with data streams that include CP437 line drawing characters.

Obviously it's easy to comment out the above lines, but I think it might make more sense for non-printable characters to be accepted, and to leave it up to the caller to decide what to do with any that they find on the virtual "screen" as they see fit.  Filtering them out, as is currently done, means that other characters do not appear in their correct locations on the screen, unless this is meant to be a way to filter out line noise, in which case you don't want the cursor to be moved when they are filtered out?

**Comment by jquast** [comment]
Closing, pexpect's terminal emulation code remains next release but no longer improved, marked deprecated by https://github.com/pexpect/pexpect/pull/240 Suggest any terminal emulation / screen scraping code efforts moved to more concerted project efforts such as https://github.com/selectel/pyte
