### ISSUE TITLE
ANSI and screen don't support Unicode

### ISSUE THREAD

**Issue by dcoshea** [pexpect/pexpect#84]
It would be nice if the ANSI and screen packages supported Unicode strings, or there were additional packages/classes that did.  I only had to change ```str()``` to ```unicode()``` and add ```u``` in front of the quoted strings (and perhaps even some of that wasn't necessary) in ```screen.pretty()``` and ```put_abs()``` in 345eb58 to get this working quickly for me, but I didn't test all methods.

If you could suggest your preferred solution, I might be able to implement it and submit a pull request.

**Comment by jquast** [comment]
Closing, pexpect's terminal emulation code remains next release but no longer improved, marked deprecated by https://github.com/pexpect/pexpect/pull/240 Suggest any terminal emulation / screen scraping code efforts moved to more concerted project efforts such as https://github.com/selectel/pyte
