### ISSUE TITLE
Exception when non-ASCII character appears in invalid ANSI escape sequence

### ISSUE THREAD

**Issue by dcoshea** [pexpect/pexpect#88]
In 345eb58 (with some changes, including changes to support Unicode), when some serial interface line noise caused garbage, non-ASCII characters to be received by my code, and they happened to be in the middle of an ANSI escape sequence, and this data was passed to an instance of ANSI, an exception occurred because an attempt was made to log the invalid character, and the encoding for the log file was ASCII:

```
Traceback (most recent call last):
  File "pexpect-test.py", line 714, in <module>
    term.process(c)
  File "pexpect.git/pexpect/ANSI.py", line 285, in process
    self.state.process(c)
  File "pexpect.git/pexpect/FSM.py", line 241, in process
    self.action (self)
  File "pexpect.git/pexpect/ANSI.py", line 179, in DoLog
    fout.write (fsm.input_symbol + ',' + fsm.current_state + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2562' in position 0: ordinal not in range(128)
```

I think there are actually a number of other issues with DoLog():
* the log file name "log" is fairly generic;
* the log messages are very cryptic unless you read the code; and
* it would be nice if the caller was able to control the logging in some way, e.g. I might like to write the messages (if they were more intelligible) to my script's own log file.

It's certainly better than nothing, and I'm not sure what a better solution would look like myself.  Perhaps using Python's ```logging``` module would help; I know almost nothing about it, but the summary says "your application log can include your own messages integrated with messages from third-party modules", so presumably it makes this easy somehow.

**Comment by jquast** [comment]
Closing, pexpect's terminal emulation code remains next release but no longer improved, marked deprecated by https://github.com/pexpect/pexpect/pull/240 Suggest any terminal emulation / screen scraping code efforts moved to more concerted project efforts such as https://github.com/selectel/pyte
