### ISSUE TITLE
Tab characters are not expanded by screen/ANSI

### ISSUE THREAD

**Issue by dcoshea** [pexpect/pexpect#95]
Neither the screen class, nor its ANSI subclass, expands tab characters.  Instead, the tab character (\x09) is literally stored in a character cell.  If this occurs and the screen contents are then retrieved and output to a normal terminal, the tab characters will be expanded at that point, but if the ```pretty()``` method is used, the right-hand border will not be aligned properly due to the expansion of the tabs.

The screen class provides some methods for dealing with setting tab stop positions, but they are not implemented or called.

It would be nice if, at the very least, tab characters caused the cursor to be moved to the standard/default tab stops.

This is fairly low priority for me, I might not get around to fixing it.

**Comment by dcoshea** [comment]
I'm using [pyte](https://github.com/selectel/pyte) instead of pexpect.ANSI now (based on [jquast's suggestion](https://github.com/pexpect/pexpect/issues/83#issuecomment-49235769)) and it seems to take care of tab characters properly.

I don't know if pexpect.ANSI has been enhanced in the time since I got it and started filing all these bugs (I never grabbed a newer version of pexpect in the meantime), but perhaps it would be worth considering deprecating pexpect.ANSI and suggesting that pyte be used instead?  One thing I did note that pyte lacks is any diagnostics when invalid escape sequences are received, but I didn't notice anything else missing that pexpect.ANSI has.

**Comment by jquast** [comment]
Closing, pexpect's terminal emulation code remains next release but no longer improved, marked deprecated by https://github.com/pexpect/pexpect/pull/240 Suggest any terminal emulation / screen scraping code efforts moved to more concerted project efforts such as https://github.com/selectel/pyte
